### ISSUE TITLE
REFPROP linking with MATLAB

### ISSUE THREAD

**Issue by ashuraj25** [ibell/coolprop#101]
I am getting continuous error for the MATLAB regarding REFPRP64.dll saying that there is error in the license file. Please tell the website to download it as the one i got from nist faq link is not working. And the procedure to link it up.

**Comment by ibell** [comment]
Do you have a file REFPRP64.dll in your REFPROP folder?  What exactly is
the error you get?  Can you provide a minimal example that can replicate
this error?

Also, you are calling REFPROP through CoolProp, right?

**Comment by ashuraj25** [comment]
@ibell  Yes i have a file REFPRP64.DLL in my REFPROP folder. The exact error I am getting is shown below.
Error in ==> refpropm at 202
            if archstr == 'win64'
I took the refprop example in the example folder and i got this error.
Can u tell the complete steps to be followed since the installation of MATLAB 2010?

**Comment by ibell** [comment]
You are using a rather older version of MATLAB, that might be the problem.
Also, this is not related to CoolProp in any way, but I will try to help
anyway.  Are you using mixtures?  If not, you might just want to use
CoolProp.  Then it is a very simple process to get CoolProp working with
MATLAB.

What platform are you on? Windows/Linux/OSX? 32-bit/64-bit? The REFPROP DLL
will only work on Windows.

Is there more to that error message?

**Comment by ashuraj25** [comment]
@ibell No I am not using mixture I am using super critical carbon dioxide as the fluid . If it is available in cool prop please tell the way to instal and obtain it? I am working on windows 64 bit that might be the problem I think.

The error message is coming only that much

**Comment by jowr** [comment]
I agree with Ian, this seems to be independent from CoolProp. However, in order to get CoolProp for your supercritical CO2, please go to http://coolprop.sourceforge.net/ and choose your favourite language/software (probably Matlab).

**Comment by ibell** [comment]
You can download the precompiled version for MATLAB from
http://sourceforge.net/projects/coolprop/files/CoolProp/4.0.0/MATLAB/ , put
it somewhere on your MATLAB path, and then you should be able to run the
example from http://coolprop.sourceforge.net/examples/MATLAB/example.html

Best of luck

**Comment by ashuraj25** [comment]
@ibell  Thanks . do we need to download Props.mexw64 or HAProps.mexw64 ?

**Comment by jowr** [comment]
HAProps for humid air, Props is for pure, pseudo-pure and incompressible fluids.

**Comment by ashuraj25** [comment]
@jowr Thanks

**Comment by ashuraj25** [comment]
@ibell @jowr Please tell in which of the two files does supercritical carbondioxide lie as i believe it is a compressible fluid . and neither it is a humid air.

**Comment by ibell** [comment]
Do you mean this:
http://coolprop.sourceforge.net/Fluids/CarbonDioxide.html?  Otherwise
I don't understand your question.

**Comment by ashuraj25** [comment]
@ibell Thanks.. got it..

**Comment by basmahd** [comment]
hello , Please help !!!
i would ask how can i define a mixture fluids with matlab link refprop? thank you in advance

**Comment by jowr** [comment]
Are you really using version 4.2.6? This version does not support mixtures, please change to a recent CoolProp version.

**Comment by ibell** [comment]
@basmahd Please open a new issue and do not hijack previous issues!
