### ISSUE TITLE
Allow array-like data as input to Props calculations (enhancement)

### ISSUE THREAD

**Issue by bachc** [ibell/coolprop#103]
CoolProp.CoolProp.Props does not seem to allow arrays as inputs to property functions, e.g. Props('H','Q',0.0,'T',np.array([250.,270.,280.]),'R410A')
results in an error.

It would sometimes be convenient to do calculations like these.

Please disregard this suggestion if already implemented in a newer version of CoolProp

Thanks!

**Comment by ibell** [comment]
Yup, fixed a while ago, we agreed about the utility of this functionality
