### ISSUE TITLE
Sun-Ely EOS

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#105]
Hey @ibell, the authors of http://inside.mines.edu/~jely/Papers/FPE_222%281%29_107.pdf claim to have a more accurate EOS for some alkanes and refrigerants. Should we consider implementing it? Are there any known issues?

**Comment by ibell** [comment]
I think for fluids that we already have implemented, we are implementing
better EOS in most cases (but not all).  The EOS for 1-Propanol is
interesting though.  We don't have that in CoolProp.

**Comment by ibell** [comment]
The issue too is that a lower AAD doesn't necessarily mean a better EOS.
Extrapolation behavior is critical.

**Comment by ibell** [comment]
Ugh, they don't provide critical information for these fluids.

**Comment by thorade** [comment]
I guess you are aware of the Span-Wagner publication on extrapolation: http://dx.doi.org/10.1007/BF02575343  

Also, the quality of EoS and the quality of extrapolation can be assessed using plots of ideal curves, like Boyle curve, Ideal curve, Joule-Thomson inversion curve and Joule inversion curve, as discussed on page 84 of the Lemmon HFC-125 publication http://dx.doi.org/10.1063/1.1797813

If not already implemented, plots for the ideal curves would be a nice addition.

**Comment by ibell** [comment]
Matthis,

That sounds like you are offering to add the ideal curves, right? :)
I agree that that would be a nice addition!

**Comment by thorade** [comment]
I should have known you would suggest that before making smart comments...
Should be fun to plot these curves, so yes, I'll see what I can do, but let me finish my PhD thesis first. Trying to submit before february 10th.

**Comment by ibell** [comment]
@thorade Good luck finishing your thesis, but adding the ideal curves would be great.  And we could add a section to the docs about evaluating the quality of EOS too.  That would be nice.  I can probably help some too.  Should we open a separate issue that I give to you?

**Comment by thorade** [comment]
You are right, this issue was about the Sun-Ely EoS.
I'll open a seperate issue once I start actually working on it. So far, I have only read two papers. Probably I'll need some help then.

**Comment by ibell** [comment]
Closing since this paper does not provided the necessary critical parameters - thus impossible to implement the EOS
