### ISSUE TITLE
Using Coolprop on Excel 2010 for OSX

### ISSUE THREAD

**Issue by jsebastiangalvis** [ibell/coolprop#106]
I've been trying to use Coolprop for Excel on OSX, but I haven't been able since the .DLL file is compiled for working with Windows. 

There's an alternative for this, or there's someone already developing the file on a parallel format?

Please help.

Thanks.

**Comment by jowr** [comment]
Sorry, I am not aware of such activities and none of the developers is actively using a Mac with MS Office... Feel free to contribute. 

If you are lucky, @ibell might find the time to look into it, but I cannot help. Good luck!

**Comment by ibell** [comment]
I am not sure it is possible to use CoolProp with Excel on OSX.  You definitely will not be able to use the DLL provided as it has been compiled for windows.  I can do a bit of investigation.

**Comment by jowr** [comment]
Isn't this an issue already?

**Comment by ibell** [comment]
Yup, sorry I just copied pasted from my email, I edited the comment

**Comment by ibell** [comment]
Looks like Excel 2010 on Mac doesn't have VBA, so I don't think you can call DLL then.  Excel 2011 seems to have brought VBA back.  That looks more promising.
