### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mitralavasani** [ibell/coolprop#111]
how use coolprop2fluent ?

**Comment by jowr** [comment]
I am afraid you cannot use Fluent and CoolProp at the moment. It is a work in progress, please have a look at https://github.com/ibell/coolprop/issues/54.

**Comment by mitralavasani** [comment]
but in the cfd-online/forum 
http://www.cfd-online.com/Forums/main/125043-now-possible-have-open-source-real-gas-properties-fluent-other-cfd-codes.html

it say that we can use it in fluent 
please help me ,i need it 
thanks

**Comment by ibell** [comment]
Did you try to run the build script? Did it compile?

**Comment by ibell** [comment]
Closing for now.  Please open a new issue in the future with a clear title summarizing the problem ("help" is not specific) and a summary of what you have tried, and what errors you run into. Comments like "it doesn't work" make it very hard for us to help you.
