### ISSUE TITLE
Variation of H and S from expected values

### ISSUE THREAD

**Issue by Rod-Persky** [ibell/coolprop#112]
Using coolprop to calculate Enthal- and Entropy, for a few fluids I've found that the result isn't as expected. For example, using the snippet:

``` cpp
  enable_TTSE_LUT("argon");
  CoolPropStateClassSI fluid_stateclass("argon");
  fluid_stateclass.update(iT, 392.171, iP, 3344.86e3);
  printf("H = %f, S = %f rho = %f\n",
         fluid_stateclass.h(), fluid_stateclass.s(), fluid_stateclass.rho());
```

I've found that the output is

``` bash
H = 45369.656194, S = -593.988731 rho = 41.009765
```

I was expecting values in the order of:
H (Enthalpy) = 200.50 [KJ/kg] and  S (Entropy) = 3.2795 [Kj/Kg-K]

Rho is spot on! This is repeated for a few other fluids such as R143a.

**Comment by jowr** [comment]
Just a guess: Check the reference point. Enthalpy and entropy have arbitrary 0 points. What counts is the difference from point A to point B. If you compare with other software, make sure you either set the reference conditions or that you only compare differences.

**Comment by thorade** [comment]
There are at least three commonly used reference points, you might want to check what values you get for the following input:
- IIR: saturated liquid at T=0°C=273.15 K is set to h=200kJ/kg and s=1kJ/kgK
- ASME: saturated liquid at T=-40°C=233.15K  is set to h=0 and s=0
- NBP: saturated liquid at p=1.01325 bar is set to h=0 and s=0

**Comment by ibell** [comment]
FYI, you can also change the reference state for the fluid.  From Python:
http://coolprop.sourceforge.net/apidoc/CoolProp.html#CoolProp.CoolProp.set_reference_state.
For some reason the text has been cut off in the first type (I'll fix it
).  But in principle doing something like
set_reference_state('Propane','IIR') should change the reference state to
IIR.

**Comment by Rod-Persky** [comment]
Thanks @ibell @thorade @jowr 

I was getting in a tizz about the negative numbers! Anyway, I'm back on track now... hopefully

**Comment by Rod-Persky** [comment]
Related to that, I was curious about IIR - So I did a pretty dumb test:

``` cpp
  printf("Without IIR:\n");
  std::string fluid_name = "R143a";
  set_standard_unit_system(UNIT_SYSTEM_SI);
  auto fluid_stateclass = new CoolPropStateClassSI((char *) fluid_name.c_str());
  fluid_stateclass->update(iT, 392.171, iP, 3344.86e3);
  fluid_stateclass->update(iH, fluid_stateclass->h(), iS, fluid_stateclass->s());
  delete fluid_stateclass;


  printf("With IIR:\n");
  set_standard_unit_system(UNIT_SYSTEM_SI);
  set_reference_stateS(fluid_name, "IIR");
  fluid_stateclass = new CoolPropStateClassSI((char *) fluid_name.c_str());
  fluid_stateclass->update(iT, 392.171, iP, 3344.86e3);
  fluid_stateclass->update(iH, fluid_stateclass->h(), iS, fluid_stateclass->s());
  delete fluid_stateclass;
```

Which has the result:

``` bash
Without IIR:
With IIR:
terminate called after throwing an instance of 'ValueError'
  what():  HS inputs are solid - not allowed h: 488045 s: 1856.81
```

It doesn't particularly matter that IIR doesn't work, I'm using the former method just fine. So I've reclosed the issue sorry.

**Comment by ibell** [comment]
@Rod-Persky The set_reference_state is applied to the fluid instance that is stored in the main fluid container.  Such that calls through Props() or PropsSI() would get the right reference state.  You instantiated the fluid directly, and thus the class doesn't have its reference state updated.  But if you use the set_reference_stateP(https://github.com/ibell/coolprop/blob/master/CoolProp/CoolProp.cpp#L1020) function, it will apply to a fluid class directly.  Hope that helps.  Any idea why you get that uncaught exception?
