### ISSUE TITLE
TTSE has become slow from Modelica

### ISSUE THREAD

**Issue by squoilin** [ibell/coolprop#113]
In coolprop2Modelica, the benchmark test with propane and the TTSE method give 332 microseconds while it use to be less than 10

**Comment by ibell** [comment]
Hmm.  Weird.  I can add a test at the c++ level to test the speed of
TTSE.  What inputs do you use for the test?

**Comment by squoilin** [comment]
Looks like it was a problem on my computer... cannot reproduce it on other machines
