### ISSUE TITLE
Thermal conductivity and TTSE

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#114]
Something is wrong with the thermal conductivity calculation when using TTSE. I will try to fix things myself, but if anyone is going to mess around with TTSE due to Sylvain's issue (https://github.com/ibell/coolprop/issues/113), it would be nice if you kept an eye open for this as well. 
![lambda](https://f.cloud.github.com/assets/769593/2011390/2d28edc6-877a-11e3-9d19-7c5ce3fe4060.png)
The graphs show thermal conductivity of R134a around the two-phase region at 5 bar. The red line is without TTSE and the blue is with activated TTSE. Do not get surprised, I also activated extended two-phase properties...

**Comment by ibell** [comment]
Perhaps this could be related to a kSI/SI units conversion problem
somehow?  Does this behavior exist with other fluids?

**Comment by jowr** [comment]
Good guess, but there is also something else going on. In attached a plot of thermal conductivity of SES36. The x-axis shows subcooling and superheat at `0.75*p_crit` in Kelvin. Note how the graph jumps back to its normal value for higher temperatures. The same can be observed for other fluids as well. I currently make a list of fluids where this occurs. 
![ses36](https://f.cloud.github.com/assets/769593/2018732/915b0046-8814-11e3-94c9-945374667524.png)

I made a script that checks the differences and the output for the graph shown above is: 

```
There were problems with SES36
Relative difference liquid: 0.999000082893
Relative difference vapour: 0.539460016261
Average factor liquid: 1000.08292667
Average factor vapour: 540.476277593
```

**Comment by jowr** [comment]
fixed, it was mostly the units...
