### ISSUE TITLE
CPP wrapper on Linux

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#116]
@Rod-Persky is there a special reason for putting the `libCoolProp.so` in `/usr/include`? I once learned to put header files in the `include` folders and libraries into `/usr/lib`... I also had to change the permission in order to call the file with other users than root. Would you mind if I changed those settings?

**Comment by Rod-Persky** [comment]
Hi @jowr that's fine, I did whatever was necessary to get it all running on my computer - I'm actually unaware of the correct location to install things and that was the first that worked.

**Comment by jowr** [comment]
I removed the original folder since CPP does not need a wrapper, it is just a shared object, see ea2028ea5fb9a8dfb4278eeb5a693e8cf049a54c for details. I also wrote a build script for Windows and made the exports aware of the `extern "C"` notation.

**Comment by Rod-Persky** [comment]
Jorrit,
I was actually using the shared / static library generated by the CPP Makefile in a number of projects. Sorry I don't understand how to use coolprop as a library without the coolprop library. Would we be able to add this back?

**Comment by jowr** [comment]
Is this what you are looking for:  https://github.com/ibell/coolprop/tree/master/wrappers/SharedLibrary ? 
Sorry if I confused you.

**Comment by Rod-Persky** [comment]
Ahh there it is! Thanks.
