### ISSUE TITLE
Make all fluid transport properties use SI units internally

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#121]
A nightmare to debug, I keep running into unit problems, though Catch is helping.

**Comment by ibell** [comment]
@jowr, I fixed this for pure and pseudo-pure fluids I think, what about the incompressibles/solutions?  Can we easily make them also always return SI (W/m/K) units?

**Comment by ibell** [comment]
See also 9a000495d76de8181c363c25a22427b0f8d24086

**Comment by jowr** [comment]
Don't they already return SI units? I think they do. I remember changing everything to SI when I rewrote the incompressible classes...

**Comment by ibell** [comment]
Ok cool, there's just some funny business for brines for conductivity(
https://github.com/ibell/coolprop/blob/master/CoolProp/CPState.cpp#L1462)
and viscosity(
https://github.com/ibell/coolprop/blob/master/CoolProp/CPState.cpp#L1441)
.  You're the expert on those!

**Comment by jowr** [comment]
Yes, I know. The problem is that we need to construct the string
containing the concentration. Calling the Props function returns values
in kSI, therefore the conversion. There does not seem to be a way around
this until we handle concentration properly.

**Comment by ibell** [comment]
Ah right that makes sense.  I think everything else is now SI
