### ISSUE TITLE
building the docs

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#124]
I understand that this is under heavy development (see https://github.com/ibell/coolprop/issues/99 and https://github.com/ibell/coolprop/issues/94), but I cannot get the docs to build. 
- There is a `Fluids` folder missing in `Web`
- Sphinx uses deprecated modules `exception: cannot import name xfileref_role` should be replaced by `sphinx.roles.XRefRole` 
- Parsing the BibTex file throws an exception `File "Web/parse_bib.py", line 59, in entry2rst`

Could anyone please update me with what the plans for the future are? Is this temporarily broken because we change to another system? I am afraid I cannot follow your discussion on IPythn notebooks and the RTD website.

**Comment by ibell** [comment]
1. With regards to the Fluids folder, the FluidInfoGenerator.py should fill
   that folder with the Fluid .rst files
2. What version of Sphinx do you use?  I don't get that error on Windows
   and the docs build more or less cleanly for me.
3. I don't get that parsing error either - can you give the full traceback?

With regards to the future, I am not 100% sure about the use of RTD.  I am
concerned that you can't compile CoolProp on it, so you don't have access
to the api documentation, which is a concern for me.  There might be a way
by using intersphinx, but that would take some work too.  There are a lot
of incompatabilities between our Sphinx build and RTD, some of which are
possible to fix, others which are not.  To be continued.

**Comment by jowr** [comment]
No problem, I just created the Fluids folder and that is fine

This is my output, obviously Sphinx 1.2:

```
make latex
sphinx-build -b latex -d _build/doctrees   . _build/latex
Making output directory...
Running Sphinx v1.2

Extension error:
Could not import extension inheritance_diagram (exception: cannot import name xfileref_role)
make: *** [latex] Error 1`
```

... and here the full error from the fluid generator: 

```
jowr@MEK-403-111-02P ~/Documents/Fluids/CoolProp.git/Web $ python FluidInfoGenerator.py 
{E. K. Michailidou and M. J. Assael and M. L. Huber and R. A. Perkins}
Traceback (most recent call last):
  File "FluidInfoGenerator.py", line 661, in <module>
    s = fluid_header(Fluid) + params_table(Fluid) + critical_table(Fluid) + SatVaporParity(Fluid) + SatLiquidParity(Fluid) + CriticalIsotherm(Fluid) + PropertyConsistency(Fluid)
  File "FluidInfoGenerator.py", line 342, in fluid_header
    BibInfo += '**Viscosity**: ' + BTC.entry2rst(VISCOSITYkey) + '\n\n'
  File "/mnt/crypt/Documents/Fluids/CoolProp.git/Web/parse_bib.py", line 59, in entry2rst
    raise ValueError
ValueError
```

It's not crucial, but would be nice if it worked. I could also spend some time myself next week to get things fixed...

**Comment by ibell** [comment]
@jowr The crux of the problem with Fluids folder is that you can't commit
an empty folder (annoying) in git, only files.  I should add a line to make
that folder if it doesn't already exist.

Try to disable the inheritance_diagram in conf.py ? I can't get it to work
anyway on windows.

I'll take a look at the other one tomorrow.  It does work for me on
windows, so I might need your help to debug.  At the least, I should raise
a more useful error than ValueError!  Perhaps once I do that you can give
me some debug output.

**Comment by jowr** [comment]
Works! Thanks.

**Comment by ibell** [comment]
Good to hear!  There was a bug that I added to the BibTeX file that was
causing that error with the bibtex parsing.  Oops :)
