### ISSUE TITLE
Bug with Matlab wrapper

### ISSUE THREAD

**Issue by BartoszBB** [ibell/coolprop#126]
The input for which coolprop fails (it's only example- thera are others):
H_Cs=132.729899237037
P_Cs=4997.12399496759
with call like this:
T_Cs=Props('T','H',H_Cs,'P',P_Cs,'water');
I get:
CoolProp error: Number of steps in density_TP has exceeded 30 with inputs T=273.16,p=4.99712e+006,rho_guess=1002.73 for fluid Water

I have tried to use CoolProps via MathCad wrapper for above values, and it works.

I use the latest-4.0.0 ( x64mex)

**Comment by ibell** [comment]
Fixed this particular issue in 0ef190a294f50816e60201cc9d42342c106739f1 Please file a more general issue if you can figure out what is causing the failure.  Thanks
