### ISSUE TITLE
Problem with fortran wrapper example

### ISSUE THREAD

**Issue by adalib** [ibell/coolprop#129]
Hi,

I have tried to run the fortran wrapper example. I could build the CoolProp.dll but I cannot create the example.exe with the build.bat file (see screenshot of the cmd windows above). I also tried to call the produced CoolProp.dll from a own fortran code but the program could not recognized the coolprop functions.
Thanks in advance for your help

![screenshot](https://f.cloud.github.com/assets/6636964/2123451/6370d890-922d-11e3-828a-82bdbc658c02.png)

**Comment by jowr** [comment]
The compiler cannot find the dll. You have to include the path to the dll in your build process. Please have a look at line 12 in the bat file. https://github.com/ibell/coolprop/blob/master/wrappers/Fortran/build.bat#L12

**Comment by adalib** [comment]
I tried to include the path where my CoolProp.dll is but I got the same error. Sorry I have no experience with bat file, maybe I did something wrong... here is the line 12 of my modified bat file:
%FC% -g -o example examplef.o coolpropIF.o -Lc:\Users\antoine.dalibard\Desktop\CoolProp-4.0.0-windows_superpack\dist_temp\windows_superpack\CoolProp-4.0.0-source_code\wrappers\SharedLibrary -lCoolProp

**Comment by jowr** [comment]
Well, it is very difficult to debug things from afar, but are you sure you have all the prerequisites installed? I mean, what kind of Fortran compiler are you using and how about the C-compiler? 
For my personal setup, I installed python-xy, which includes the compilers and libraries needed.

**Comment by adalib** [comment]
No I am not sure. I downloaded the CoolProp version from the website with Option 1. So I needed to download separately the wrapper/fortran files as well as the wrapper/SharedLibrary files to add them to my directory structure. Then I have installed MinGW (with include C and fortran compilers) in order to run this example.

Normally I use Microsoft visual studio 2008 und Intel visual Fortran v11.1. In the future I would like to use CoolProp functions from fortran code compiled with IVF.

**Comment by jowr** [comment]
OK, so let's start from the beginning. 
1. Could you please get the zip file from https://github.com/ibell/coolprop/archive/master.zip
2. Unpack the zipfile to a directory of your choice. 
3. Build the shared library for your system by running `wrappers\SharedLibrary\BuildDLL.bat`
   Please let me know if that works. 

If successful, you can proceed and adjust the paths to the executables in line 5 and 6  of `wrappers\Fortran\build.bat` and try to execute that script.

**Comment by adalib** [comment]
Ok, now it works! Thanks

Now I am not sure I fully understood how to call this CoolProp.dll from a fortran program. Sorry I am not a developer (as you probably already noticed). I just code some TRNSYS models in fortran. I would like to know how I can call CoolProp functions from a fortran code. I use Intel Visual Fortran V11.1 and Microsoft visual studio 2008.

thanks

**Comment by jowr** [comment]
There are a couple of pitfalls, but you should try to do as follows:
1. Make the shared library (you already did)
2. Put the library into your PATH (either by changing your environment variable PATH to include the CoolProp directory or by copying the DLL to a system folder like `C:\Windows\system`.
3. Compile Fortran code and remeber to tell the linker where the DLL is using the `-L` option for the path to the dll and the `-l` option for the DLL name.

This should be all (in theory).

**Comment by ibell** [comment]
@jowr - For TRNSYS, I think they use another compiler (Intel?) which could
make it difficult to link up with CoolProp.  But it should be only a case
of changing the compiler that is used, right?  That could be a tricky one
to debug though since I don't have access to TRNSYS or Intel FORTRAN

**Comment by jowr** [comment]
Yes, it could get difficult since I also do not have access to an Intel compiler...
I tried to prepare for the worst case by writing a C file that calls the dll. It works for us, but our section uses only g77 and gfortran. Let's hope for the best.

**Comment by adalib** [comment]
yes we use Intel Visual Fortran for TRNSYS. I tried in a simple program to call CoolProp functions 

```
  program CallCoolProp
  IMPLICIT NONE
  !DEC$ ATTRIBUTES DLLIMPORT::CoolProp
  DOUBLE PRECISION T,PROPS
  T=Props('T','P',101.325,'Q',0,'Water')
  end
```

But it did not work (did not recognize Props function) although I put the CoolProp.dll in the project directory. Something is missing here... probably what the file "CoolPropIF.c" does in the example. But I dont know how to solve this issue.

**Comment by jowr** [comment]
Exactly. You do not have to load the DLL in Fortran, the C interface takes care of that. You have to link the Fortran object with the C object. The Fortran code will call the C functions, which in turn call the dll. It is not the cleanest way, but this is how I could get it to work. This is exactly what happens in https://github.com/ibell/coolprop/blob/master/wrappers/Fortran/build.bat
1. compile Fortran (line 10)
2. compile C (line 11) 
3. link compiled objects with library (line 12) 

I recommend you to follow the same procedure. It sounds like this really is a basic problem and maybe you can get a colleague or a friend to help you with this since it is much easier when you sit in front of the same machine...

**Comment by adalib** [comment]
Ok I will try to do so. I will let you know if I manage to do it. Thanks a lot for your help

**Comment by jowr** [comment]
Antoine, I talked to some colleagues today, but no one here uses the Intel compiler. I now applied for a trial download of the software and installed it. Let's see if I can help you on Wednesday...

**Comment by ibell** [comment]
I had the idea I would buy the Intel compiler so that we could do some
debugging, and then I looked at this page :
http://software.intel.com/en-us/fortran-compilers .  Crap that's expensive.

**Comment by jowr** [comment]
Well, it took me some time, but now I can make a C call from Fortran using Intel Visual Fortran and Visual Studio for C. I had no luck with CoolProp though. I'll try again tomorrow.

**Comment by jowr** [comment]
You might also want to ask Intel's support. The product isn't cheap and I guess some sort of support must be included.

**Comment by AllanStarke** [comment]
I'm trying to compile the Fortran wrapper example with Intel Visual Studio on windows, but I'm having some trouble. 

The problem looks like to be in the linker. I can't link the coolprop.dll with the C interface. I built a project with only the C interface and try to compile. I try with in the Visual studio, and with the intel command line prompt. No successes.

Although, using the gcc at linux, it works fine.

I see that you can make a C call from Fortran with IVF, do you have some tip?

**Comment by ibell** [comment]
Can you send us screenshots of the errors?  @jowr, any words of wisdom?

**Comment by AllanStarke** [comment]
![fortran_wrapper_error](https://cloud.githubusercontent.com/assets/7434461/2835458/80470288-cfe9-11e3-89da-1212491939a1.png)

same error, using the command line prompt. 
Using the Intel fortran in linux, we are able to compile an run the fortran example. 

Tank you

**Comment by AllanStarke** [comment]
Hi,

to understand how the coolProp works, we are trying to run the c++ example, from the website. But we are getting this error:

g++ teste_c.cpp -L./ -lCoolProp -ldl -I ../../CoolProp

```
/tmp/ccsBw3ON.o: In function `main':
teste_c.cpp:(.text+0x1f7): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
teste_c.cpp:(.text+0x3d7): undefined reference to `Props1(char const*, char const*)'
teste_c.cpp:(.text+0x444): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
teste_c.cpp:(.text+0x4ab): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
teste_c.cpp:(.text+0x518): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
teste_c.cpp:(.text+0x57f): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
teste_c.cpp:(.text+0x5f0): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
/tmp/ccsBw3ON.o:teste_c.cpp:(.text+0x63d): more undefined references to `PropsSI(char const*, char const*, double, char const*, double, char const*)' follow
/tmp/ccsBw3ON.o: In function `main':
teste_c.cpp:(.text+0x798): undefined reference to `enable_TTSE_LUT(char const*)'
teste_c.cpp:(.text+0x7d8): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
teste_c.cpp:(.text+0x83f): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
teste_c.cpp:(.text+0x8b1): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
teste_c.cpp:(.text+0x918): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
teste_c.cpp:(.text+0x989): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
/tmp/ccsBw3ON.o:teste_c.cpp:(.text+0x9d6): more undefined references to `PropsSI(char const*, char const*, double, char const*, double, char const*)' follow
/tmp/ccsBw3ON.o: In function `main':
teste_c.cpp:(.text+0xb27): undefined reference to `disable_TTSE_LUT(char const*)'
teste_c.cpp:(.text+0x184d): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
teste_c.cpp:(.text+0x18c5): undefined reference to `PropsSI(char const*, char const*, double, char const*, double, char const*)'
teste_c.cpp:(.text+0x1960): undefined reference to `HAProps(char const*, char const*, double, char const*, double, char const*, double)'
teste_c.cpp:(.text+0x19f1): undefined reference to `HAProps(char const*, char const*, double, char const*, double, char const*, double)'
teste_c.cpp:(.text+0x1a5a): undefined reference to `HAProps(char const*, char const*, double, char const*, double, char const*, double)'
collect2: error: ld returned 1 exit status
```

The program can't find several function on the coolprop.dll. For the first error, if a change the PropsSI, for props. This function call works. 

We don't know what is going on?!

**Comment by jowr** [comment]
I can confirm the errors. I will look into that when I have the time (probably during the weekend).

**Comment by ibell** [comment]
@jowr, You know how to build the examples?  I should have probably provided
some instructions for the compiled languages (C++, JAVA, etc.)  Take a look
at the build file at
https://github.com/ibell/coolprop/blob/master/Web/examples/C%2B%2B/run_example.bat

**Comment by jowr** [comment]
Thanks, but I know these files... I simply need to take a closer look at the code.

**Comment by AllanStarke** [comment]
About the C++ example, I did't know the existence of the run_example.bat. I will take a look on that.

We are able to compile the exemplof.for on linux and windows. But,
1. on linux the program works, but the results looks like to be wrong.
2. on windows, the compilations works, but the program don't, problems with the variable that are delivered to the Props function. (I'll investigate this later);

We will review all the steps taken until now, to check if we did something wrong.

One last question, There is the possibility to create the Interface with the BIND(C) statement (C Interoperability features of Fortran 2003)?

Best Regards'

**Comment by jowr** [comment]
I never tried the `BIND(C)` features of newer Fortran flavours... 

We are using old Fortran code with CoolProp on MacOS, Windows and Linux with 32bit and 64bit without any problems. Here is my C-interface:

```

#include <string.h>
#include <stdio.h>
#include <stdbool.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(_WIN64) || defined(__WIN64__)
#  define CONVENTION __declspec(dllexport)
#endif

#ifndef CONVENTION
#  define CONVENTION
#endif

double CONVENTION Props1 (char * FluidName, char * Output);
double CONVENTION Props  (char * Output,char Name1, double Prop1, char Name2, double Prop2, char * FluidName);
double CONVENTION PropsSI(char * Output,char Name1, double Prop1, char Name2, double Prop2, char * FluidName);
double CONVENTION DerivTerms(char * Term, double T, double rho, char * FluidName);
int CONVENTION set_reference_stateS(char * FluidName, char * reference_state);
bool CONVENTION enable_TTSE_LUT(char *FluidName);
bool CONVENTION isenabled_TTSE_LUT(char *FluidName);
bool CONVENTION disable_TTSE_LUT(char *FluidName);
int CONVENTION set_TTSE_mode(char *FluidName, char * Value);
void CONVENTION set_debug_level(int level);


/* Create pointer-only functions for Fortran avoiding underscores for f77 */
double CONVENTION props1_(char *FluidName, char *Output)
{
  /* return Props1(std::string(FluidName), std::string(Output)); */
  return Props1(FluidName, Output);
}

double CONVENTION props_(char *Output, char *Name1, double *Prop1, char *Name2, double *Prop2, char *FluidName)
{
  /* return Props(std::string(Output), Name1, Prop1, Name2, Prop2, std::string(FluidName)); */
  return Props(Output, *Name1, *Prop1, *Name2, *Prop2, FluidName);
}

void CONVENTION propsmod_(char *Output, char *Name1, double *Prop1, char *Name2, double *Prop2, char *FluidName, double *resu)
{
  /* return Props(std::string(Output), Name1, Prop1, Name2, Prop2, std::string(FluidName)); */
  *resu = Props(Output, *Name1, *Prop1, *Name2, *Prop2, FluidName);
/*   printf("res: %4.2f \n", *resu);
//   printf("out: %s    \n", Output);
//   printf("res: %s    \n", Name1);
//   printf("res: %4.2f \n", *Prop1);
//   printf("res: %s    \n", Name2);
//   printf("res: %4.2f \n", *Prop2);
//   printf("res: %s    \n", FluidName);  */
}

double CONVENTION propssi_(char *Output, char *Name1, double *Prop1, char *Name2, double *Prop2, char *FluidName)
{
  /* return Props(std::string(Output), Name1, Prop1, Name2, Prop2, std::string(FluidName)); */
  return PropsSI(Output, *Name1, *Prop1, *Name2, *Prop2, FluidName);
}

double CONVENTION derivterms_(char *Term, double *T, double *rho, char *FluidName)
{
  /* return DerivTerms(std::string(Term), T, rho, std::string(FluidName)); */
  return DerivTerms(Term, *T, *rho, FluidName);
}

int CONVENTION setreferencestates_(char *FluidName, char *reference_state)
{
  /* return set_reference_stateS(std::string(FluidName), std::string(reference_state)); */
  return set_reference_stateS(FluidName, reference_state);
}
/* int set_reference_stateS(std::string FluidName, std::string reference_state); */

/*  Enable the TTSE */
int CONVENTION enablettselut_(char *FluidName)
{
  if (enable_TTSE_LUT(FluidName)) return 1;
  else return 0;
}
/* bool CONVENTION enable_TTSE_LUT(char *FluidName); */

/*  Check if TTSE is enabled */
int CONVENTION isenabledttselut_(char *FluidName)
{
  if (isenabled_TTSE_LUT(FluidName)) return 1;
  else return 0;
}
/* bool CONVENTION isenabled_TTSE_LUT(char *FluidName); */

/*  Disable the TTSE */
int CONVENTION disablettselut_(char *FluidName)
{
  if (disable_TTSE_LUT(FluidName)) return 1;
  else return 0;
}
/* bool CONVENTION disable_TTSE_LUT(char *FluidName); */

/*  Set the TTSE mode (normal or bicubic) */
int CONVENTION setttsemode_(char *FluidName, char *Value)
{
  return set_TTSE_mode(FluidName, Value);
}
/* int CONVENTION set_TTSE_mode(char *FluidName, char * Value); */

/*  Set the DEBUG mode */
void CONVENTION setdebuglevel_(int *level)
{
  /* int levels = level; */
  set_debug_level(level[0]);
}
/* void CONVENTION set_debug_level(int level); */
```

... and here is the Fortran file:

```
C**********************************************************************
      SUBROUTINE COOL_STATES(P, H, T, V, S, X, U, IN1, IN2, SP, COOLTAB)
C**********************************************************************
C  COOL_STATES controls the calculation of all state variables via 
C  CoolProp. Two inputs are given.
C
C
CP Programmer : Leonardo Pierobon 2014
CP              Thermal Energy, DTU-MEK, Denmark.
C***********************************************************************
C**********************************************************************
CA                   For IN1 and IN2 :  1 = P
CA                                      2 = H
CA                                      3 = T
CA                                      4 = V
CA                                      5 = S
CA                                      6 = X
CA                                      7 = U.
      INCLUDE 'ENVIRO.INI'
      DOUBLE PRECISION P, H, T, V, S, X, U, D
      INTEGER IN1,IN2,I,SP,COOLTAB(2,ANTCOOL+1)
      CHARACTER(LEN=80) FLUID

      DO I=1,ANTCOOL
        IF (SP.EQ.COOLTAB(1,I)) THEN
          FLUID  = COOLNAMES(I)
          GOTO 100
        ENDIF
      ENDDO   
100   CONTINUE

c ----
c P,H
c ---- 
      IF(((IN1.EQ.1).AND.(IN2.EQ.2)).OR.((IN1.EQ.2).AND.(IN2.EQ.1)))THEN

        P = 1D2*P
        CALL propsmod("T"//CHAR(0), "H"//CHAR(0), H,
     :  "P"//CHAR(0), P, TRIM(FLUID)//CHAR(0), T)
        CALL propsmod("S"//CHAR(0), "H"//CHAR(0), H,
     :  "P"//CHAR(0), P, TRIM(FLUID)//CHAR(0), S)
        CALL propsmod("D"//CHAR(0), "H"//CHAR(0), H,
     :  "P"//CHAR(0), P, TRIM(FLUID)//CHAR(0), D)
        CALL propsmod("Q"//CHAR(0), "H"//CHAR(0), H,
     :  "P"//CHAR(0), P, TRIM(FLUID)//CHAR(0), X)
c ----
c P,T
c ----       
      ELSE IF(((IN1.EQ.1).AND.(IN2.EQ.3)).OR.((IN1.EQ.3).AND.(IN2.EQ.1))
     :   )THEN

        P = 1D2*P
        T = T + 273.15
        CALL propsmod("D"//CHAR(0), "T"//CHAR(0), T,
     :  "P"//CHAR(0), P, TRIM(FLUID)//CHAR(0), D)
        CALL propsmod("S"//CHAR(0), "T"//CHAR(0), T,
     :  "D"//CHAR(0), D, TRIM(FLUID)//CHAR(0), S)
        CALL propsmod("H"//CHAR(0), "T"//CHAR(0), T,
     :  "D"//CHAR(0), D, TRIM(FLUID)//CHAR(0), H)
        CALL propsmod("Q"//CHAR(0), "T"//CHAR(0), T,
     :  "D"//CHAR(0), D, TRIM(FLUID)//CHAR(0), X)    
c ----
c P,S
c ----          
      ELSE IF(((IN1.EQ.1).AND.(IN2.EQ.5)).OR.((IN1.EQ.5).AND.(IN2.EQ.1))
     :   )THEN

        P = 1D2*P
        CALL propsmod("H"//CHAR(0), "S"//CHAR(0), S,
     :  "P"//CHAR(0), P, TRIM(FLUID)//CHAR(0), H)
        CALL propsmod("T"//CHAR(0), "S"//CHAR(0), S,
     :  "P"//CHAR(0), P, TRIM(FLUID)//CHAR(0), T)
        CALL propsmod("D"//CHAR(0), "S"//CHAR(0), S,
     :  "P"//CHAR(0), P, TRIM(FLUID)//CHAR(0), D)
        CALL propsmod("Q"//CHAR(0), "S"//CHAR(0), S,
     :  "P"//CHAR(0), P, TRIM(FLUID)//CHAR(0), X) 
c ----
c P,X
c ----    
      ELSE IF(((IN1.EQ.1).AND.(IN2.EQ.6)).OR.((IN1.EQ.6).AND.(IN2.EQ.1))
     :   )THEN

        P = 1D2*P
        CALL propsmod("T"//CHAR(0), "P"//CHAR(0), P,
     :  "Q"//CHAR(0), X, TRIM(FLUID)//CHAR(0), T) 
        CALL propsmod("H"//CHAR(0), "P"//CHAR(0), P,
     :  "Q"//CHAR(0), X, TRIM(FLUID)//CHAR(0), H)
        CALL propsmod("S"//CHAR(0), "P"//CHAR(0), P,
     :  "Q"//CHAR(0), X, TRIM(FLUID)//CHAR(0), S)
        CALL propsmod("D"//CHAR(0), "P"//CHAR(0), P,
     :  "Q"//CHAR(0), X, TRIM(FLUID)//CHAR(0), D)
c ----
c T,X
c ----    
      ELSE IF(((IN1.EQ.3).AND.(IN2.EQ.6)).OR.((IN1.EQ.6).AND.(IN2.EQ.3))
     :   )THEN

        T = T + 273.15
        CALL propsmod("P"//CHAR(0), "T"//CHAR(0), T,
     :  "Q"//CHAR(0), X, TRIM(FLUID)//CHAR(0), P)
        CALL propsmod("H"//CHAR(0), "T"//CHAR(0), T,
     :  "Q"//CHAR(0), X, TRIM(FLUID)//CHAR(0), H)
        CALL propsmod("S"//CHAR(0), "T"//CHAR(0), T,
     :  "Q"//CHAR(0), X, TRIM(FLUID)//CHAR(0), S)
        CALL propsmod("D"//CHAR(0), "T"//CHAR(0), T,
     :  "Q"//CHAR(0), X, TRIM(FLUID)//CHAR(0), D)
      END IF

      T = T - 273.15
      P = 1D-2*P
      V = 1/D
      U = H - 1D2*P*V
!      write(6,*)'FLUID: ','*',TRIM(FLUID),'*'
!      write(6,*)'IN1: ',IN1
!      write(6,*)'IN2: ',IN2
!      write(6,*)'T: ',T,'degC'
!      write(6,*)'P: ',P,'bar'
!      write(6,*)'H: ',H,'kJ/kg'
!      write(6,*)'D: ',D,'kg/m3'
!      write(6,*)'S: ',S,'kJ/(kgk)'
!      write(6,*)'U: ',U,'kJ/kg'     
      END SUBROUTINE
```

**Comment by ibell** [comment]
I guess the annoying pedant in me needs to note here that the char \* should
now be const char *.  But that shouldn't change much of anything.

**Comment by jowr** [comment]
Yes, I guess that should be updated. @AllanStarke, did you get anywhere?

**Comment by AllanStarke** [comment]
I am very busy in this week, and couldn't find time to analyze the last example..
but last week, we are able to write a fortran interface with the Bind(C) for the Props function. 

I will make some more tests and write some functions and modules to work whit Trnsys.

I'll document and write other example.f90 using the bind(C) to post here..

**Comment by jowr** [comment]
Great, please keep us posted. It would be nice to provide a more sophisticated example than my immature interface...

**Comment by ibell** [comment]
+1 on the BIND(C).  That would be really great if you could put that
together for the code in 4.2, we can port it over to 5.0 as well when we
get to that point.

**Comment by AllanStarke** [comment]
Hi, 

sorry to take to long to post the solution with the Bind(C). 
For now, I only have the interface for the Props function, here is the example:

```
program hello



use iso_c_binding!, only: C_CHAR, C_NULL_CHAR, C_DOUBLE

INTERFACE
    REAL(C_DOUBLE) FUNCTION Props  &
        (output, name1, prop1, name2, prop2, fluidname)    &
            BIND(C, NAME='Props@32')            
            USE ISO_C_BINDING
            IMPLICIT NONE
        character(kind=c_char) :: output(*)
        character(c_char), VALUE :: name1
        real(C_DOUBLE), VALUE :: prop1
        character(c_char), VALUE :: name2
        real(C_DOUBLE), VALUE :: prop2
        character(kind=c_char) :: fluidname(*)
    END FUNCTION Props
END INTERFACE

double precision T,Q,D,h,s
character(LEN=32) ref
character(LEN=2) output, name1, name2
double precision outval, propp1, prop2, outval2




T = 300
Q = 0
D = 1250;


output = "D"//CHAR(0)
name1  = "T"//CHAR(0)
propp1  = T
name2  = "Q"//CHAR(0)
prop2  = Q
ref    = "Propane"//CHAR(0)





outval = Props(output, name1, propp1, name2, prop2, ref)

outval2 = Props(output, "T"//CHAR(0), prop1, name2, prop2, ref)

Print *, outval


end program hello
```

Credits for,
Renan A. Starke
Allan R. Starke

**Comment by ibell** [comment]
Nice work! Can you please provide more information about how to use the
example, what versions of FORTRAN are supported, where files should be
placed, command line call used to build this example, etc.?  Any other
things that I am missing @jowr?  Please provide as a text file which I will
format appropriately.

Could this be placed in a module rather than importing all into this code
example itself?  Modular code is (almost) always better.  I'm a newbie at
FORTRAN programming, so pardon my ignorance.

**Comment by ibell** [comment]
Also can you document where you got the information about the BIND(C) stuff
so that we can do further reading?

**Comment by AllanStarke** [comment]
Hi, 

sorry for the lack of explanation. I am learning fortran too.

the example is only a console application that calls the function props. I'm reposting the code, with some comments and with the solutions files (Visual Studio).

We test this example at linux, with intel compiler (trial) and gfortran. And at windows with Visual Studio 2010 and intel fortran XE 2013. 

Basically you need to compile the fortran source to create the .obj and link this file with the coolprop.lib (SharedLibrary). This works at linux and windows with command lines. I don't remember the commands right now, I used that only once. 

About the version, I'm not sure, but in the intel's sample files of MixedLanguage is written:
"the C interoperability features first introduced in Fortran 2003" - referring the Bind(C)

Yes, the interface can be put in a module, I test it and works fine here. (Modules for globa data)

My next step is create some subrotines to adequate the coolprops with some old sources that I have. Thus, I don't need to change the old stuff, and concentrate only in the subrotines. 

About the documentation of Bind(C), I found in the Internet. I will try to find the links.

Follows the link of the visual studio solution,

https://www.dropbox.com/s/sxvs58stesic8d3/Fortran_bind_C.rar

```
program hello


    !Use TestData       ! Include a Module with the interface, Optional (to not re-write the Interface every at Subroutine or Program)

    use iso_c_binding
    implicit none 


!The interface to use the Props Function
INTERFACE
    REAL(C_DOUBLE) FUNCTION Props  &
        (output, name1, prop1, name2, prop2, fluidname)    &
            BIND(C, NAME='Props@32')            
            USE ISO_C_BINDING
            IMPLICIT NONE
        character(kind=c_char) :: output(*)
        character(c_char), VALUE :: name1
        real(C_DOUBLE), VALUE :: prop1
        character(c_char), VALUE :: name2
        real(C_DOUBLE), VALUE :: prop2
        character(kind=c_char) :: fluidname(*)

    END FUNCTION Props

END INTERFACE


!Here Start the programa


!Initializate the variables used in the example
   !implicit none   
double precision T,Q,D,h,s
character(LEN=32) fluid, PropName
character(LEN=2) out1, n1, n2
double precision dens1, dens2, prop1, prop2


!----------------------
!Example calculates: (Example Code for MATLAB)
!
!Density of saturated liquid Propane at 300 K:
!---------------------


T = 300                 ! Defining the temperature
Q = 0                   ! Defining the quality
!D = 1250;


out1 = "D"//CHAR(0)      ! String with of the output Propertie   
n1  = "T"//CHAR(0)       ! String with of the input Propertie #1
n2  = "Q"//CHAR(0)       ! String with of the input Propertie #2
fluid    = "Propane"//CHAR(0)   ! String with the fluid name


! From the CoolProp 4.2.1 documentation ->> CoolProp.CoolProp.Props
! Call Type #2:
!   Props(OutputName,InputName1,InputProp1,InputName2,InputProp2,Fluid) --> float
!

dens1 = Props(out1, n1, T, n2, Q, fluid)                                !calling props, strings are Variables

dens2 = Props("D"//CHAR(0), "T"//CHAR(0), T, "Q"//CHAR(0), Q, fluid)    !calling props deffinig the strings directlly in the arguments 


Print *, dens1


end program hello



```

**Comment by jowr** [comment]
Thanks for sharing this code! It seems like none of us is a Fortran expert... The current Fortran example was written by me to connect CoolProp to our Fortran 77 code and all I can tell is that these C-bindings do not work for that code. However, I think it is very relevant to have an example covering a recent version of Fortran although the Fortran world seems to like their "dinosaur" software...

**Comment by ibell** [comment]
I've made lots of progress with iso_c_binding.  In a few minutes Ill
push some commits explaining how to use the new code to v5, which
compiles with gcc/gfortran, and should compile with intel as well.  I
cant seem to get the older F77 code to work, perhaps @jowr and I can
have a teleconf to discuss next week.  I dont understand the point of
the shim code in the *IF.c file.  Can't we just link the DLL with the
proper naming convention (all lower case with a underscore at the
end)?  I can add F77 compatible wrapper functions where necessary to
CoolpropLIB.c/h as needed.  At the moment I cant get the F77 code to
compile...

**Comment by ibell** [comment]
Ok the changes end up with

*https://github.com/CoolProp/CoolProp/commit/032826e70f50ac4a83054710def7441ad5a39e6c
https://github.com/CoolProp/CoolProp/commit/032826e70f50ac4a83054710def7441ad5a39e6c
*

*simple example, proof of principle:
https://github.com/CoolProp/CoolProp/tree/master/wrappers/Fortran/simple_example
https://github.com/CoolProp/CoolProp/tree/master/wrappers/Fortran/simple_example
*

*Calling CoolProp v5 from FORTRAN :
https://github.com/CoolProp/CoolProp/tree/master/wrappers/Fortran/detailed_example
https://github.com/CoolProp/CoolProp/tree/master/wrappers/Fortran/detailed_example
*

_Seems to work!_

_Ian_
