### ISSUE TITLE
R113 Critical Pressure

### ISSUE THREAD

**Issue by longapalooza** [ibell/coolprop#134]
I'm a PhD student that uses REFPROP for my research. My research deals with using the fluid properties of R113.  I thought I would try out CoolProp because I like open source software. When I tried to calculate the specific enthalpy of R113 at a temperature of 300K and a quality of 0 (i.e. saturated liquid), CoolProp returns a value of -150.67 kJ/kg while under the same conditions REFPROP returns 224.37 kJ/kg. Trying to get to the root cause of the discrepancy, I checked the CoolProp fluid property page for R113 (http://coolprop.sourceforge.net/Fluids/R113.html) and noticed that the critical pressure of R113 (4.9885 MPa) is different then that listed in REFPROP (3.3922 MPa).  I checked several other sources and all of them showed the value that REFPROP has. Is this the cause for the difference between the specific enthalpy values?

**Comment by jowr** [comment]
Thank you for the comment on the critical pressure. I am sure @ibell can explain a little more about that. 
Regarding your enthalpy values, please make sure that you compare with similar reference states. Have a look at https://github.com/ibell/coolprop/issues/112 for more details.

**Comment by longapalooza** [comment]
That is what my problem is. The delta between enthalpies is same. Is there a method or function to check/change the reference state from within Mathcad and Matlab/Octave? I use both regularly and would like to have my values match that of REFPROP. I saw the set_reference_state from the link provided in the thread you referred me to but isn't that just for python?

**Comment by jowr** [comment]
Sorry, I am afraid the functionality you ask for is not part of the wrappers, yet. If you can, you are invited to participate and contribute the functions you are missing.
Have a look at https://github.com/ibell/coolprop/blob/master/wrappers/MATLAB/Props.c to get an idea of how to modify the wrapper.

**Comment by ibell** [comment]
@wlong007 Quite right about the critical pressure being wrong for R113.  I fixed it in 020e91f4e9a410d226b79a26c861d0210b54736b.  @jowr is quite right about the reference state.  The MATLAB wrapper is a disaster, but in Octave, the `set_reference_stateS` and `set_reference_stateD` functions are exposed through CoolPropDLL.h (https://github.com/ibell/coolprop/blob/master/CoolProp/CoolPropDLL.h#L90).

**Comment by longapalooza** [comment]
Thanks for all the help. I'll take a look at the Matlab wrapper if I find some time.
