### ISSUE TITLE
Crtitical pressure units

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#137]
There still is a unit conversion bug somewhere:

```
In [10]: CP.Props('R134a','pcrit')
Out[10]: 4059.28

In [11]: CP.PropsSI('R134a','pcrit')
Out[11]: 4059.28

In [12]: CP.PropsU('R134a','pcrit','SI')
Out[12]: 4059.28

In [13]: CP.Props('pcrit','T',0,'P',0,'R134a')
Out[13]: 4059.28

In [14]: CP.PropsU('pcrit','T',0,'P',0,'R134a','SI')
Out[14]: 4059280.0

In [15]: CP.PropsSI('pcrit','T',0,'P',0,'R134a')
Out[15]: 4059280.0
```

Additionally, the critical pressure returned from the Modelica wrapper is also in kPa instead of Pa.

I will try to fix it and report progress later.

**Comment by ibell** [comment]
Ugh.  A couple of things - have you played with the Catch unit testing
yet?  We should have a unit test for this in C++ level.  I wonder where the
unit conversion is not happening..  I'll take a look tonight.

**Comment by jowr** [comment]
No haven't played with the unit testing at all. Would be nice if you could have a look later. 
- I fixed things in Modelica by just calling PropsSI directly. 
- The Python issue remains: PropsU cannot handle two parameter calls properly.
- The general issue remains as well. Calling Props1 somehow leads to an unconverted output.

Would be nice to fix it soon.

**Comment by ibell** [comment]
Yes I agree.  This is a high priority bug and I will fix it tonight, add a
Catch unit test, and resolve it.  We might want to consider releasing 4.1.1
as a bugfix to resolve this issue as well...

How heavily do you think that people use PropsU?  One idea I had was to
deprecate that function in favor of PropsSI or Props (which would be either
kSI or SI depending on the unit system in use).  That would clean up the
Python wrapper quite a bit as well.  And make Python and other languages
more similar.

**Comment by jowr** [comment]
Good point. Go ahead and deprecate it, it's a mess, really. I think no one besides me is using it :-)

**Comment by ibell** [comment]
Progress.  Props and PropsSI seem to operate properly now, but PropsU still
seems to be a bit wonky.  Was a coding error on my side:

```
In [1]: import CoolProp.CoolProp as CP

In [2]: CP.Props('R134a','pcrit')
Out[2]: 4059.28

In [3]: CP.PropsSI('R134a','pcrit')
Out[3]: 4059280.0

In [4]: CP.PropsU('R134a','pcrit','SI')
Out[4]: 4059.28

In [5]: CP.Props('pcrit','T',0,'P',0,'R134a')
Out[5]: 4059.28

In [6]: CP.PropsU('pcrit','T',0,'P',0,'R134a','SI')
Out[6]: 4059280.0

In [7]: CP.PropsSI('pcrit','T',0,'P',0,'R134a')
Out[7]: 4059280.0

In [8]: CP.Props('P','T',340,'Q',0,'R134a')
Out[8]: 1971.5353359718272

In [9]: CP.PropsSI('P','T',340,'Q',0,'R134a')
Out[9]: 1971535.3359718272

In [10]: CP.Props('pcrit','T',340,'Q',0,'R134a')
Out[10]: 4059.28

In [11]: CP.PropsSI('pcrit','T',340,'Q',0,'R134a')
Out[11]: 4059280.0
```
