### ISSUE TITLE
Error while compiling in MATLAB

### ISSUE THREAD

**Issue by ghost** [ibell/coolprop#140]
Hey,

I tried to install CoolProp for using it in MATLAB, but during compiling the process crashed.
I was told to post the whole output, so here you go (sorry, but it is a lot):

MATLABBuilder_OSX

path_to_src =

../../CoolProp/

../../CoolProp/AllFluids.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/AllFluids.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____379()’:
../../CoolProp/AllFluids.cpp:401:79: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
      double pcrit_RP = PropsSI("pcrit","T",300,"D",1e-10,(char_)RPName.c_str());
                                                                               ^
../../CoolProp/AllFluids.cpp:401:79: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/AllFluids.cpp:401:79: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Brine.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/CPMath.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/CPState.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/CoolProp.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/CoolPropDLL.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/CoolPropDLL.cpp: In function ‘long int redirect_stdout(char_)’:
../../CoolProp/CoolPropDLL.cpp:15:29: warning: ignoring return value of ‘FILE_ freopen(const char_, const char_, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  freopen(file, "a+", stdout);
                             ^
../../CoolProp/CoolPropTools.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/CriticalSplineConstants.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/FluidClass.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/Helmholtz.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/HumidAirProp.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/Ice.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/IncompBase.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/IncompBase.cpp: In member function ‘double IncompressibleClass::simplePolynomial(const std::vectorstd::vector<double >&, double, double)’:
../../CoolProp/IncompBase.cpp:76:64: warning: ‘double IncompressibleClass::simplePolynomial(const std::vector<double>&, double)’ is deprecated (declared at ../../CoolProp/IncompBase.cpp:52) [-Wdeprecated-declarations]
   result += pow(x,(int)i) \* simplePolynomial(coefficients[i], T);
                                                                ^
../../CoolProp/IncompLiquid.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/IncompSolution.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/MatrixMath.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/Mixtures.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/REFPROP.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/Solvers.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/Spline.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/TTSE.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/TTSE.cpp: In member function ‘void TTSESinglePhaseTableClass::matrix_from_file(std::string, std::vectorstd::vector<double >_)’:
../../CoolProp/TTSE.cpp:491:51: warning: ignoring return value of ‘size_t fread(void_, size_t, size_t, FILE_)’, declared with attribute warn_unused_result [-Wunused-result]
    fread(&(((_A)[i])[0]), sizeof(double),Np,pFile);
                                                   ^
../../CoolProp/TTSE.cpp: In member function ‘void TTSESinglePhaseTableClass::vector_from_file(std::string, int, std::vector<double>_)’:
../../CoolProp/TTSE.cpp:513:48: warning: ignoring return value of ‘size_t fread(void_, size_t, size_t, FILE_)’, declared with attribute warn_unused_result [-Wunused-result]
   fread(&((_vec)[0]), sizeof(double), N, pFile);
                                                ^
../../CoolProp/Tests.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

../../CoolProp/Tests.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____11()’:
../../CoolProp/Tests.cpp:15:40: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    set_reference_stateS("Propane","IIR");
                                        ^
../../CoolProp/Tests.cpp:15:40: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:16:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    double h_EOS = PropsSI("H","T",273.15,"Q",0,"Propane");
                                                         ^
../../CoolProp/Tests.cpp:16:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:16:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:16:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:17:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    double s_EOS = PropsSI("S","T",273.15,"Q",0,"Propane");
                                                         ^
../../CoolProp/Tests.cpp:17:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:17:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:17:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:26:40: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    set_reference_stateS("Propane","NBP");
                                        ^
../../CoolProp/Tests.cpp:26:40: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:27:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    double h_EOS = PropsSI("H","P",101325,"Q",0,"Propane");
                                                         ^
../../CoolProp/Tests.cpp:27:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:27:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:27:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:28:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    double s_EOS = PropsSI("S","P",101325,"Q",0,"Propane");
                                                         ^
../../CoolProp/Tests.cpp:28:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:28:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:28:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:37:43: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    set_reference_stateS("Propane","ASHRAE");
                                           ^
../../CoolProp/Tests.cpp:37:43: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:38:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    double h_EOS = PropsSI("H","T",233.15,"Q",0,"Propane");
                                                         ^
../../CoolProp/Tests.cpp:38:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:38:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:38:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:39:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    double s_EOS = PropsSI("S","T",233.15,"Q",0,"Propane");
                                                         ^
../../CoolProp/Tests.cpp:39:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:39:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:39:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____48()’:
../../CoolProp/Tests.cpp:56:49: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
     double p_Props1SI = Props1SI("R134a","pcrit");
                                                 ^
../../CoolProp/Tests.cpp:56:49: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:57:45: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
     double p_Props1 = Props1("R134a","pcrit")_1000;
                                             ^
../../CoolProp/Tests.cpp:57:45: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:58:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
     double p_Props = Props("pcrit",'T',300,'Q',0,"R134a")_1000;
                                                         ^
../../CoolProp/Tests.cpp:58:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:59:61: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
     double p_PropsSI = PropsSI("pcrit","T",300,"Q",0,"R134a");
                                                             ^
../../CoolProp/Tests.cpp:59:61: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:59:61: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:59:61: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:71:47: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
     double p_Props1SI = Props1("R134a","pcrit");
                                               ^
../../CoolProp/Tests.cpp:71:47: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:72:45: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
     double p_Props1 = Props1("R134a","pcrit");
                                             ^
../../CoolProp/Tests.cpp:72:45: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:73:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
     double p_Props = Props("pcrit",'T',300,'Q',0,"R134a");
                                                         ^
../../CoolProp/Tests.cpp:73:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:74:61: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
     double p_PropsSI = PropsSI("pcrit","T",300,"Q",0,"R134a");
                                                             ^
../../CoolProp/Tests.cpp:74:61: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:74:61: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp:74:61: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp: In function ‘int run_fast_tests()’:
../../CoolProp/Tests.cpp:87:49: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
   char_ const argv[] = {"/a/dummy/path","[fast]"};
                                                 ^
../../CoolProp/Tests.cpp:87:49: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../CoolProp/Tests.cpp: In function ‘int run_not_slow_tests()’:
../../CoolProp/Tests.cpp:99:50: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
   char\* const argv[] = {"/a/dummy/path","~[slow]"};
                                                  ^
../../CoolProp/Tests.cpp:99:50: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
../../CoolProp/Units.cpp

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

---

  Warning: Neither -compatibleArrayDims nor -largeArrayDims is selected. 
           Using -compatibleArrayDims. In the future, MATLAB will require
           the use of -largeArrayDims and remove the -compatibleArrayDims
           option. For more information, see:
           http://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html

---

-> mexopts.sh sourced from directory (DIR = $PREF_DIR)
##    FILE = /home/moe/.matlab/R2013b/mexopts.sh

->    MATLAB                = /usr/local/MATLAB/R2013b
->    CC                    = gcc
->    CC flags:
         CFLAGS             = -ansi -D_GNU_SOURCE  -fexceptions -fPIC -fno-omit-frame-pointer -pthread
         CDEBUGFLAGS        = -g
         COPTIMFLAGS        = -O -DNDEBUG
         CLIBS              = -Wl,-rpath-link,/usr/local/MATLAB/R2013b/bin/glnxa64 -L/usr/local/MATLAB/R2013b/bin/glnxa64 -lmx -lmex -lmat -lm -lstdc++
         arguments          =  -DMX_COMPAT_32
->    CXX                   = g++
->    CXX flags:
         CXXFLAGS           = -ansi -D_GNU_SOURCE -fPIC -fno-omit-frame-pointer -pthread
         CXXDEBUGFLAGS      = -g
         CXXOPTIMFLAGS      = -O -DNDEBUG
         CXXLIBS            = -Wl,-rpath-link,/usr/local/MATLAB/R2013b/bin/glnxa64 -L/usr/local/MATLAB/R2013b/bin/glnxa64 -lmx -lmex -lmat -lm
         arguments          =  -DMX_COMPAT_32
->    FC                    = gfortran
->    FC flags:
         FFLAGS             = -fexceptions -fbackslash -fPIC -fno-omit-frame-pointer
         FDEBUGFLAGS        = -g
         FOPTIMFLAGS        = -O
         FLIBS              = -Wl,-rpath-link,/usr/local/MATLAB/R2013b/bin/glnxa64 -L/usr/local/MATLAB/R2013b/bin/glnxa64 -lmx -lmex -lmat -lm
         arguments          =  -DMX_COMPAT_32
->    LD                    = gcc
->    Link flags:
         LDFLAGS            = -pthread -shared -Wl,--version-script,/usr/local/MATLAB/R2013b/extern/lib/glnxa64/mexFunction.map -Wl,--no-undefined
         LDDEBUGFLAGS       = -g
         LDOPTIMFLAGS       = -O
         LDEXTENSION        = .mexa64
         arguments          =  -ldl
->    LDCXX                 = 
->    Link flags:
         LDCXXFLAGS         = 
         LDCXXDEBUGFLAGS    = 
         LDCXXOPTIMFLAGS    = 
         LDCXXEXTENSION     = 
##          arguments          =  -ldl

Warning: You are using gcc version "4.8.1".  The version
         currently supported with MEX is "4.7.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

-> gcc -c  -I../../CoolProp/ -I/usr/local/MATLAB/R2013b/extern/include -I/usr/local/MATLAB/R2013b/simulink/include -DMATLAB_MEX_FILE -ansi -D_GNU_SOURCE  -fexceptions -fPIC -fno-omit-frame-pointer -pthread  -DMX_COMPAT_32 -O -DNDEBUG  "Props.c"

In file included from Props.c:11:0:
../../CoolProp/GlobalConstants.h:5:1: error: expected identifier or ‘(’ before ‘/’ token
 // --------------------------------------------------
 ^
../../CoolProp/GlobalConstants.h:29:1: error: expected identifier or ‘(’ before ‘/’ token
 // These are constants for the phases of the fluid
 ^
../../CoolProp/GlobalConstants.h:32:1: error: expected identifier or ‘(’ before ‘/’ token
 // These are constants for the units
 ^
../../CoolProp/GlobalConstants.h:35:1: error: expected identifier or ‘(’ before ‘/’ token
 // These are constants for the unit systems (currently only SI and KSI are supported)
 ^
../../CoolProp/GlobalConstants.h:38:1: error: expected identifier or ‘(’ before ‘/’ token
 // These are unit types for the fluid
 ^
Props.c: In function ‘mexFunction’:
Props.c:55:9: error: expected expression before ‘/’ token
         // Try to shortcut to get the strings for the fluid
         ^
Props.c:152:38: error: ‘UNIT_SYSTEM_SI’ undeclared (first use in this function)
             set_standard_unit_system(UNIT_SYSTEM_SI);
                                      ^
Props.c:152:38: note: each undeclared identifier is reported only once for each function it appears in
Props.c:158:38: error: ‘UNIT_SYSTEM_KSI’ undeclared (first use in this function)
             set_standard_unit_system(UNIT_SYSTEM_KSI);
                                      ^

```
mex: compile of ' "Props.c"' failed.
```

Unable to complete successfully.

Error in MATLABBuilder_OSX (line 34)
eval(['mex -v ', include_string,' Props.c ', o_files])

Thanks for your help,
Moritz

**Comment by ibell** [comment]
Ah, a couple of problems I can see:
1. You have too new a compiler, it wants 4.7.x, you have 4.8.1.
2. gcc is being pedantic about the style of comments.  I'll fix that.

The rest are harmless warnings.

**Comment by ibell** [comment]
Hopefully fixed in e77eae6f90dcfae6e93b70c78ecec276bcc16a76 please let us know if this works for you now.
