### ISSUE TITLE
MATLAB density calculation pressure set to 0

### ISSUE THREAD

**Issue by ghost** [ibell/coolprop#145]
Hey,

I wanted to let you know if pressure set to zero (this happens e.g. when differential equation is initialized), density cannot be calculated.
MATLAB is busy but does not answer anymore. It somehow sticks.

Props('D', 'H', 100, 'P', 0, 'Water')

Otherwise it works fine; also when enthalpy is set to zero.

**Comment by ibell** [comment]
Can you set it to 1e-10 in your code?  It's weird that a zero pressure causes a hang.  Thanks for the bug report.  I'll see what is going on.

**Comment by ghost** [comment]
Then it "works":

Props('D', 'H', 100, 'P', 1E-10, 'Water')
Error using Props
CoolProp Error: CoolProp error: Your saturation pressure [0.000000 Pa] is out of range
[611.654771 Pa, 22064000.000000 Pa]

**Comment by ibell** [comment]
Short answer, don't initialize in that region.  Its solid there.  You can use zero pressure inputs now in the superheated vapor region.
