### ISSUE TITLE
Cool prop

### ISSUE THREAD

**Issue by ashuraj25** [ibell/coolprop#155]
How to find the codes for all the engineering thermodynamic parameters?
Like ones I know are 
O for calorific value at constant volume etc.
What are the ones for adiabatic index and where to find complete list?

**Comment by jowr** [comment]
I hope this is what your are looking for: http://coolprop.sourceforge.net/contents.html

**Comment by ibell** [comment]
I think it is more likely to be this one :
http://coolprop.sourceforge.net/apidoc/CoolProp.html#CoolProp.CoolProp.DerivTerms

Acutally @jowr, it would be great if we could do some more documentation on
the derivatives.  And perhaps do a bit of cleanup on the naming conventions
we use as well.

Ian

**Comment by jowr** [comment]
Yes, let's put it on the list for next week.

**Comment by ashuraj25** [comment]
@jowr @ibell I have lokked at both the pages but i still couldnt find some of the thermodynamic properties there. like adiabatic index symbol. Is there any page with complete lists that is bit easy to comprehend?

**Comment by ibell** [comment]
We don't directly have a symbol for adiabatic index, but that's simple
enough already since its just cp/cv.  Some of the other derivatives could
be exposed without too much trouble.  What else would you like to have?

**Comment by ashuraj25** [comment]
@ibell Thanks sir. I had already implemented it by cp/cv .I just wanted  to know if there were direct symbols for it that i have missed out. Thanks again for the help

**Comment by ibell** [comment]
Any other derivatives that you want access to?

**Comment by ashuraj25** [comment]
@ibell Not now sir. Thanks
