### ISSUE TITLE
CoolProp Humid Air

### ISSUE THREAD

**Issue by lindsayldy** [ibell/coolprop#156]
When calculate the humid air under -8C  with dry-bulb, wet-bulb and pressure, Coolprop can't run out a result. P.S., it's for Excel

**Comment by ibell** [comment]
Can you give me minimal working example for a function call that fails?

Also, what language, OS, 32-bit or 64-bit? I'll take a look.

**Comment by lindsayldy** [comment]
Hi, Ian

I am working on the 64-bit English version.

When I tried to calculate the following, it fails, no matter what the wet-bulb temperature is
=HAPROPS("H","T",265,"B",264,"P",101.3)

But when I raised the dry-bulb temperature to 266, it works

Thank you !

Danyang Li
Thar Geothermal / Thar Energy
150 Gamma Drive
Pittsburgh, PA 15238
P  412-378-1662

**Comment by ibell** [comment]
Sorry what programming language ? Excel, MATLAB, etc.?

**Comment by lindsayldy** [comment]
Excel

Danyang Li
Thar Geothermal / Thar Energy
150 Gamma Drive
Pittsburgh, PA 15238
P  412-378-1662

**Comment by ibell** [comment]
Ok, I fixed this bug.  I put interim versions of the DLLs in http://sourceforge.net/projects/coolprop/files/CoolProp/Nightly/2014.02.26/

**Comment by lindsayldy** [comment]
Thanks!

Danyang Li
Thar Geothermal / Thar Energy
150 Gamma Drive
Pittsburgh, PA 15238
P  412-378-1662
