### ISSUE TITLE
Still unit problems with TTSE

### ISSUE THREAD

**Issue by kaern** [ibell/coolprop#158]
Eventhough Jorrit fixed the unit error in the TTSE for thermal conductivity. There are still problems with beta and speed of sound.. see comparison w/o TTSE enabled..

![untitled](https://f.cloud.github.com/assets/2339689/2255406/50de7ef8-9df4-11e3-876a-b0895b8bdf34.jpg)

**Comment by ibell** [comment]
which is which?

**Comment by jowr** [comment]
Did you delete and regenerate the table data? There was an error with the stored data...

**Comment by ibell** [comment]
I bumped the rev, so it should be forced to build the new tables again
theoretically.

**Comment by kaern** [comment]
TTSE (red) gives the unrealistic high speed of sound (left) for water at p = 80 bar and T=500 K as I remember. beta on the right.. Jorrit is working on this issue..
