### ISSUE TITLE
inconsistency on HAProps values

### ISSUE THREAD

**Issue by thermoengineer** [ibell/coolprop#161]
Hello
We have realised that on the coolprop HAPROPS returns stranger values. Please see the examples below. You can understand what I try to mention. For example T values are wavying.

 var 1 = CoolProp.HAProps("T", "H", 165, "P", atmosferikBasinc, "R", 1)-273.15;=> 160.38580260355536
var 2 = CoolProp.HAProps("T", "H", 164, "P", atmosferikBasinc, "R", 1) - 273.15; => 39.67140102354756
var 3 = CoolProp.HAProps("T", "H", 163, "P", atmosferikBasinc, "R", 1) - 273.15; =>  161.60251723235842
var 4 = CoolProp.HAProps("T", "H", 162, "P", atmosferikBasinc, "R", 1) - 273.15; =>  160.61023454227609
var 5 = CoolProp.HAProps("T", "H", 161, "P", atmosferikBasinc, "R", 1) - 273.15; =>  159.61795185219387
var 6 = CoolProp.HAProps("T", "H", 160, "P", atmosferikBasinc, "R", 1) - 273.15; =>  158.62566916211159
var 7 = CoolProp.HAProps("T", "H", 159, "P", atmosferikBasinc, "R", 1) - 273.15; =>  157.63338647202931
var 8 = CoolProp.HAProps("T", "H", 158, "P", atmosferikBasinc, "R", 1) - 273.15; =>  38.930580020934372
var 9 = CoolProp.HAProps("T", "H", 157, "P", atmosferikBasinc, "R", 1) - 273.15; =>  170.48305993283554
var 10 = CoolProp.HAProps("T", "H", 156, "P", atmosferikBasinc, "R", 1) - 273.15; =>  38.677631318402689
var 11 = CoolProp.HAProps("T", "H", 155, "P", atmosferikBasinc, "R", 1) - 273.15; =>  38.549992193390551
var 12 = CoolProp.HAProps("T", "H", 154, "P", atmosferikBasinc, "R", 1) - 273.15; => 38.421564758075192
var 13 = CoolProp.HAProps("T", "H", 153, "P", atmosferikBasinc, "R", 1) - 273.15; => 38.292339986157572
var 14 = CoolProp.HAProps("T", "H", 152, "P", atmosferikBasinc, "R", 1) - 273.15; =>  38.1623087177706
var 15 = CoolProp.HAProps("T", "H", 151, "P", atmosferikBasinc, "R", 1) - 273.15; =>  38.031461563301036
var 16 = CoolProp.HAProps("T", "H", 150, "P", atmosferikBasinc, "R", 1) - 273.15; =>  37.899789079581296
var 17 = CoolProp.HAProps("T", "H", 149, "P", atmosferikBasinc, "R", 1) - 273.15; =>  37.767281600742365
var 18 = CoolProp.HAProps("T", "H", 148, "P", atmosferikBasinc, "R", 1) - 273.15; =>  37.633929305090078
var 19 = CoolProp.HAProps("T", "H", 147, "P", atmosferikBasinc, "R", 1) - 273.15; =>  37.499722203485192
var 20 = CoolProp.HAProps("T", "H", 146, "P", atmosferikBasinc, "R", 1) - 273.15; =>  37.364650082227
Best regards,
Hasan

**Comment by ibell** [comment]
Bug fixed.  Output from 

```
for (double h = 165; h >= 146; h -= 1)
{
    std::cout << h << ": " << HAProps("T", "H", h, "P", 101.325, "R", 1)-273.15 << std::endl;
}
```

is

```
165: 39.7963
164: 39.6754
163: 39.5538
162: 39.4314
161: 39.3083
160: 39.1845
159: 39.0599
158: 38.9345
157: 38.8084
156: 38.6816
155: 38.5539
154: 38.4255
153: 38.2963
152: 38.1662
151: 38.0354
150: 37.9037
149: 37.7712
148: 37.6378
147: 37.5036
146: 37.3685
```

**Comment by ibell** [comment]
Download at http://sourceforge.net/projects/coolprop/files/CoolProp/Nightly/2014.02.26/

**Comment by thermoengineer** [comment]
Dear Ian,
Thank you for fixing the bug. It works well again.
BR
Hasan

**Comment by ibell** [comment]
Good to hear!

Ian
