### ISSUE TITLE
SES 36 - Helmholtz energy functions 

### ISSUE THREAD

**Issue by JDPS** [ibell/coolprop#163]
First, my sincere congratulations and acknowledgments for coolprop database.
I found this database since I need to simulate a system running on SES36.
Unfortunately I think that will be impossible, since I didn’t find Helmholtz energy functions.
Can you please confirm if I am correct?
Thank you very much.

**Comment by jowr** [comment]
Hello, I am not sure what you are referring to, but the inputs `phir` and `phi0` might be what you need. Please have a look at http://coolprop.sourceforge.net/apidoc/CoolProp.html#CoolProp.CoolProp.DerivTerms , in principle, the inputs to `DerivTerms` also work with the `Props` function, which is accessible from most wrappers. Please let us know which software you are using, that makes it much easier to help.

**Comment by jowr** [comment]
You could also use the standard relations, please see http://en.wikipedia.org/wiki/Helmholtz_free_energy 

`a = u - Ts` with `u = h - p/rho` ...

**Comment by ibell** [comment]
@jowr is right on the money.  What exactly is the issue that you are having?

**Comment by JDPS** [comment]
Thanks for the quick answer.
I am not an expert on programming. 
I am trying to implement SES36 COOLPROP database in EBSILON software.
EBSILON has an editable C-language source code. This source was used in the past for calling REFPROP dll library. 
On this source I have to supply the functions that will be called by Ebsilon Kernel.
The functions called by EBSILON are:

USER2PHASEDLL_API double H_PT( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double S_PT( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double T_PH( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double T_PS( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double TSAT_P( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double PSAT_T( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double H_PS( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double S_PH( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double X_PH( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double H1_P( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double H2_P( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double CP_PH( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double V_PT( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double V_PH( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double P_H1( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double P_S2( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double X_PS( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double H_PX( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double ETA_PH( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double ALAM_PH( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double H_TS( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double T_HS( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double P_SH( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double S_TH( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double S_TX( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );
USER2PHASEDLL_API double PHASE_PH( int nMatId, double dblVar1, double dblVar2, int nData, int\* pnError );

Looking at SES36 source code I only find some functions for calculating saturation properties.

**Comment by ibell** [comment]
You don't want to call SES36 fluid directly, you want to call the PropsSI()
function you can find in CoolPropDLL.h .  That way you could easily call
another fluid by just changing the fluid name.  You need the whole package
in able to enable all the inputs you want.  The first thing that you should
make sure you can get working is to call the K2F function which converts a
temperature in Kelvin to Fahrenheit.  It can be found in CoolPropDLL.h  If
you can get that working, everything else is (relatively) easy.

So you need to implement ALL of those functions?  Certainly possible, but
its going to be quite some work for you.

**Comment by JDPS** [comment]
I was trying to simplify, since I only need SES36 data.
Unfortunately EBSILON professional requires the implementation of all functions.
Thank you for the information, it was very helpful. At least I know that it can be done.
I will try to implement the functions, but first I will do your suggestion of stating with temperature conversion.

**Comment by JDPS** [comment]
I didn´t sucess on the implementation of this functions on EBSILON. 
I am doing this in my spare time, so it can take a while until is finish.
Yet I think that you can close this issue.
