### ISSUE TITLE
BibTeX citation problem

### ISSUE THREAD

**Issue by ghobold** [ibell/coolprop#165]
Just so to let you know that BibTeX will fail when compiling the citation suggested in http://coolprop.sourceforge.net/citation.html

The part `journal = {Industrial & Engineering Chemistry Research},` should be `journal = {Industrial \& Engineering Chemistry Research},` 

If the backslash is not included, the BibTeX interpreter will think `&` is an alignment character rather than simply a character.

**Comment by ibell** [comment]
Thanks I'll fix it this evening.
