### ISSUE TITLE
Include CoolProp in ExternalMedia

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#166]
- [x] Make ExternalMedia compile on Linux
- [x] Add CoolProp to the latest version of ExternalMedia for Modelica 
- [x] Commit changes to the Modelica.org SVN server
- [x] Alter the Modelica code to handle extended features introduced by CoolProp2Modelica - like f(h,s), EXTTP, TTSE and index reduction annotations

**Comment by jowr** [comment]
I added a new branch for the SVN externals on the Modelica.org servers. Could anyone with write-access to these servers please update the URL for the external dependency on CoolProp? The new branch is called `ExternalMedia` and can be found via SVN at `https://github.com/ibell/coolprop/branches/ExternalMedia/`

**Comment by squoilin** [comment]
About the extended features, do you believe they should be integrated directly into ExternalMedia? ExternalMedia is primarily designed for fluidprop, which does not handle incompressibles or (h,s). 

Another solution could be to transform CoolProp2Modelica into a new library that extends ExternalMedia and adds the other features. In that case, it could be directly integrated into ThermoCycle. 

What do you think?

**Comment by jowr** [comment]
For now, the plan is to have both CoolProp2Modelica as a standalone library and the integration into ExternalMedia. The implementation of the changes we made will end up in the CoolPropMedium file and do not interfere with the FluidProp side of things. 

I am not sure about a direct integration with ThermoCycle, but that is also an option.

**Comment by jowr** [comment]
Almost done, new features not included in ExternalMedia yet.
