### ISSUE TITLE
CoolProp and EES compatibility issues

### ISSUE THREAD

**Issue by visekemi** [ibell/coolprop#173]
I get errors when I open and then run the example in the folder C:\EES32\Userlib\CoolProp_EES, after install of CoolProp. I am running it on Windows 7 with EES versions: Commercial V9.409 (05/21/2013) and Commercial V9.613 (02/22/2014), with both I get the same issues.

**Comment by ibell** [comment]
I think you aren't using 4.1.2.  I installed 4.1.2 on my own machine and
the example runs.  So my feeling is that you have an older version
installed.  What version did you install?

**Comment by visekemi** [comment]
You mean version of CoolProp? I downloaded from the following link:
http://sourceforge.net/projects/coolprop/files/CoolProp/4.1.2/EES/
I run the CoolProp_EES_installer in the folder: C:\EES32\Userlib.
The CoolProp_EES is in that folder.

**Comment by visekemi** [comment]
I found the issue: first I downloaded all the folder with all interfaces from the link: Download CoolProp-4.1.2-windows_superpack.zip (43.7 MB) from the page which you sent me. I uninstalled it and downloaded only CoolProp_EES_installer.msi from the same page, installed and works. 
So, I think there is something wrong with that folder, where all the interfaces for all languages are.

**Comment by ibell** [comment]
That is odd as the updated installer for EES should have been included in
the superpack. Anyway, glad to hear it is working now.

Closing this issue.
