### ISSUE TITLE
Simple plotting of cycles

### ISSUE THREAD

**Issue by spinnau** [ibell/coolprop#174]
I want to discuss possibilities to add easy plotting of processes and cycles. I know about the _SimpleCycles_ module, but a more general solution would be great. By now for each process the data has to be created and plotted manually, like

``` python
T = xrange(T_1, T_2)
s = [Props('S', 'T', T_i, 'P', p_1, 'Water') for T_i in T]
plt.plot(T, s)
```

This means a lot of plotting code for cycles. Especially in IPython notebooks a cleaner solution would be nice. Thus, I am actually using the method proposed below, that takes a list of _State_ objects. This reduces the plotting part to almost two lines of code (as the _State_ objects were already existing for calculation of the cycle):
- check for constant properties between the given _State_ objects and connect them with isolines or straight lines
- the _draw_process_ method could be included in _PropsPlot_ class
- maybe the _draw_isolines_ or _get_isolines_ methods could be used internally, if they get new min/max keyword arguments (defaulting to _None_ for API compatibility)

``` python
from CoolProp.CoolProp import Props
from CoolProp.State import State
from CoolProp.Plots import PropsPlot
import numpy as np


def draw_process(props_plot, states, color='r', ls='-'):
    """ Draw process

    Parameters
    ----------

      props_plot          CoolProp.Plots.PropsPlot instance
      states (list)       List of CoolProp.State.State objects

    """   

    n = 100
    y, x = props_plot.graph_type.lower().replace('t', 'T')

    for i, state in enumerate(states):
        if state.Fluid != props_plot.fluid_ref:
            raise ValueError('All State objects should use the same fluid.')

        if i == 0: continue

        S_2 = states[i]
        S_1 = states[i-1]    

        # isobaric process
        if S_1.p == S_2.p:
            x_val = np.linspace(getattr(S_1, x), getattr(S_2, x), n)
            y_val = [Props(y.upper(), 'P', S_1.p, x.upper(), val, fluid) for val in x_val]
        # add more processes with constant values here ... 
        else:
            x_val = [getattr(S_1, x), getattr(S_2, x)]
            y_val = [getattr(S_1, y), getattr(S_2, y)]            

        props_plot.axis.plot(x_val, y_val, color=color, ls=ls, zorder=10)


# example rankine cycle
fluid = 'Water'
p_min = 20
p_max = 15e3
T_max = 550 + 273.15

S_1 = State(fluid, dict(P=p_min, Q=0))     # condenser outlet
S_2 = State(fluid, dict(P=p_max, S=S_1.s)) # isentropic compression
S_3 = State(fluid, dict(P=p_max, T=T_max)) # isobaric heating
S_4 = State(fluid, dict(P=p_min, S=S_3.s)) # isentropic expansion

Ts = PropsPlot(fluid, 'Ts')
draw_process(Ts, [S_1, S_2, S_3, S_4, S_1])
Ts.show()
```

What do you think about it?

(This issue should be labeled as enhancement)

**Comment by ibell** [comment]
This is a great idea!  We also need someone to come in and convert all the plotting routines to always use the PropsSI function.  Want to take a shot at that too?

**Comment by spinnau** [comment]
Yes, I can do the conversion to PropsSI function. But what to do with the axis units and labels? Should the plots also show SI units (with scientific notation to make pressure and energy values more readable)?

**Comment by ibell** [comment]
I think its best if we still show the units in kSI units (kPa, kJ/kg,
etc.), but the internal calculations should use the PropsSI function and do
necessary conversions

**Comment by jowr** [comment]
Hi and thanks for the help. In my opinion, we should make plots in the same units as before. Using SI units internally will make the code more future-proof...

**Comment by spinnau** [comment]
Ok, sounds like a good solution...

**Comment by spinnau** [comment]
@ibell While working on this, I found out, that your commit 9e832e76ff94b1d963e0049672348cee3137456c breaks the existing code for plotting isolines. In `IsoLines.__set_axis_limits` method T could be input and output for Ts-diagrams. Do you think this should be fixed in plotting routines?

**Comment by ibell** [comment]
Yes!  I was going back and forth about throwing an error when the output is
the same as the input.  In the end, I decided that the use case was useful
enough to make the change.  But it would be good if we could  fix the
plotting routines.  To be honest I don't use the plotting routines that
much, but if you could make a PR with the necessary fixes, that would be
great!!

**Comment by spinnau** [comment]
The issue described above is fixed in the pull request for plotting of cycles...
