### ISSUE TITLE
Create mixtures with CoolProp

### ISSUE THREAD

**Issue by visekemi** [ibell/coolprop#175]
How do I create mixtures with CoolProp? I followed similar command as for FluiProp:
D=CoolProp('D','T',300,'P',205,'R32:50/R125:50')
and doesn't work.
Please help!

**Comment by ibell** [comment]
Unfortunately CoolProp does not support mixtures for the moment though it will extremely soon. If you have REFPROP, you can use mixtures like in : http://coolprop.sourceforge.net/FluidInformation.html#refprop-fluids-and-mixtures

**Comment by visekemi** [comment]
I have refprop 9 and refprop 8. Looks like only refprop 8 works. However, how can I create a mixture using variables?
Dens = CoolProp('D','Q',1,'P',101.325,'REFPROP-MIX:R32[x]&R125[y]')
x=0.3
y=0.7

**Comment by ibell** [comment]
You need to turn the variables into a string.  Not sure how to do that in
EES.  REFPROP 9 should definitely work.  I use 9.1, and I know a couple of
other people do as well.  Where is your REFPROP installed?

**Comment by visekemi** [comment]
It is saved on C:\Program Files\REFPROP
Thanks for help

**Comment by ibell** [comment]
Perhaps the best is to add the c:\Program Files\REFPROP to the system
path.  See also
http://geekswithblogs.net/renso/archive/2009/10/21/how-to-set-the-windows-path-in-windows-7.aspx

**Comment by visekemi** [comment]
Thanks...discussions helped a lot, I made it finally :-)
Here is a EES string to create mixture of refrigerants:
a$='REFPROP-MIX:'||'R32'||'['||yy$||']'||and$||'R125'||'['||xx$||']'

**Comment by ibell** [comment]
Great I added that information about the EES strings to the docs.
