### ISSUE TITLE
Python error: basic_string::resize (when using TTSE)

### ISSUE THREAD

**Issue by kaern** [ibell/coolprop#177]
I got this strange error when enabling TTSE. There is no error when without TTSE..

Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.

> > > import CoolProp
> > > import CoolProp.CoolProp as CP
> > > CP.enable_TTSE_LUT('Propane')
> > > True
> > > p = CP.Props('P', 'T', 300, 'D', 1, 'Propane')
> > > 0.15 to build both two phase tables
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "CoolProp.pyx", line 217, in CoolProp.CoolProp.Props (build\temp.win32-2.
> > > 7\Release\pyrex\CoolProp\CoolProp.cpp:21297)
> > >   File "CoolProp.pyx", line 327, in CoolProp.CoolProp.Props (build\temp.win32-2.
> > > 7\Release\pyrex\CoolProp\CoolProp.cpp:19808)
> > > ValueError: CoolProp error: basic_string::resize :: inputs were:"P",'T',3.000000
> > > 0000000000e+02,'D',1.0000000000000000e+00,"Propane"

**Comment by jowr** [comment]
Interesting, it works out of the box for me...

**Comment by ibell** [comment]
Are both/either of you building from source versus using the installers?

**Comment by jowr** [comment]
I compile from source, as you might have guessed.

**Comment by ibell** [comment]
@kaern How did you install coolprop?

**Comment by kaern** [comment]
sorry for waiting.. I run the setup.py install file. 

It is strange that the error only happens the first time, I do a call, the second time it works..
![untitled](https://f.cloud.github.com/assets/2339689/2407146/043ff606-aa85-11e3-9cbb-eee75902cb67.png)

It means trouble when running some fancy scripts..

**Comment by ibell** [comment]
Yes this is weird - I've not seen this before.  Are you building from
sources from git?

**Comment by kaern** [comment]
yes I am. I should test it on another machine before proceeding though..
I do that and get back..

**Comment by ibell** [comment]
For me:
C:\Users\Belli\Documents\Code\CoolProp\wrappers\Python>ipython
Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 2.0.0-dev -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import CoolProp.CoolProp as CP

In [2]: CP.enable_TTSE_LUT('propane')
Out[2]: True

In [3]: CP.PropsSI('D','P',10e5,'T',300,'propane')
0.148 to build both two phase tables
Out[3]: 489.45493493146154

In [4]: CP.PropsSI('D','P',10e5,'T',300,'propane')
Out[4]: 489.45493493146154

Interestingly our values are slightly different, but I don't get an error...

Ian

**Comment by kaern** [comment]
Hi Ian,

It works if I use the installer file. Then we get the same results. However, I cannot get it working when I compile myself. It must be an issue on my computer, you can close the issue..

Martin

Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 0.13.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import CoolProp.CoolProp as CP

In [2]: CP.enable_TTSE_LUT('propane')
Out[2]: True

In [3]: CP.PropsSI('D','P',10e5,'T',300,'propane')
0.05 to build both two phase tables
Out[3]: 489.4549349314619

**Comment by ibell** [comment]
It's a weird bug but lets close it for now.  If it pops up again, please reopen this issue.
