### ISSUE TITLE
Question: Reversibility of Props()

### ISSUE THREAD

**Issue by mamue** [ibell/coolprop#178]
This is an example code in python.

I am doing this:

``` python
import CoolProp
import CoolProp.CoolProp as CP

psat = CP.Props('P','T',273,'Q',0.5, 'R744')
tsat = CP.Props('T','P',psat,'Q',0.5, 'R744')
```

psat now is 3471.3228415670787 and tsat now is 272.9999999999997

Next I am doing this

``` python
qsat = CP.Props('Q','P',psat,'T',tsat, 'R744')
```

and I get:
-1.0

Because all items are identical, I expect to get qsat = 0.5 as this is the Q-value with which I calculated psat and tsat.

What is going wrong here? Is the computational accuracy to blame?

**Comment by ibell** [comment]
You cannot use temperature and pressure as inputs in the two-phase region
since they do not uniquely define the state.  Are you using an older
version of CoolProp?  These inputs should cause an error...

**Comment by mamue** [comment]
Sorry, apparently you're right.
Would you please delete/ close this issue?

The version of coolprop I'm using is:

``` python
CoolProp.__version__
'4.1.2'
CoolProp.__gitrevision__
'6396c4e238c39f1d449e1d36d8ed18ae89212b84'
```

Sorry for bothering and thank you for replying!

**Comment by ibell** [comment]
Interesting.  This is actually sort of a bug since it didn't give an
error.  But I think the fact that it didn't give an error is due to the
numerical precision since your inputs are just outside the twophase region
now.
