### ISSUE TITLE
v5 tasks

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#179]
- [x] Extract EOS terms from v4 code to JSON
  -  How do we switch between EOS?
- [ ] Extract Transport properties from v4 to JSON
  - There are a lot of different terms we need to implement.  This is going to be painful.
- [x] Extract ancillary curves from v4 (or refit) to JSON
  - Refitting might be the best since we have very good ancillary fitter code now
- [x] Build FluidsContainer
  - Container class for the constants that can be used for the fluids.  It has a factory function that can be used to return a Fluid instance.

**Comment by ibell** [comment]
Here's a skeleton of a JSON file:

```
[
  {
    "NAME" : "Water",
    "ALIASES" : ["R718","H2O"],
    "CRIT": {"rho" : 322,
             "rho_units" : "kg/m^3",
             "p" : 22064,
             "p_units" : "kPa",
             "T" : 647.096,
             "T_units" : "K"
             },
    "EOS": [
              {
                "key" : "Wagner-JPCRD-2002",
                "bibtexkey" : "Wagner-JPCRD-2002",
                "alphar" : [
                              {
                               "type" : "alphar_power",
                               "n": [1.1, 3.3, 3.3, 5.7],
                               "d": [1.1, 3.3, 3.3, 5.7],
                               "t": [1.1, 3.3, 3.3, 5.7],
                               "l": [1.1, 3.3, 3.3, 5.7]
                              }
                           ],
                "alpha0" : [
                           ],
                "reduce": {
                            "equal_to" : "crit"
                          },
                "limits": {}
              }
            ],
    "VISCOSITY" : "Huber-JPCRD-2009",
    "ECS_LENNARD_JONES" : "Poling-BOOK-2001",
    "SURFACE_TENSION" : { "bibtexkey": "Mulero-JPCRD-2012",
                          "a" : [1,2,3],
                          "n" : [3,4,5]
                        }
    }
]
```

**Comment by ibell** [comment]
## Core Thermodynamic Routines
- [x] Determine if pseudo-pure
- [x] Triple point temperature
- [x] PQ for mixtures using SS
- [x] TQ for mixtures using SS
- [ ] Phase envelope construction
- [ ] PQ for mixtures using NR
- [ ] TQ for mixtures using NR
- [ ] PQ for pure & pseudo-pure
- [x] TQ for pseudo-pure
- [ ] Melting curves
- [ ] TP for pure/pseudo-pure/mixtures
- [ ] DT for pseudo-pure / mixtures

## Generalized flash routines
- [ ] TH, TS, TU
- [ ] PD, PH, PS, PU
- [ ] DH, DS, DE
- [ ] Nasty ones: HS, US

# Transport properties

**Comment by jowr** [comment]
Is this done?

**Comment by ibell** [comment]
Yes, I think so.
