### ISSUE TITLE
DerivTerms() in MATLAB

### ISSUE THREAD

**Issue by ghobold** [ibell/coolprop#180]
Is the function DerivTerms() implemented in the MATLAB wrapper? It does not seem to be. In my program I have to use the coefficient of thermal expansion and I would need a few derivatives to make that work, as it cannot be written in terms of outputs provided by the Props() function.

**Comment by ibell** [comment]
It sort of is (or rather will be in 4.2).  You should be able to pass the
same output parameters to Props as you would have passed to DerivTerms, and
it will return the deriv term in question.  If I remember correctly, you
will always get back SI units, so you are better off just always using SI
units everywhere.

**Comment by ghobold** [comment]
Yes, that works, and you do get back in SI. Thanks!

**Comment by ibell** [comment]
Cool thanks for the question
