### ISSUE TITLE
Props output if independent variable is same as dependent variable

### ISSUE THREAD

**Issue by bachc** [ibell/coolprop#184]
Calling the Props function and requesting a property that is within the known inputs returns the input as result, e.g.

> > > Props('P','T',320,'P',340,'R410A')
> > > 340.0

This behavior is consistent with Refprop but:
doing such a call might  likely the result of a programming error and lead to longer debugging time for the resulting program. 
EES, in contrast, throws an error that the independent variable is same as dependent variable - which is helpful to find programing mistakes.

I prefer the EES behavior, please decide if you see the need for action.

Thanks!

**Comment by ibell** [comment]
@jowr, @kaern @squoilin  - What do you think about this?  I'm on the fence.

**Comment by kaern** [comment]
It is not possible to make such a call in Modelica, so for me it does not matter. I guess the choice depends on the level of additional work this will require, which I cannot estimate.. By the way - Hi Christian..

**Comment by ibell** [comment]
Ok, I've thought about this issue, and I think I am ok to go ahead with making this change.

**Comment by ibell** [comment]
Closed in 9e832e76ff94b1d963e0049672348cee3137456c
