### ISSUE TITLE
When I add a package name, there  will be an error

### ISSUE THREAD

**Issue by yang22zhang** [ibell/coolprop#189]
In the web project by Java calls have to add a package name,but when I for CoolPropJNI.java plus package name will be an error.

+coolprop version: 4.1.2
+OS: windows 32bit/64bit

here is message:

> **class:** java.lang.UnsatisfiedLinkError
> **Message:** com.si.test.coolprop.CoolPropJNI.Props(Ljava/lang/String;CDCDLjava/lang/String;)D

trace：
   Line | Method
->>  195 | doFilter  in PageFragmentCachingFilter.java

---

|     63 | doFilter  in AbstractFilter.java
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run . . . in java.lang.Thread

Caused by ControllerExecutionException: Runtime error executing action
->>  195 | doFilter  in PageFragmentCachingFilter.java

---

|     63 | doFilter  in AbstractFilter.java
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run . . . in java.lang.Thread

Caused by InvocationTargetException: null
->>  195 | doFilter  in PageFragmentCachingFilter.java

---

|     63 | doFilter  in AbstractFilter.java
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run . . . in java.lang.Thread

Caused by UnsatisfiedLinkError: com.si.test.coolprop.CoolPropJNI.Props(Ljava/lang/String;CDCDLjava/lang/String;)D
->>   24 | Props     in CoolPropJ.java

---

|      9 | index     in designController.groovy
|    195 | doFilter  in PageFragmentCachingFilter.java
|     63 | doFilter  in AbstractFilter.java
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    744 | run . . . in java.lang.Thread

How should I solve it？

**Comment by ibell** [comment]
So did you fix the problem?

**Comment by yang22zhang** [comment]
yes.By don't have the package name of class to call.
