### ISSUE TITLE
partial derivative

### ISSUE THREAD

**Issue by olivierslts** [ibell/coolprop#192]
Hello

To apply a reconciliation method with EES, I would need the enthalpy of refrigerant R134a, and  its partial derivatives in terms of polynomes (f(T,P)). Could you help with this please?

**Comment by jowr** [comment]
I am afraid that this is not implemented yet. It shouldn't be too much work though, feel free to add the functionality to the wrapper ;-)

**Comment by ibell** [comment]
I'm going to take a crack at this - this issue is just a place holder to
help me remember to do it!
