### ISSUE TITLE
EES

### ISSUE THREAD

**Issue by JDPS** [ibell/coolprop#196]
Two doubts regarding coolprop external function on EES:
1. I cannot distinguish the fluid quality on liquid and superheated range, since I always get the value -1. It´s supposed to be this way?
2. It´s possible to change the reference for enthalpy and entropy on EES?
Thank you.

**Comment by ibell** [comment]
1. Correct. In version 5 of CoolProp, the fluid quality will be
   approximated in the subcooled and superheated regions such that Q > 1 in
   vapor, Q < 0 in liquid.  In 4.1.2/4.2, it is always -1 if it is not
   two-phase.  A bad design decision, but there you go.
2. Sorry, it's not possible to change reference state in EES.  In other
   languages, yes, but not in EES.

**Comment by JDPS** [comment]
Thank you for the information.
