### ISSUE TITLE
Accessing Refprop through Coolprop with EES for mixture does not work

### ISSUE THREAD

**Issue by bdechesne** [ibell/coolprop#2]
The error i get is:
"CoolProp error: Your refrigerant [REFPROP-MIX:R152a[0.5]&R245fa[0.5]] is from REFPROP, but CoolProp does not support REFPROP on this platform, yet."

It doesn't work either with pure fluids.

Thanks in advance

**Comment by jowr** [comment]
Hm, which version of CoolProp do you use? This error also occurs when the refprop.dll file is not available on our system. Please make sure the refprop.dll file is in your windows/system folder or add the refprop installation directory to your path.

**Comment by bdechesne** [comment]
Le 4/09/2013 13:02, jowr a écrit :

> Hm, which version of CoolProp do you use? This error also occurs if 
> the refprop.dll file is not available on our system. Please make sure 
> the refprop.dll file is in your windows/system folder or add the 
> refprop installation directory to your path.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ibell/coolprop/issues/2#issuecomment-23781170.
> 
> I use the last version of coolprop and Ian added the REFPROP folder in 
> the system folder so i think the problem comes from somewhere else! But 
> thanks for your response though!

## 

Bertrand Dechesne
Assistant / Phd Candidate

Thermodynamics and Energetics Laboratory
University of Liège
Sart-Tilman Campus B49-P33
4000 Liège
Belgium
+32(0)4 366 48 23
bdechesne@ulg.ac.be

**Comment by ibell** [comment]
Fixed with the updated EES version and fixed setting of mole fraction array for second call
