### ISSUE TITLE
HAProps density output error

### ISSUE THREAD

**Issue by d-e-t** [ibell/coolprop#202]
Some properties given by HAProps are way off; is this module broken?  The examples from coolprop.org work fine, but anything involving density seems to give errors. For instance, density comes out as 149.4 kg/m3 regardless of pressure or temp.

```
CP.HAProps('D','T',297.15,'P',101.3,'R',0.0)
```

I'm also having problems with the spec. entropy output.

**Comment by ibell** [comment]
'D' is the symbol for dewpoint, see
http://coolprop.sourceforge.net/apidoc/HumidAirProp.html#CoolProp.HumidAirProp.HAProps

What problem do you have with entropy?

**Comment by d-e-t** [comment]
...whoops!  Obviously I'm new to using CoolProp.  Having 'D' as density in Props and dewpoint in HAProps is a tricky one though...  With that cleared up, I'll have to go back and check if I'm still having problems.
