### ISSUE TITLE
Problem with entropy in excel

### ISSUE THREAD

**Issue by pijmleko6** [ibell/coolprop#204]
I use coolprop to heat pumps project and and every time when I have to read something that has to do with entropy maybe also with enthalpy exel is crashing eg. when I'm writing =Props("T";"S";J6;"P";H6;"Water") and excel is dead

**Comment by ibell** [comment]
What are the values that go into that function to cause Excel to crash?
Are you using the most recent version of CoolProp - 4.1.2?

**Comment by pijmleko6** [comment]
So for this =Props("T";"S";J6;"P";H6;"R1234yf") and J6 is another coolprop function =Props("S";"T";G4;"P";H4;"R1234yf") and so on until  start where I have the temperature evaporator and condenser and H6 is  Props("P";"T";C3;"Q";"R1234yf").fluid is R1234yf . And yes i have 4.1.2

**Comment by ibell** [comment]
What are the _numbers_ that go into the Props function? I need to be able
to replicate the error to fix it.

**Comment by pijmleko6** [comment]
=Props("T";"S";1,615611229;"P";1018,393275;"R1234yf") I struggle with this for 3 days and say that it is not the fault of numbers , because if you enter the number  not oreferences to other cells everything is works.

**Comment by ibell** [comment]
Right, there is a bug in CoolProp that I need to fix.  Would have been good
if you could have filed the issue before...  Hope to get to it tomorrow.

**Comment by pijmleko6** [comment]
Thank you man ! :D

**Comment by ibell** [comment]
Fixed in 12bef51720e8f5e005134839b28e1bbdeb3e9a23

New DLL for Excel can be downloaded from http://sourceforge.net/projects/coolprop/files/CoolProp/Nightly/2014.04.07/
