### ISSUE TITLE
Enthalpy with "T" and "P" as inputs

### ISSUE THREAD

**Issue by redorangdude** [ibell/coolprop#206]
I have found that the result when calculating enthalpy does depend on the order of the inputs. With R404a @ T=161.816 °F and P= 234.904 psia I get the following:

With T as first input - 108.3229 btu/lbm
With P as first input - 664.3222 btu/lbm

Additionally with P as the first input, it looks like T is completely ignored. I changed T well below the Tmin for R404a and it still gives the result 664.3222 btu/lbm.

Apologies for not using SI units, its the curse of being an american engineer.

**Comment by ibell** [comment]
Please provide a minimal example (in SI units!) that demonstrates this
problem.

What language? What operating system?

**Comment by redorangdude** [comment]
Heres your SI units. I don't think I need to re-write the example.
161.816 °F = 345.27 K
234.904 psia = 1619.606 kPa
108.3229 btu/lbm = 251.96 kJ/kg
664.3222 btu/lbm = 1545.213 kJ/kg

I'm using the DLL through Microsoft Excel 2013 Visual Basic on Windows 7 Professional.

**Comment by ibell** [comment]
Can you attach a minimal XLS file calling with the two orders please?  This
behavior is something I have never seen before, and I think it might be
something in your implementation.  There's no obvious issue in my mind.

Are you using CoolProp 4.1.2?

**Comment by redorangdude** [comment]
I'll save you the trouble. :-). I went and took my code out of the
calculation and it was fine.
Can you attach a minimal XLS file calling with the two orders please? This
behavior is something I have never seen before, and I think it might be
something in your implementation. There's no obvious issue in my mind.

Are you using CoolProp 4.1.2?

On Tue, Apr 8, 2014 at 10:51 PM, redorangdude notifications@github.comwrote:

> Heres your SI units. I don't think I need to re-write the example.
> 161.816 °F = 345.27 K
> 234.904 psia = 1619.606 kPa
> 108.3229 btu/lbm = 251.96 kJ/kg
> 664.3222 btu/lbm = 1545.213 kJ/kg
> 
> I'm using the DLL through Microsoft Excel 2013 Visual Basic on Windows 7
> Professional.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/ibell/coolprop/issues/206#issuecomment-39900201>
> .

## 

Reply to this email directly or view it on
GitHubhttps://github.com/ibell/coolprop/issues/206#issuecomment-39901431
.

**Comment by ibell** [comment]
Cool good to hear.
