### ISSUE TITLE
Installing CoolProp with Pip issue

### ISSUE THREAD

**Issue by qvn** [ibell/coolprop#214]
Hey guys, thanks for making this cool properties package. 

I'm no expert in Python but I have been dabbling a bit. When trying to pip CoopProb, I keep getting these errors: 

```
build/temp.macosx-10.9-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:25556:26: error: expected the class name after '~' to name a destructor

  p->Fluid.std::string::~string();
                         ^
build/temp.macosx-10.9-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:25557:26: error: expected the class name after '~' to name a destructor

  p->phase.std::string::~string();
                         ^
```

And then I would have 

```
error: command 'clang' failed with exit status 1
```

I'm on a mac and I have a command line tools. So when I check for clang, I got it somewhere:

```
(temp2)Quyens-Mac-Pro:~ qvn$ which clang
/usr/bin/clang
```

Any thoughts?

**Comment by ibell** [comment]
You need to install the most recent version of Cython.  There was a bug
with clang which was causing this problem, but is fixed now.

**Comment by qvn** [comment]
I just checked and I happen to have cython 0.20 is that right?

```
(temp2)Quyens-Mac-Pro:LearnOO qvn$ cython --version
Cython version 0.20.1
```

**Comment by ibell** [comment]
I think you need to recompile Cython from source as the changes that fix
clang came after the release of 0.20.1 if I am not mistaken. Do you know
how to recompile cython from source?  You can pull the zip from
https://github.com/cython/cython/archive/master.zip

**Comment by qvn** [comment]
I got it!!! There are instruction in Cython packages to install the 0.21dev. Everything went smoothly now. 

Thank you for your help!
