### ISSUE TITLE
H,D and S,D Iterations

### ISSUE THREAD

**Issue by paarfi** [ibell/coolprop#220]
Could you please add support for H,D and S,D as inputs to calculate T? That would be very helpful with our partial compression calculations.

Thanks.

**Comment by ibell** [comment]
They will be supported in CoolProp v5, but there are not plans to support
them in v4.x.  You can check out the new v5 code at
https://github.com/CoolProp/CoolProp .  It is under active development
though, so many things are not working at the moment.

**Comment by ibell** [comment]
Implemented in v5, will not fix in v4.x
