### ISSUE TITLE
Water/Glycol (EG-50%) enthalpy  inconsistency

### ISSUE THREAD

**Issue by romarro** [ibell/coolprop#224]
I am using the CoolProp version 4.2.2
I want to find the enthalpy of EG-50% at a certain temperature: 
In[33]: Props('H','T',26+273.15,'P',200,'EG-50%')
Out[34]: -19.044985684

But when I want to find the same temperature knowing the enthalpy I get an error. 

In[35]: Props('T','H',-19.044985684,'P',200,'EG-50%')
Traceback (most recent call last):

  File "<ipython-input-35-5ba3a4652582>", line 1, in <module>
    Props('T','H',-19.044985684,'P',200,'EG-50%')

  File "CoolProp.pyx", line 229, in CoolProp.CoolProp.Props (build\temp.win-amd64-2.7\Release\pyrex\CoolProp\CoolProp.cpp:11077)

  File "CoolProp.pyx", line 324, in CoolProp.CoolProp.Props (build\temp.win-amd64-2.7\Release\pyrex\CoolProp\CoolProp.cpp:10473)

  File "CoolProp.pyx", line 225, in CoolProp.CoolProp.__Props_err2 (build\temp.win-amd64-2.7\Release\pyrex\CoolProp\CoolProp.cpp:9995)

ValueError: CoolProp error: Brine Temp.(-5082.43 C) out of range [-147.289, 100] for fluid EG
 :: inputs were:"T","H",-1.9044985684000000e+01,"P",2.0000000000000000e+02,"EG-50%

**Comment by ibell** [comment]
@jowr - any thoughts?

**Comment by ibell** [comment]
Sounds like a unit conversion bug to me.  What if you use the PropsSI
function?

**Comment by romarro** [comment]
Nope, I did with PropsSI and get the same error 

here is the run

PropsSI('H','T',26+273.15,'P',2e5,'EG-50%')
-19044.985684
PropsSI('T','H',-19044.985684,'P',2e5,'EG-50%')
Traceback (most recent call last):

  File "<ipython-input-6-f2964a2eb14f>", line 1, in <module>
    PropsSI('T','H',-19044.985684,'P',2e5,'EG-50%')

  File "CoolProp.pyx", line 360, in CoolProp.CoolProp.PropsSI (build\temp.win-amd64-2.7\Release\pyrex\CoolProp\CoolProp.cpp:12466)

  File "CoolProp.pyx", line 458, in CoolProp.CoolProp.PropsSI (build\temp.win-amd64-2.7\Release\pyrex\CoolProp\CoolProp.cpp:11862)

  File "CoolProp.pyx", line 356, in CoolProp.CoolProp.__PropsSI_err2 (build\temp.win-amd64-2.7\Release\pyrex\CoolProp\CoolProp.cpp:11384)

ValueError: CoolProp error: Brine Temp.(-5082.43 C) out of range [-147.289, 100] for fluid EG
 :: inputs were:"T","H",-1.9044985683999999e+04,"P",2.0000000000000000e+05,"EG-50%"

**Comment by ibell** [comment]
Hmm guess not - Ill take a look.

**Comment by jowr** [comment]
I do not know what is going wrong, but the solvers for (h,p)-inputs are not that solid in 4.2... This will be much better in v5, but let us try and improve things a little bit for 4.2 as well. @ibell, maybe this can be discussed next week as well.

**Comment by ibell** [comment]
I fixed it - it needed a call to PropsSI instead of Props.

**Comment by romarro** [comment]
So it works if you call:
h=Props('H','T',26+273.15,'P',200,'EG-50%')
and then :
T=PropsSI('T','H',h,'P',200,'EG-50%')
you get T=26.00000 C
but how do we explain this ? 
PropsSI should have h input with J/kg and Props should give h with kJ/kg

**Comment by ibell** [comment]
I cannot duplicate this behavior at the C++ level.  What do you get for h?
When I do the cycle with either Props or PropsSI, I get back to T = 26 C.

You did recompile CoolProp, right?

**Comment by romarro** [comment]
no, I didn't recompile CoolProp, I had downloaded the windows compiled version 4.2.2 for python from the site. 
the h value is -19.04498

**Comment by ibell** [comment]
Ah, you need to recompile to get all the correct behavior.  Until you do
so, you will have the erroneous code.  I can work on a bugfix release, but
I have to make some architectural changes, so it might be just a while.

**Comment by romarro** [comment]
ok thanks, for now I can live with this. The important thing is that we have discovered a workaround.

**Comment by ibell** [comment]
bugfix release released.  You should be able to do pip install CoolProp and it download a binary wheel to avoid compilation

**Comment by romarro** [comment]
thx

**Comment by ibell** [comment]
Please close the issue if you are satisfied.
