### ISSUE TITLE
problem installing, python 3.4

### ISSUE THREAD

**Issue by aadhate** [ibell/coolprop#226]
Hello,

I have been trying to install CoolProp from pip and I'm getting the following error:

pip install CoolProp
Downloading/unpacking CoolProp
  Downloading CoolProp-4.2.3.zip (1.0MB): 1.0MB downloaded
  Running setup.py (path:/tmp/pip_build_abhir/CoolProp/setup.py) egg_info for package CoolProp
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_abhir/CoolProp/setup.py", line 34, in <module>
        if cmdline and ''.join(cmdline).find('pycompletionserver.py') > 0:
    TypeError: can only join an iterable
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_abhir/CoolProp/setup.py", line 34, in <module>

```
if cmdline and ''.join(cmdline).find('pycompletionserver.py') > 0:
```

TypeError: can only join an iterable

Any suggestions on what I should try?

**Comment by ibell** [comment]
Can you try uninstalling psutil?  Unless you need it?  Apparently they have
changed their API from when I used it.   Alternatively, remove that whole
psutil block -
https://github.com/ibell/coolprop/blob/master/wrappers/Python/setup.py#L30-L39

Also, I don't think CoolProp works on 3.4 - at least I haven't tested it
yet.  What OS do you use?  Windows? Linux?  Are you using anaconda?

**Comment by aadhate** [comment]
I use Linux and anaconda. I didn't realize that CoolProp did not support 3.4 yet, would you recommend switching to an earlier version (I'm just starting with python).

**Comment by ibell** [comment]
Yes, for now, 3.4 seems to have some compatibility issues.  I recommend
3.3, that works fine for me.
