### ISSUE TITLE
HAPROPS PROBLEM

### ISSUE THREAD

**Issue by ghost** [ibell/coolprop#227]
Hello Ian,

THE FOLLOWING FORMULA LEAD TO AN ERROR :
haprops("H","T",45+273.15,"R",0.6,"P",101.325)

Could you please correct this error ?

Sincerely,
PY

**Comment by jjgomera** [comment]
Works fine here:

 In [1]: from CoolProp.HumidAirProp import HAProps
 In [2]: HAProps("H","T",45+273.15,"R",0.6,"P",101.325)
 Out[2]: 142.57362773649277

**Comment by ibell** [comment]
And in version 5 (https://github.com/CoolProp/CoolProp), works too:

In [3]: from CoolProp.HumidAirProp import HAPropsSI

In [4]: HAPropsSI("H","T",45+273.15,"R",0.6,"P",101325)
Out[4]: 142573.62546989485
