### ISSUE TITLE
How to perform CoolProp tests properly

### ISSUE THREAD

**Issue by sagitter** [ibell/coolprop#228]
Hi all.

How can I perform all CoolProp tests properly by using a single command?

**Comment by ibell** [comment]
You can do

```
import CoolProp
CoolProp.test()
```

It is expected that some of the tests will fail - in version 5 which is in development at https://github.com/CoolProp/CoolProp, all the tests will pass when we are done.

**Comment by sagitter** [comment]
Thank you.
