### ISSUE TITLE
Saturation temperature in coolpropsolver.cpp

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#23]
In the Modelica wrapper, saturation temperature is defined as bubble line temperature. Shouldn't this rather be a computed value? Tsat = (TV - TL) \* _Q + TL does anyone see any problems with such a formulation?

**Comment by ibell** [comment]
But what about mixtures?  They don't have a "saturation temperature".

**Comment by thorade** [comment]
@jowr For pure fluids you have Tsat=TV=TL so using the bubble line temperature would be fine in that case

**Comment by ibell** [comment]
But we also have to worry about psedo-pure mixtures, for which it is not
true that Tsat=TV=TL.

**Comment by jowr** [comment]
Exactly, that is why I think we should use the quality weighted temperature...

**Comment by ibell** [comment]
But, the temperature is not quality weighted in the two-phase region.  It's
close, but not exactly.

**Comment by thorade** [comment]
Yep, sorry, I forgot you also treat pseudo-pure and I should remember not to post on the internet during my after lunch fatigue.
