### ISSUE TITLE
Plot after fresh install on a mac

### ISSUE THREAD

**Issue by vancesteven** [ibell/coolprop#230]
I got it working in 2.7 --> conda create py2k py=2 is nice 

 After making sure I can run query the version (4.2.3) and get properties 
 of 
 fluids, I tried plotting something from some of the examples. Here is the 
 error I keep getting in ipython notepad. 

> In [43]: 
> 
> ts_plot = PropsPlot('R290', 'Ts') 
> 
> ts_plot.show() 
> 
> ---------------------------------------------------------------------------TypeError 
> 
> Traceback (most recent call 
> last)<ipython-input-43-dae5f0cbc426> in <module>() 1 ts_plot = 
> PropsPlot('R290', 'Ts')----> 2 ts_plot.show() 
> /Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/Plots/Common.pyc 
> 
> in show(self) 296 297 def show(self):--> 298 
> self._draw_graph() 299 matplotlib.pyplot.show() 
> /Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/Plots/Plots.pyc 
> 
> in _draw_graph(self) 500 501 def _draw_graph(self):--> 502 
> self.__draw_region_lines() 503 
> self._plot_default_annotations() 504 
> self.scale_plot(plot_units=self.plot_units) 
> /Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/Plots/Plots.pyc 
> 
> in __draw_region_lines(self) 496 lines = 
> self._get_sat_lines(kind='T', 497 
> smin=self.smin,--> 498 
> smax=self.smax) 499 drawLines(self.fluid_ref, lines, 
> self.axis) 500 
> /Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/Plots/Common.pyc 
> 
> in _get_sat_lines(self, kind, smin, smax, num, x, line_opts) 161 
> _, x_vals = self._get_fluid_data(self.graph_type[1], 162 
> 'Q', x,--> 163 
> kind, sat_mesh) 164 165 
> if self.graph_type[0] != kind: 
> /Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/Plots/Common.pyc 
> 
> in _get_fluid_data(self, req_prop, prop1_name, prop1_vals, prop2_name, 
> prop2_vals) 129 prop1_name, 
> p1_val, 130 prop2_name, 
> prop2_vals[i],--> 131

**Comment by ibell** [comment]
I cannot replicate.  Can you provide a minimal script that demonstrates the
problem, with versions for CoolProp, matplotlib, python, etc.?

This works fine for me:

```
C:\Users\Belli>python
Python 2.7.6 |Continuum Analytics, Inc.| (default, May 27 2014, 15:00:33)
[MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io and https://binstar.org
>>> from CoolProp.Plots.Plots import PropsPlot
>>> ts_plot = PropsPlot('R290','Ts')
>>> ts_plot.show()
```

**Comment by vancesteven** [comment]
That works fine for me too.  Maybe it was a problem with ipython notebook.

Thanks!

# 

Dr. Steve Vance
Astrobiologist, Planetary Scientist, Human
626-437-6200 (cell)

# vance.steven@gmail.com
