### ISSUE TITLE
zero occured in row 3

### ISSUE THREAD

**Issue by squoilin** [ibell/coolprop#231]
when compiling the Coolprop2Modelica wrapper with the latest version from github, then running into dymola, I get the message below. It occurs for many fluids, but I cannot reproduce it at the c++ level.

TwoPhaseMedium_setState_ph_(1.6500000000000000e+006, 2.5653687955785857e+005, 2, pointer, "R407c", "CoolProp", "R407c");
works fine. 

but in Dymola I get:
debug has the value of 6
Checking fluid R407c against database.
Check passed, reducing R407c|debug=6 to R407c
Setting constants for fluid R407c
setState_ph(p=1.6500000000000000e+006,h=2.565368795578
Zero occurred in row 3, the matrix is singular.
Press the Stop button in Dymola to end the simulation!

any idea?

**Comment by ibell** [comment]
One idea is to compile the library as a DLL, which would allow us to do
line-by-line debugging, and see exactly what is happening.  It might be a
bit tricky to get working, but could be worth it in the long run.

If there is interest in this, I can see if I can get something working.

Ian

**Comment by squoilin** [comment]
Ok I solved it in this revision:
https://github.com/ibell/coolprop/commit/22e19cc508d67f0b26221f4480917b045a46c9a7
There are some mysterious things remaining though

For the dll, let's try to to this for version 5.0. Same for the above issues, I prefer to spend time debugging them in the new release.
