### ISSUE TITLE
Excel Addin: R404A wrong thermal conductivity

### ISSUE THREAD

**Issue by spiderpinne** [ibell/coolprop#232]
The Coolprop 4.2.0 Excel Addin returns thermal conductivity for R404A in the wrong decimal power.

The correct Value would be the returned value \* 10 ^ 3.

**Comment by ibell** [comment]
I made the fix locally, but didn't push it.   I'll release 4.2.4 tonight
with this bug fixed.  Alternatively you can build the DLL yourself.

**Comment by ibell** [comment]
Build in progress, should be online in another hour or two.

**Comment by ibell** [comment]
Ok its online now.  Can you please confirm that this fixes it?

**Comment by spiderpinne** [comment]
Fix works! Thank you very much for the fast response!
