### ISSUE TITLE
CoolProp in JAVA

### ISSUE THREAD

**Issue by EVT1982** [ibell/coolprop#235]
For my diploma thesis I need some property data. I followed your instruction to integrate CoolProp.dll, but it finally doesn't work out. First I want to explain my proceeding:

1.I installed Visual Studios 2012
2.I installed SWIG
3.Changed the destinations of the paths in the build_x64.bat (I use a 64-bit System) 
4.Put the CoolProp.dll, the content of the SWIG folder and the build_x64.bat in one folder and execute the build_x64.bat.
5. A new CoolProp.dll was build and here the report 
![report](https://cloud.githubusercontent.com/assets/8436275/3903233/b3708d54-22c9-11e4-82b4-537d819a3d6c.jpg)
6. I copied all builded java files and the builded CoolProp.dll and try to start the example. 

Thank in advance for your quick response.

**Comment by ibell** [comment]
What error do you get?

**Comment by ibell** [comment]
Are you sure that your Java is 64-bit?

**Comment by EVT1982** [comment]
As you can see i got no error.
![report1](https://cloud.githubusercontent.com/assets/8436275/3903944/8cdec8f0-22d2-11e4-82f1-1ec665da1d19.jpg)
And I am sure that it is a 64-bit, it's a amd athlon II P360.

**Comment by ibell** [comment]
But even if your _computer_ is x64, your Java can still be 32-bit.  For me,
I get:

```
C:\Users\Belli>java -version
java version "1.7.0_40"
Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
Java HotSpot(TM) 64-Bit Server VM (build 24.0-b56, mixed mode)
```

what do you get?

When you run the example, what is the error you get?

**Comment by EVT1982** [comment]
I solved the problem. I didn't copy the CoolProp.dll into the java.library.path. 
Now everything is working fine.

Thank you again for your help and quick response.

**Comment by ibell** [comment]
Ok cool, glad to hear.  Please close this ticket.
