### ISSUE TITLE
Speeding

### ISSUE THREAD

**Issue by AllanStarke** [ibell/coolprop#236]
Hi,

I am using the Coolprop with Fortran, using the BIND_C for the interface, like we discussed in the other topic. 

I am trying to incorporate the Coolprop library in a transient solver, therefore, I have a massive number of function call of Props function (4x10^6). I'm optimizing the code to minimize the computational work, thereby, I'm looking for the best options of the Coolprop library.

I'm already using the temperature and density to evaluate the properties (since Equations of State are all explicit in temperature and density), and the TTSE look up table. There are other options to enhance the speed of the code?

I am trying to write a Fortran interface for the function "get_global_param_string("version")", however, looking tho expotsDLL.txt (@ SharedLibrary  ),  I haven't found the exported function to do so. Which one is the correct exported function?

Can you help me to understand the functionality of the enable_TTSE_LUT_writing() function?
And how this option change the the Coolprop?

Best regards

**Comment by ibell** [comment]
How long does 4e6 evaluations take you?  It should be on the order of a few
microseconds per call, so something like 4 seconds for 4e6 calls I should
think.  The FORTRAN-C interface could be slowing things down quite a bit.

TTSE or Bicubic wont help all that much if you are already using TD as
inputs since there is still overhead calling the TTSE method.

_get_global_param_string@8 is the function you want.  It takes a
pre-allocated zero-terminated string which is pre-allocated in REFPROP
land.  See the header at
https://github.com/ibell/coolprop/blob/master/CoolProp/CoolPropDLL.h

Also, see our new library in v5.  Still work to be done, but we could use
some testers.

**Comment by AllanStarke** [comment]
Hi,
I found the _get_global_param_string@8, but why there are two inputs (param and Output)?
`<get_global_param_string(const char *param, char *Output);>`  

param - should be 'version', but 'Output'?

I have something like this,

```
a = enable_TTSE_LUT("Water"//CHAR(0))
c = isenabled_TTSE_LUT("Water"//CHAR(0))

DO i=1,1000000


        Call Water_TP(T(1),P(1), dens=D(1), enth=h(1), inte=u(1), entr=s(1), cp=cp(1), cv=cv(1), cond=k(1), visc=mu(1),qual=x(1)) 

       Call Water_TQ(T(2),x(2), pres = P(2), dens=D(2), enth=h(2), inte=u(2), entr=s(2), cp=cp(2), cv=cv(2), cond=k(2), visc=mu(2))

       Call Water_PQ(P(3),x(3), temp = T(3), dens=D(3), enth=h(3), inte=u(3), entr=s(3), cp=cp(3), cv=cv(3), cond=k(3), visc=mu(3))

       s(4) = s(3)
       Call Water_PS(P(4),s(4), temp = T(4), dens=D(4), enth=h(4), inte=u(4), qual=x(4), cp=cp(4), cv=cv(4), cond=k(4), visc=mu(4))

       h(5) = 0.80*h(4)
       Call Water_PH(P(5),h(5), temp = T(5), dens=D(5), inte=u(5), entr=s(5), qual=x(5), cp=cp(5), cv=cv(5), cond=k(5), visc=mu(5))

   ENDDO
```

Each Call Water_XX.. evaluates 9 Props function, so.. 9_5_1000000 = 4.7e7 evaluations
This take:

0.471 sec to build both two phase tables
t=    415.352662500000 sec          N = 1000000

415 seconds it's quite fast, and it takes only 0.417 to write the tables.

Using 'Bicubic', with DO i=1,40000 takes, (1.80E+06)

t = 415.945466300000 secs           N= 40000

Sumarizing:

TTSE          4.7E+07 evaluations      -->415.35 secs
Bicubic       1.80E+06 evaluations      --> 415.94 secs.

same time, but TTSE has 25x more points... sounds right?

**Comment by ibell** [comment]
Sorry, right, param is the thing you want("version"), and output is the
pre-allocated string that the result will be put into.

The same tables are used for both and are cached on the computer. (in the
%HOME%/.CoolProp-TTSE or something similar).  You should start the clock
around only the calculation block.  You should see that bicubic is about
10% slower than TTSE, but both are much faster than the full EOS.

8us/call with TTSE is a bit slower than I would think.  But you do have the
data passing with FORTRAN/C.  So who knows.  I think that's about as fast
as you can do.

**Comment by AllanStarke** [comment]
Hi,

Tank you for your answer. I just needed to know if there was other ways to optimize it with something that I'm not aware.

Yesterday, one of the transient simulations was taking 1h, and the another takes 10-12h.
Now, with the TD and with TTSE, they take 100sec and 600sec. So, I can't complain!

I intent to start using the CoolProp 5 next weekend. I don't start yet, because I couldn't find the SharedLibrary folder, so I need to start over.

**Comment by ibell** [comment]
Cool!  I love to hear things like that :)
