### ISSUE TITLE
Coolprop Refprop pcrit with wrong unit prefix

### ISSUE THREAD

**Issue by mayersre** [ibell/coolprop#238]
A call to PropsSI(refpropfluid,'pcrit')) returns a value in MPa, should be Pa

example code:
###### 

import CoolProp
import CoolProp.CoolProp as cp
# 

print(CoolProp.**version**)
# 

refs=['R134A','REFPROP-R134A','PROPANE','REFPROP-PROPANE','R744','REFPROP-CO2']
for ref in refs :
    print(ref,cp.PropsSI(ref,'pcrit'))
###### 
## result (I added whitspaces to align the numbers): 

4.2.5
R134A                           4059280.0
REFPROP-R134A         4.05928
PROPANE                     4251200.0
REFPROP-PROPANE   4.2512
R744                             7377300.0
REFPROP-CO2            7.3773

**Comment by ibell** [comment]
Ok, I will fix it today.
