### ISSUE TITLE
Refprop mixtures off IIR scale

### ISSUE THREAD

**Issue by mayersre** [ibell/coolprop#239]
Hi,

refprop mixtures do not scale properly to IIR (200kJ/kg at 273.15 liquid)

the following code reproduces the problem:
###### 

import CoolProp
import CoolProp.CoolProp as cp
# 

print(CoolProp.**version**)
# 

refs=['REFPROP-MIX:R407A.MIX','REFPROP-MIX:R407C.MIX','REFPROP-MIX:R407F.MIX']

for ref in refs :
    print(cp.PropsSI('H','T',273.15,'Q',0,ref))
###### 

output should be 200.00000 by definition
4.2.5
200650.3589402943
200843.08823723203
200996.83154258208
###### 

I double checked with excel refprop, there it is ok 

fluid   enthalpy    TLIQ means 'Q' = 0

R407A.MIX   200,00000   =Enthalpy(C7;"TLIQ";"mks";273,15)
R407C.MIX   200,00000   =Enthalpy(C8;"TLIQ";"mks";273,15)
R407F.MIX   200,00000   =Enthalpy(C9;"TLIQ";"mks";273,15)

regards
Reiner

**Comment by ibell** [comment]
Confirmed as issue.

**Comment by ibell** [comment]
But really, there is nothing "wrong" with CoolProp as far as I can tell.
How it ends up giving you back 200,000 when you use Excel is more a mystery
to me.  Nowhere in the .mix file does it specify the default reference
state.

**Comment by ibell** [comment]
If you want it to be exactly 200,000, you can always subtract difference
from h(T=273.15, Q = 0)

**Comment by ibell** [comment]
If you call SETREF directly in C++ (which I assume the excel spreadsheet is
doing), you get the right value. Otherwise, there is no way to know _a
priori_ what the reference state should be.
​

**Comment by ibell** [comment]
Closed unless you can propose a stable means of dealing with this.  Calling the set_reference_state function would be an option and then calling REFPROP's setref function, but I haven't worked on that for mixtures yet.  Definitely not going to happen for 4.x, would consider it for v5.

**Comment by mayersre** [comment]
Hi Ian,

thanks for your responses on this, pls. don't work too late in the night ;)

I would be happy to have this available in V5, just some clear way how 
to deal with it.

Currently I added the correction just before plotting or printing ... 
which makes code not nice.

PS.: It is the same with Entropy ...

Thanks & kind regards
Reiner

Am 05.09.2014 um 01:03 schrieb Ian Bell:

**Comment by ibell** [comment]
Well, I think the easiest is to do like REFPROP and use the
set_reference_state function for both mixtures and pure fluids.  Though for
the moment I don't understand how to set reference states for mixtures.  I
need to think a little about that.  In principle it ought to be rather
straightforward.

For now, I don't have any brilliant ideas.
