### ISSUE TITLE
Scilab

### ISSUE THREAD

**Issue by Jjhayi** [ibell/coolprop#242]
Hello again
I tried on Scilab, because its closer to octave
But i got a new problem
Any tips?
![captura de tela 2014-10-02 18 08 40](https://cloud.githubusercontent.com/assets/9000464/4498517/46dab890-4a79-11e4-85d8-815874d158df.png)

**Comment by ibell** [comment]
Scilab calls the DLL.  Where is the dll and where are your function
definitions? You need to follow the example and its instructions at

http://sourceforge.net/projects/coolprop/files/CoolProp/4.2.5/Scilab/

**Comment by Jjhayi** [comment]
The dll, the sample and script are on the same file (last three files on right in the image).
The code calling the function is on the left
First i run the sample, then the "trocador"
Am i doing something wrong?

**Comment by Jjhayi** [comment]
ohh nvm, it worked :)
thanks

**Comment by ibell** [comment]
Cool! Please close the issue.
