### ISSUE TITLE
CoolProp GUI (Design Considerations)

### ISSUE THREAD

**Issue by Rod-Persky** [ibell/coolprop#248]
UI Design ideas thread, what should be included in the first version that will make life easer? #247 

RefProp has a good number of different tables:
- Specified state points
- Saturated state points

Plots:
- All basic flash calculations

And Options:
- Reference state
- Units
- Preferences

For an initial version, what is the absolute minimum requirements?

**Comment by Rod-Persky** [comment]
Moved to coolprop/coolprop

**Comment by hyhzju** [comment]
I would say not necessary to separate the tables into specified or saturated (V-L or S-L). Just a table, but allowing the user to input a few letters (such as sl for saturated liquid, sv for saturated vapor) along with the values for specified state points. When for output, it also indicates whether it is just on the saturated line or not. 

Graphs would be fine. But there are a lot of professional graphical software available. When we have a data table, we can do what ever we need for produce nice graphs, which are in publication quality. Here the important thing is to provide strong data export functions, which can produce data files compatible to microsoft Excel, LibreOffice Calc, Origin, SigmaPlot, GNUPlot etc.

Refprop does not allow to change the values already generated in the table by changing the units. I think if we could realize a "dynamic/instantly/simultaneously" change will be attractive.
