### ISSUE TITLE
Model error - sqrt (2*DP_cd.rho_nom) = sqrt (-6.32246e-005)

### ISSUE THREAD

**Issue by enter802** [ibell/coolprop#249]
Hi,

Whenever I try to simulate Sylvain Quoilin's thesis model (SQThesisModel) from the thermocycle library, I get the following model error: "Model error - sqrt (2*DP_cd.rho_nom) = sqrt (-6.32246e-005)"

And similar error occurs for other models too.

Can someone help me solving this issue? May be this is a very minor issue, but some help would be great! Thanks in advance.

**Comment by ibell** [comment]
Not sure why this error is posted to coolprop issues.  Doesn't seem related
to CoolProp.  Better to post to https://github.com/thermocycle/
