### ISSUE TITLE
CoolProp 5.0.5 from PyPI: Python import error

### ISSUE THREAD

**Issue by ghost** [ibell/coolprop#250]
Hi,
CoolProp 5.0.5 + Python 3.4

Installed CoolProp 5.0.5 from PyPI and using:

<pre>import CoolProp.CoolProp as CP</pre>

throws the error:

<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/CoolProp/__init__.py", line 5, in <module>
    from . import constants
  File "/usr/lib/python3.4/site-packages/CoolProp/constants.py", line 3, in <module>
    import _constants
ImportError: No module named '_constants'
</pre>

<b>EDIT: SORRY, POSTED IN THE WRONG PLACE; CLOSING IT HERE</b>

**Comment by ibell** [comment]
And OSX?  What version of python?

There's a weird problem it seems that I can't currently replicate.  Windows
and some OSX work fine.

@jowr, does this work on your mac?  It does, right?  Aren't we using it for
the docs?

**Comment by ghost** [comment]
I'm running Archlinux with Python 3.4.2.

If you haven't noticed, I posted this in the wrong place i.e. issues for version 4; have reposted the issue here:
https://github.com/CoolProp/CoolProp/issues/388
