### ISSUE TITLE
coolprop js any server installs needed?

### ISSUE THREAD

**Issue by ghost** [ibell/coolprop#251]
Hi, Firstly, thanks for the great work! 

I wanted to make a webpage with some ORC cycle calculations  to use in my teachings. I downloaded your example (link below) but it won't work. When I clean up everything but the essentials, it boils down to an error caused by using the PropsSI function... (yes, I do have the coolprop.js file on my server) 

Is it required to install something on the server or is there some server parameter setting required.

Thanks in advance
Ulrik

https://github.com/ibell/coolprop/blob/master/wrappers/Javascript/index.html

**Comment by jowr** [comment]
Hi. Have you had a look at the latest version? This ist the repository for v4 and v5 is developed https://github.com/CoolProp/Coolprop. The online version is maintained at https://github.com/CoolProp/Coolprop-Online and an example can be found via the homepage http://coolprop.sourceforge.net/online/index.html.

**Comment by ghost** [comment]
Hi again, As I understand it the version you refer to is Python based. The one I wish to use, because it seems easier, is the one linked to below. Is this one depreciated?. 
https://github.com/ibell/coolprop/blob/master/wrappers/Javascript/index.html

**Comment by jowr** [comment]
Well, it should still owrk, but the JavaScript interface might have changed. I have to admit, that I have never used that one myself though. Maybe you can post the error you get and/or your inputs.

**Comment by ghost** [comment]
Good idea! Here goes:

coolprop.js:1 missing function: feclearexcept
coolprop.js:1 -1
coolprop.js:1 -1
coolprop.js:26 Uncaught abort() at Error
    at stackTrace (http://.../coolprop.js:1:21064)
    at abort (http://.../coolprop.js:26:34738)
    at _feclearexcept (http://.../coolprop.js:1:4039080)
    at rA (http://.../coolprop.js:5:251522)
    at eval (eval at cwrap (http://.../coolprop.js:1:14286), <anonymous>:1:619)
    at window.onload (http://.../coolP.php:19:12)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by jowr** [comment]
Did you try to do what it suggests? (Building the JavaScript wrapper with more debug output enabled)

**Comment by ibell** [comment]
Yes it is not working, I will debug and see why not.

Closing this issue, follow the progress here: https://github.com/CoolProp/CoolProp/issues/442
