### ISSUE TITLE
Properties of therminol fluids

### ISSUE THREAD

**Issue by jsbahamonde** [ibell/coolprop#252]
Dear Ian

I just installed the lates version of Matlab-CoolProp (5.0.7). It works properly with fluid like water. However, for fluids like thermino if gives me problems:

Here the screenshot:

![scsh](https://cloud.githubusercontent.com/assets/10710216/6270454/73108116-b85a-11e4-9bf4-e96eb1e2efbe.png)

Hope you can help me.

Regards,

Sebastian

**Comment by jowr** [comment]
The error is correct, the standard backend is a Helmholtz-energy-based one and that does not support T66. Use `INCOMP::T66` instead. If I am not mistaken, just `T66` has never worked before.

**Comment by jowr** [comment]
Not in version 5 at least... It did in version 4 though.

**Comment by jsbahamonde** [comment]
It works! Thank you very much.

**Comment by jowr** [comment]
You are welcome. Please have a look at the documentation if you experience errors. Many things changed from version 4 to 5 and you might discover a few more rough edges. Please keep posting issues in case you find bugs.

**Comment by jowr** [comment]
... and please use the new repo at https://github.com/CoolProp/CoolProp next time.
