### ISSUE TITLE
Reciprocal_density option not working

### ISSUE THREAD

**Issue by dinojr** [ibell/coolprop#256]
According to the docstring of class PropsPlot(BasePlot), there is an option to plot P versus 1/rho. It doesn't seem to be used however. Consider the following MWE:

```
from CoolProp.Plots import PropsPlot

ts_plot = PropsPlot('R290', 'PD', reciprocal_density= True)
ts_plot.show()
```

The graph plots P versus rho regardless of the reciprocal_density option value.

**Comment by jowr** [comment]
Please have a look at https://github.com/CoolProp/CoolProp/issues/651
