### ISSUE TITLE
Vapor mass quality = 1 generates error

### ISSUE THREAD

**Issue by Finnepinnen** [ibell/coolprop#257]
Hi,

when evaluating EoS in a point on the envelope the following error occurs:
Warning: PQ: 

Thesis: It only happens with refrigerants having temperature glide.

<-- Example in MatLab R2014b -->

import CoolProp.*;

Temp_Cond = 313.15;

% For refrigerant R22
Ref_1 = CoolProp.AbstractState.factory('REFPROP', 'R22');

Ref_1.update(CoolProp.QT_INPUTS, 1, Temp_Cond);
p_31 = Ref_1.p();

Ref_1.update(CoolProp.PQ_INPUTS, p_31, 0);

% For refrigerant R407C
Ref_2 = CoolProp.AbstractState.factory('REFPROP', 'R407C');

Ref_2.update(CoolProp.QT_INPUTS, 1, Temp_Cond);
p_32 = Ref_2.p();

% This works
Ref_2.update(CoolProp.PQ_INPUTS, p_32, 1e-10);

% This doesn't work
Ref_2.update(CoolProp.PQ_INPUTS, p_32, 1e-11);

% Neither does this
Ref_2.update(CoolProp.PQ_INPUTS, p_32, 0); 

<-- End of example -->

Best regards
/Peter

**Comment by jowr** [comment]
Hi Peter, this is the wrong repository. Could you please repost at https://github.com/CoolProp/CoolProp? Thanks.
