### ISSUE TITLE
Missing CoolProp DLL in LabVIEW folder or ducumentation needed

### ISSUE THREAD

**Issue by bachc** [ibell/coolprop#259]
The documentation on https://github.com/ibell/coolprop/tree/master/wrappers/Labview
states:
## To Install
1. Copy the files CoolProp.vi, Coolprop.llb and CoolProp.dll from this folder to somewhere you want
2. ...

Unfortunately the CoolProp.dll file is not in that folder and compiling the dll seems to be a bit tedious for "normal" users.

**Comment by ibell** [comment]
These are the issues for v4.2.5, please open an issue here: https://github.com/CoolProp/CoolProp/issues

**Comment by bachc** [comment]
Done. Thanks!
