### ISSUE TITLE
PropsSImulti in Python

### ISSUE THREAD

**Issue by VAL333** [ibell/coolprop#261]
Hi @jowr,

The PropsSImulti seems increadibly useful and I would really need it for my project. However, I cannot use it in python and I believe the reason is that there is no wrapper to use it in python. Would it be possible (and relatively quick) to implement the wrapper so that PropsSImulti can be used in python?

Thank you very much.

**Comment by ibell** [comment]
Sure we can do that.  Can you please open an issue to that effect?  We wrap
most of PropsSImulti functionality into PropsSI, but we could expose
PropsSImulti directly.

**Comment by jowr** [comment]
I also think that we have most of this functionality already, but would you mind opening an issue at https://github.com/CoolProp/CoolProp instead and close this one?

**Comment by jowr** [comment]
Here is an example:

``` Python
import numpy as np
import CoolProp.CoolProp as CP
fluid = "HEOS::Water"
out_lst = ["H","S"]
in1_lst = np.array([150,220])+273.15
in2_lst = np.array([0.1,0.5])*1e5
CP.PropsSI(out_lst,"T",in1_lst,"P",in2_lst,fluid)
```

yields

``` Python
array([[ 2783039.45842859,     8689.22188195],
         2916990.17161347,     8240.36378027]])
```

**Comment by ibell** [comment]
I think the issue is being able to also pass mole fractions as vector.
Otherwise vectorization in thermo Props is as you say.

**Comment by VAL333** [comment]
Thank you very much. I agree with ibell. The example given above doesn't specify the mole or mass fraction of each fluid. Also, can you use this functionality with gases?

The issue was submitted at https://github.com/CoolProp/CoolProp issue #848.
