### ISSUE TITLE
bubble/dew densities

### ISSUE THREAD

**Issue by adex987** [ibell/coolprop#262]
I just start using Coolprop, matlab wrapper. I have difficulties defining dew and bubble properties such as density, specific heat, etc.

Example:
I defined, CoolProp.PropsSI('D', 'P', p, 'Q', 0, 'Water') for saturated liquid density and it works, but for bubble density I defined CoolProp.PropsSI('dl', 'P', p, 'Q', 0, 'Water'), didn't work.

The saturated liquid/vapor properties are different from bubble/dew.
can you help me? Thank you,

**Comment by jowr** [comment]
Please see my comment to #197 .

``` MATLAB
presure = CoolProp.PropsSI('P', 'T', 373, 'Q', 0, 'Water')
dl = CoolProp.PropsSI('D', 'P', presure, 'Q', 0, 'Water')
dv = CoolProp.PropsSI('D', 'P', presure, 'Q', 1, 'Water')
```

**Comment by thorade** [comment]
@jowr maybe you want to move your answer to the identical issue in the current repo:
https://github.com/CoolProp/CoolProp/issues/908

@adex987 The issue tracker is mainly for bugs in the source code, 
if you just have a question on how to use the software, you should better ask it on the CoolProp users mailing list: https://groups.google.com/forum/#!forum/coolprop-users
