### ISSUE TITLE
cannot compile with visual studio 14

### ISSUE THREAD

**Issue by chchen85** [ibell/coolprop#265]
When it is compiling with visual studio after CMake, it's keep saying that cannot open the head file "fmt/format.h", "all_cubics_JSON.h" ,  'Eigen/Core', and several other head files. Can give help to give some comments? Thank you.

**Comment by ibell** [comment]
Sorry, but you have filed an issue for version 4, which is no longer under development.  Please file an issue here: https://github.com/CoolProp/CoolProp/issues and provide much more detail about what you have done.  It's not possible to debug your issue as it stands.

**Comment by ibell** [comment]
Sorry, but you have filed an issue for version 4, which is no longer under
development.  Please file an issue here:
https://github.com/CoolProp/CoolProp/issues and provide much more detail
about what you have done.  It's not possible to debug your issue as it
stands.
