### ISSUE TITLE
TTSE functioning

### ISSUE THREAD

**Issue by kaern** [ibell/coolprop#31]
All of a sudden, for some reason, I can't get TTSE to work. Can somebody validate its results..?

**Comment by ibell** [comment]
Perhaps I broke something :/ Can you tell me what has broken?  Do you get
an error message?

**Comment by ibell** [comment]
Try deleting the TTSE data maybe

**Comment by kaern** [comment]
I am not in front of my laptop now, but i got constant values totally out of range when expecting phase transition... I am not sure how to delete the TTSE data...

**Comment by jowr** [comment]
I'll check with Martin tomorrow...

**Comment by ibell** [comment]
Any update here?

**Comment by jowr** [comment]
No updates, it does not work and I cannot figure out why...

## 

Jorrit Wronski
DTU Mechanical Engineering

Technical University of Denmark
Department of Mechanical Engineering
Nils Koppels Allé
Building 403 Room 111
2800 Kgs. Lyngby

phone: +45 45 25 41 83
email: jowr@mek.dtu.dk
http://www.tes.mek.dtu.dk/English

**Comment by ibell** [comment]
Can you give me a point that fails?  I am using TTSE right now, seems ok by
me.  Try updating the TTSERev macro in TTSE.cpp?  That should force it to
rebuild the tables.

Ian

**Comment by jowr** [comment]
Hmmm, the latest master revision works for me...

**Comment by kaern** [comment]
Hi again,

Now I learned how to delete the table data, and I see the new one is not created, that means the TTSE functioning is still not working???

**Comment by ibell** [comment]
You are using modelica, right?  I seem to recall that @jowr had a
similar problem at one point.  He says the master version of CoolProp
works fine with TTSE.  And for me it works fine too.

**Comment by kaern** [comment]
I tried to use TTSE in python and it works. The Modelica wrapper does not work however.

**Comment by ibell** [comment]
I'm going to have to pass off to @jowr then

**Comment by kaern** [comment]
Hi again,

Now I went through the revisions made. I found that revision 

Secant obeys the maxiter parameter (e0caf83927e130a34d7725253e7c15a6e9aa19a4)

works, but 

Improvements to solvers at low pressure/temperature (4514f657be6966afe0e2660ea8f76e73f5752184)

does not.. While looking at the code in above revision "Improvements to solvers at low pressure/temperature" I cannot understand what should influence the lib file and TTSE? 

Of course I can try to delete each line of the revision, to find what makes the error, but maybe some of you can see any problem?

**Comment by ibell** [comment]
What fluid are you using?  There are some seriously unpleasant numerical
problems at low pressure/ temperature for quite a few fluids.

Ian

**Comment by kaern** [comment]
Good call, I see now the propane (which worked in python) does also work in Modelica, but water does not..
I will try look deeper into what line causes the error..

**Comment by kaern** [comment]
It seems to be the line: 
-        Tsat = Secant(&SPGR,Tsat,1e-4,1e-7,50,&errstr);
-        Tsat = Secant(&SPGR,Tsat,1e-2*Tsat,1e-8,50,&errstr); 

I will try to use newest revision at change this line..

**Comment by ibell** [comment]
Which one works?  The tolerance of 1e-8 might be problematic I guess.  At
some point I want to figure out a more robust method for low pressure.  So
many nasty numerical problems = Many nights of lost sleep.

**Comment by kaern** [comment]
Hi again, I was wrong first, sorry.. the above line works in newest revision..

I found the error to be the line:
-    while (fabs(error) > 1e-10 && fabs(change/rho)>DBL_EPSILON*10)
-   while (fabs(error) > 1e-10 && fabs(change)>1e-10) 
  which I changed back to the previous..

I don't know what exactly happens in this line, but you may want to optimize it..?
And now you can close this issue..

**Comment by ibell** [comment]
Sorry, can you confirm that everything works ok with code in master? If so,
feel free to close the ticket
