### ISSUE TITLE
Support Secondary Working Fluids in CoolPropStateClass

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#32]
This is going to be annoying, but very useful, especially for me and my uses in ACHP and elsewhere.

**Comment by jowr** [comment]
The coming implementation of Brines will be prepared for that... This feature is on my list as well ;-)

**Comment by ibell** [comment]
Excellent.  Do you have any idea of an estimated time that this might be
ready?

**Comment by jowr** [comment]
No idea, the basic structure is almost done (see branch), but I still lack the integration with the State class...

**Comment by jowr** [comment]
As agreed on this week, @ibell now owns this issue. Congrats!

**Comment by ibell** [comment]
I'll hack away - should be ready-ish soon

**Comment by jowr** [comment]
@ibell: Would be nice to get some feedback on the new class structure before you use your time on the state class. https://github.com/ibell/coolprop/tree/brines_solutions

**Comment by ibell** [comment]
I'll take a look tonight - have some work to do today.

Ian
