### ISSUE TITLE
Removal/Modification of titles from property plots

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#34]
The titles are sometimes nice, but for cases like this, I would prefer that they be removed.  In general, perhaps just put the fluid name?  From the axis labels it should be clear what is being plotted, right?

![figure_1](https://f.cloud.github.com/assets/1859947/1199897/b6c14d16-251a-11e3-851f-3efedb465d85.png)

**Comment by lgpage** [comment]
Oh wow that is a mess :)
Can you post the source for this example.

**Comment by ibell** [comment]
```
from CoolProp.Plots import PropsPlot
PP = PropsPlot('REFPROP-MIX:R32[0.47319469]&R125[0.2051091]&R134a[0.32169621]','TD')
PP.show()
```

**Comment by lgpage** [comment]
I get the following error for this example:
`ValueError: CoolProp error: Could not load librefprop.so, make sure it is in your system search path.`

Not sure why, or if I did something wrong.

**Comment by lgpage** [comment]
Added a title filter for `REFPROP-MIX` fluids (0c8f734c92d3121d09657ac8bbf5c6768e2d1cd6)

**Comment by ibell** [comment]
@lgpage You got that error because REFPROP is not installed (or installed improperly).

Can we close this ticket?

**Comment by lgpage** [comment]
That would make sense.
Out of interest is there a Coolprops equivalent that doesn't use REFPROP ?

**Comment by ibell** [comment]
Ask me again in a few months when we have mixtures working, but for now,
no, this should only be a problem with this REFPROP. In general my
preference is to have the default behavior be x- and y-axis labels and no
title
