### ISSUE TITLE
Brines I

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#45]
Move old brine and solution data to new object structure.

**Comment by jowr** [comment]
@ibell : Can anyone help me understand the coefficients for the freezing point calculations? Why are there non-zero coefficients that are multiplied with the current temperature? The freezing should only depend on concentration, shouldn't it?

**Comment by ibell** [comment]
Not sure, Ill send you spreadsheet when I get home in 30 mins so you
can check the values.

**Comment by jowr** [comment]
Problems solved and old fluids ported to new structure. 

The only question that remains is: What is HC-10 line 350 in Brine.cpp? It looks like a home-made fit by @ibell, but which name and description should the fluid get?

**Comment by jowr** [comment]
OK, I assume it is Dynalene HC-10. I will just remove it from the solutions since it is a normal heat transfer fluid.
