### ISSUE TITLE
Brines II

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#46]
Include all fluids from SecCool software.

**Comment by jowr** [comment]
Removed from v4.0, I currently do not have the time.

**Comment by jowr** [comment]
- [x] Slurry ice (3x)
- [x] ZitrecAC
- [x] Potassium formate/Sodiumpropionate (Zitrec S10 to S55)
- [x] Potassium acetate/Potassium formate (Aspen Temper -10 to -55 and Pekasol)

**Comment by ibell** [comment]
Isn't ammonia water already included from Melinder?

**Comment by ibell** [comment]
BTW, that checklist is very cool

**Comment by jowr** [comment]
You're right, updated.

**Comment by ibell** [comment]
@jowr , can you include these last two brines so that we can close out this issue?

**Comment by jowr** [comment]
@ibell, we are talking eleven fluids here, but let me see if I can do it later tonight.

**Comment by ibell** [comment]
Ah sorry, I thought it was just two left.  Whenever you have a moment
that would be great!  If you see other issues that are quick fixes,
lets close them out.

**Comment by jowr** [comment]
Added in 41416acc7c7f6ff7a6304067daa0707a9462deee

**Comment by ibell** [comment]
Bueno!
