### ISSUE TITLE
Brines III

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#47]
Include Lithium-Bromide solution properties from:
http://www.sciencedirect.com/science/article/pii/S0140700700000396

Wouldn't it be nice with some absorption chiller calculations in the examples?

**Comment by ibell** [comment]
Yes, yes it would.  That would be awesome.  One step at a time :)

**Comment by jowr** [comment]
I changed my mind. This article seems to be more like what we need: http://dx.doi.org/10.1016/j.ijrefrig.2005.10.007

The authors were so kind to provide some source code, should be straight forward to implement.

**Comment by jowr** [comment]
Removed from v4.0, I currently do not have the time.

**Comment by jowr** [comment]
Done.
