### ISSUE TITLE
Modelica wrapper

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#48]
Clean up the Modelica code to make it standard-compliant. @ibell: What was the compiler switch for Dymola again?

Who wants to do that?

**Comment by squoilin** [comment]
I can take that

**Comment by ibell** [comment]
So I'd like to ask a bigger question - should we keep our wrapper or just
bake everything into ExternalMedia?

**Comment by ibell** [comment]
And push the improvements we have made to CoolProp2Modelica into
ExternalMedia?

**Comment by jowr** [comment]
As far as it's C++, I think everything should be merged. However, we have to solve this one first: https://github.com/ibell/coolprop/issues/4

**Comment by squoilin** [comment]
We should move to externalmedia asap. Do we have the proper rights on the repository now?

I will list the successive modifications we made to coolprop2modelica and see how compatible they are with the actual version of externalmedia.

In the meantime, we can keep bringing modifications to coolprop2modelica.

Ian, could you go in my office, create an administrative account for jorrit on the server, and start a few instances of dymola on his session, so that he can test #48 . Remote access must be activated after the user has been created.

**Comment by ibell** [comment]
The c++ part has been pushed to ExternalMedia, I havent tested it yet, but
it compiles ok, you can get the code (read-only) from
https://github.com/modelica/ExternalMedia, but I can push to svn now as
well.  You should both request access to the svn repo in order to push your
changes

**Comment by ibell** [comment]
@squoilin which compiler flags are you talking about?  For VS? Or GCC?

**Comment by ibell** [comment]
And @squoilin , I will get Jorrit onto the server tomorrow.

**Comment by jowr** [comment]
@ibell: I meant the options to turn on Modelica standard compatibility checks in Dymola.

**Comment by ibell** [comment]
Ah right, you know where to turn on the pedantic check?  Its in the solver options window

**Comment by thorade** [comment]
You can also turn on/off the pedantic check using the flag `Advanced.PedanticModelica=true`  in the command window, as described here: http://stackoverflow.com/q/17276571/874701
You should also try the `Hidden.PrintFailureToDifferentiate=true` flag, it will show you where numerical Jacobians are introduced.

**Comment by jowr** [comment]
Thanks Matthis!

**Comment by jowr** [comment]
OK, I did not check the numerical Jacobians, but the code seems to be standard compliant now. I get only one error and that is in the "test" package due to a missing reference to TILMedia, which I do not have. 

Moved this from beta to v2014 hope to check the numerical Jacobians soon.

**Comment by jowr** [comment]
We moved to ExternalMedia, outdated.
