### ISSUE TITLE
Plots are broken

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#5]
When I try to run the normal ph or hs plots, I get the following error::

```
>pythonw -u "Plots.py"
Traceback (most recent call last):
  File "Plots.py", line 834, in <module>
    hs('R245fa', show = True)
  File "Plots.py", line 708, in hs
    drawLines(Ref,lines,ax)
  File "Plots.py", line 160, in drawLines
    'bubble' in str(lines[0]['label']).lower() 
KeyError: 'label'
```

**Comment by jowr** [comment]
Yes, looks like I broke something. I'll fix it asap.
Jorrit

ibell notifications@github.com wrote:

When I try to run the normal ph or hs plots, I get the following error::

**Comment by ibell** [comment]
Thanks.

**Comment by jowr** [comment]
Should be fixed.
