### ISSUE TITLE
Improved documentation for new plotting functionality

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#51]
Hey @lgpage, @jowr et al., we are preparing to release CoolProp 4.0 in early November and I was hoping that you might have a moment to add some examples of how to use your new plotting functionality to the documentation.  It would be great to have a page that covers all the options available and shows examples.  We have docs for the API interface but I'd like a bit more.

**Comment by lgpage** [comment]
Cool will do... these examples go in the `Web/examples/examples.rst` file right

**Comment by ibell** [comment]
Could do, my idea was a teaser with one or two nice examples, then a link
pointing over to a new page of docs on plots, showing off all the features,
pitfalls, dangers, possibilities, etc., which would be something like
Web/examples/plotting.rst or something like that

**Comment by lgpage** [comment]
Cool I'll start putting together a `Web/examples/plotting.rst` file with the examples

**Comment by ibell** [comment]
Awesome, looking forward to seeing them! Have you played around with
building the docs before using sphinx?

Ian

**Comment by lgpage** [comment]
I've only played around with using Epydoc, but I'll look into using sphinx.

**Comment by ibell** [comment]
It's not too painful, you can start by copy-pasting the current examples
from the examples page and hacking away - that's how I taught myself

**Comment by ibell** [comment]
@lgpage Your branch looks excellent

One small comment, I prefer if you don't use plt as the name of the instance of your PropsPlot as it is standard to do

```
import matplotlib.pyplot as plt
```

which would over-write this import.

Also, there is some missing text in the warning (see below).  Apart from that, I'm ready to pull and close this issue

Missing text:

![clipboard01](https://f.cloud.github.com/assets/1859947/1359304/0fbd7418-37da-11e3-822d-b841c9343b4e.png)

**Comment by lgpage** [comment]
I'll update the docs and change `plt` to something else.
The missing text is what I am going to finish up today, ran out of time yesterday

**Comment by ibell** [comment]
No problem, it looks excellent otherwise.  One other thing regards the
subplots at the bottom - it's a bit weird to have the last plot in the
bottom right, but that's me being pedantic.

**Comment by lgpage** [comment]
Following changes where made:
- `plt` name changed
- finished missing text
- fixed location of the last subplot
- merged with master 5eade09330425581b4cb17e33272f595e15abcc5

**Comment by ibell** [comment]
_Que bueno_ - want to make a pull request and I'll accept it?  Also, can you tidy up the branches you made on github?  There are a few floating around...

**Comment by lgpage** [comment]
I have already merged these changes into the master branch.
I will tidy up the other branches as well :D

**Comment by ibell** [comment]
Excellent. Closed.
