### ISSUE TITLE
calculate derivative (∂²p/∂ρ²)_s

### ISSUE THREAD

**Issue by thorade** [ibell/coolprop#52]
If at some point you do not know what else to implement, you could add the derivative (∂²p/∂ρ²)<sub>s</sub> or (∂²p/∂v²)<sub>s</sub> which is used to calculate other properties e.g. in these papers:
- http://dx.doi.org/10.1016/j.fluid.2009.07.021
- http://dx.doi.org/10.1063/1.2759533
- http://dx.doi.org/10.1016/j.fluid.2012.09.017

**Comment by ibell** [comment]
I know those guys at Delft, I'm firewalled right now but Ill take a look on
Friday.  Also, no one is stopping you if you wanted to make the changes
yourself :) .  It should be added to the CoolPropStateClassSI class in
CPState.h/cpp, and a unit conversion overload in CoolPropStateClass.

Ian

**Comment by ibell** [comment]
@thorade , Want to do this?  We could add it to 4.0

**Comment by thorade** [comment]
As a very first step, here is how to rewrite derivatives with respect to density/volume:

![gasdynamics_dp2-dv2-t](https://f.cloud.github.com/assets/314571/1461016/c1a963f6-4489-11e3-80b5-bbccc579ac71.png)

and analogously also

![gasdynamics_dp2-dv2-s](https://f.cloud.github.com/assets/314571/1461026/cb7aedf8-448b-11e3-8795-96c16bc2c72a.png)

I'll try to find time to add these derivatives, but maybe it will have to wait till I finish my thesis.

**Comment by ibell** [comment]
They just aren't very nice derivatives.  I think I can do it, it shouldn't
be too awful, I've done similar things before...  Its just not a priority
for me in my research

**Comment by thorade** [comment]
Same for me, I have already written them down on paper, but it is quite lengthy and I do not currently need these. I just saw them in these papers and thought they might be nice to have for people researching ORCs.

**Comment by ibell** [comment]
I agree.  If you can formulate the derivatives in terms of things that are
already coded in the state class (
http://coolprop.sourceforge.net/_static/doxygen/html/class_cool_prop_state_class_s_i.html)
it would be very little work for me to take the remaining steps

Ian

**Comment by thorade** [comment]
![gasdynamics_transform](https://f.cloud.github.com/assets/314571/1461687/0beb1358-44c4-11e3-97c0-1164ae933094.png)

Here is an expression in terms of existing functions, might be shortened a little bit more using 
(∂s/∂ρ)<sub>T</sub> = -1/ρ² (∂p/∂T)<sub>ρ</sub> . 
Probably there are substantialy shorter expressions possible, but I currently do not see how to get there.
A pdf with intermediate steps is here: https://github.com/thorade/HelmholtzMedia/blob/master/Extras/LaTeX/tables/GasDynamics_Standalone.pdf

**Comment by ibell** [comment]
Also see http://www.google.be/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0CDgQFjAB&url=http%3A%2F%2Frepository.tudelft.nl%2Fassets%2Fuuid%3A1fcb4772-a453-4c5a-b94c-c6a93c8cb6c2%2FColonna_2007.pdf&ei=DdByUovaGarS0QXFt4Fo&usg=AFQjCNH_DKZq0xJpUZtn2P7jF4RABK93ig&sig2=kJ9-yaCaU1SoUTCJvhpRlw&bvm=bv.55819444,d.d2k&cad=rja

**Comment by ibell** [comment]
Added in revision 60e6a3e2c16b2dcb50fccb099991794dd82c9d8b

**Comment by thorade** [comment]
Two notes to myself:
http://www.wolframalpha.com/input/?i=derivative+of+a%28x%29-b%28x%29*b%28x%29%2Fd%28x%29
http://www.wolframalpha.com/input/?i=derivative+of+a%28x%29-b%28x%29*c%28x%29%2Fd%28x%29
http://www.wolframalpha.com/input/?i=derivative+of+-1%2Fx^2*f%28x%29
Using the expanded form.
In Matlab symbolic toolbox, there is also the command `expand`

**Comment by ibell** [comment]
There's also sympy (http://sympy.org/en/index.html), they have an online
thingy too which is awesome

**Comment by thorade** [comment]
OK, I do now have three different ways of calculating these derivatives and all return the same values and also the same value as in the Colonna paper, table 2.
For debugging, here is a table with some values for Propane, with EoS from Lemmon http://dx.doi.org/10.1021/je900217v 
The saturation pressure of propane at 298.15 K is 952074.52 Pa.
The saturation pressure of propane at 0.93*Tc (343.9977 K) is 2629921.8 Pa.

<table>
    <tr>
        <th>T in K</th>
        <th>p in Pa</th>
        <th>(∂²p/∂ρ²)<sub>s</sub></th>
        <th>(∂²p/∂v²)<sub>s</sub></th>
        <th>fundamental derivative of gasdynamics</th>
    </tr>
    <tr>
        <td>298.15</td>
        <td>101325</td>
        <td>3284.18</td>
        <td>797236</td>
        <td>1.04866</td>
    </tr>
    <tr>
        <td>343.9977</td>
        <td>2629921.0</td>
        <td>-169.371</td>
        <td>1.56338e+010</td>
        <td>0.834887</td>
    </tr>
</table>

**Comment by ibell** [comment]
I get 0.819526851026 for the fundamental derivative at 343.9977 K which
agrees with Colonna of 0.82.  I also get (∂²p/∂v²)s to be equal to
15346165273.570604

**Comment by ibell** [comment]
At 298.15 K /101325 Pa, I get completely different solution, second partial with volume equal to 127223.04620506837 and 0.16734608712500065 for the fundamental derivative

**Comment by thorade** [comment]
But which EoS are you using for propane?
I'll add another table for n-Butane using the Bücker-Wagner EoS: http://dx.doi.org/10.1063/1.1901687

**Comment by ibell** [comment]
Im using Lemmon

**Comment by thorade** [comment]
For n-Butane, using the Bücker-Wagner EoS: http://dx.doi.org/10.1063/1.1901687

<table>
    <tr>
        <th>T in K</th>
        <th>p in Pa</th>
        <th>(∂²p/∂ρ²)<sub>s</sub></th>
        <th>(∂²p/∂v²)<sub>s</sub></th>
        <th>fundamental derivative of gasdynamics</th>
    </tr>
    <tr>
        <td>298.15</td>
        <td>101325</td>
        <td>862.173</td>
        <td>1.33302e+006</td>
        <td>1.02383</td>
    </tr>
    <tr>
        <td>403.86875</td>
        <td>2666889</td>
        <td>-174.731</td>
        <td>1.61759e+010</td>
        <td>0.68654</td>
    </tr>
</table>

**Comment by thorade** [comment]
Do you have FluidProp installed? Does the regular version calculate the FDG?

**Comment by ibell** [comment]
Nope I do not have FluidProp installed, but I am pretty sure it doesn't
calculate the FDG.  Any further insight on the derivatives we were looking
at before?  It would have been nice if they had provided one or two points
for validation...

**Comment by ibell** [comment]
I could also email one of their students as well.  Might be the easiest.

**Comment by thorade** [comment]
Nannan from the Colonna-FluidProp group has a publication that calculates the FDG in terms of derivatives wrt density: http://dx.doi.org/10.1016/j.fluid.2012.09.017 while in the other publication http://dx.doi.org/10.1016/j.fluid.2009.11.003 they used derivatives wrt to volume. The Nannan formulation uses only terms that are already implemented in CoolProp and can be used directly.

Also, comparison of the two formulations shows that
![gasdynamics_dp2-dv2-t short](https://f.cloud.github.com/assets/314571/1473858/9e4e425a-4623-11e3-96e3-c27639e99834.png)

**Comment by ibell** [comment]
Nice, they end up with different derivatives than I did...

**Comment by ibell** [comment]
Seems like you were right about how to calculate d2pdv2_T, I think its the
same as what you told me before.  I have a few things to do, but I'll check
this evening.

**Comment by ibell** [comment]
Ok, it works with the new derivatives.  You were spot on about the derivatives.  I still am a bit confused, but I think it makes sense.  You just can't do what I did as it is not mathematically consistent evidently.

Issue closed. Will be available in 4.0 through DerivTerms

**Comment by thorade** [comment]
Thanks for the fixes. BTW, not one of the formulas I posted was correct in the first version, I corrected each one afterwards.

**Comment by ibell** [comment]
But you had the principles correct at least.  They never did properly teach
me partial derivatives in my math classes I have taken so far
