### ISSUE TITLE
Polish work and integration of FLUENT wrapper (and OpenFOAM?)

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#54]
@lgpage We put together a wrapper of Coolprop for FLUENT, I think I remember seeing you were doing stuff with OpenFOAM.  Want to help me build/test a wrapper for CoolProp for OpenFOAM?

**Comment by lgpage** [comment]
Yeah that would be awesome... I've thought about this a few time... also
got 1 or 2 students at the university that would benefit from this.

**Comment by ibell** [comment]
Maybe we can all work together on this?  It wasn't too painful to get it
working for FLUENT, took just two hours to get a simple example working.
Is there a mailing list for OpenFOAM?

**Comment by lgpage** [comment]
OpenFoam itself does not have a mailing list as far as I know. However the extend OpenFoam project would probably be the best place  (http://www.extend-project.de/community-organisation/21/69/view/article) or the cfd-online forums (http://www.cfd-online.com/Forums/openfoam-programming-development/)

A few thoughts on this from my side:
- We might have to look at maintaining version specific wrappers, depending on how much OpenFoam's API changes from version to version
- The easiest might be to create a OpenFoam Thermophysical class that wraps the functionality on CoolProp

**Comment by Rod-Persky** [comment]
Has there been any progress on the OpenFoam thermophysical class, or does has anyone had experience writing such a class? I'm looking at gettting real gas properties into OF 2.2.2

**Comment by ibell** [comment]
Logan,

I certainly haven't played with it, and I have had no direct contact about
OpenFOAM.  Happy to work on this, but no idea how to proceed

**Comment by ibell** [comment]
I think this issue should be closed for now.  If we can find someone that uses openFOAM, I'd be happy to revisit this ticket.

**Comment by davideziviani** [comment]
@ibell, a colleague of mine @nicola1312199 and I are working on a project to get the my single-screw expander simulated using openFOAM. As we are using refrigerants, I though this ticket could be reopened.

I know you get CoolProp to work with Fluent. Any general guidelines on how to couple it with openFOAM. If you can help him out with the general todo list, I think we should manage to create a wrapper.

**Comment by ibell** [comment]
I can't really do much with CoolProp now, but you guys are MORE than welcome to have a go at it.  I have no idea what the interface looks like for OpenFOAM, but I do know it is C++, so that should make the integration process relatively easy.
