### ISSUE TITLE
Frozen point (% etylhene glycol / % propylène glycol + Water)

### ISSUE THREAD

**Issue by ghost** [ibell/coolprop#55]
hello,

how can I calculate the the frozen point of a mixing water+glycol (ethylene glycol / propylene glycol), in function of the % (in mass) of glycol ?

Sincerely,
PY

**Comment by ibell** [comment]
Hi PY,

Its not perfect, and will improve in 4.0, but for now you can do:

```
>>> import CoolProp
>>> CoolProp.CoolProp.Props('F','T',300,'P',101,'EG-5%')
271.5671979698416
>>> CoolProp.CoolProp.Props('F','T',300,'P',101,'EG-30%')
258.5742179531783
```

where the inputs for T and P are ignored and you set the concentration using the string.
