### ISSUE TITLE
Python plotting

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#66]
Hi,
thank you for an improved plotting package! I currently convert my code to use the new functions and the following ideas came to my mind:
1. Unified approach to parameter handling: I think all functions should follow the structure of the most popular one, Props. Hence, functions like `_get_fluid_data(self, req_prop, prop1_name, prop2_name, prop1_vals, prop2_vals)` should rather be `_get_fluid_data(self, req_prop, prop1_name, prop1_vals, prop2_name, prop2_vals)`
2. `numpy` compatibility. In my opinion it is important to allow numpy arrays as inputs. Some of the new functions do only work with common lists and fail if fed with numpy objects. Furthermore, I suggest to return numpy arrays asm well. I heavily use the operator overloading for `+, -, *, /` and that requires numpy objects.

Please let me know what you think. These are suggestions, feel free to disagree and share your concerns.

**Comment by lgpage** [comment]
I agree 100% with these suggestions and as a general rule I try to allow for numpy arrray inputs were possible, I just haven't had the time to check this yet. 
I'll look into implementing them either today or Sunday.

**Comment by jowr** [comment]
Great, let me know if you could use a hand implementing things.

**Comment by ibell** [comment]
Either of you have an estimate for time frame?  I'm inclined to release
4.0beta as is now... And then release 4.0 proper in a week or so. @jowr
@lgpage Do you have anything to add to the changelog that I've missed
(Web/changelog.rst)?

**Comment by jowr** [comment]
Added incompressibles to change log, remove them if you think they shouldn't be mentioned (I'm kind of undecided...).

**Comment by ibell** [comment]
I'd rather they be there so it is as clear as possible what we have changed.

**Comment by ibell** [comment]
@lgpage @jowr I'm ready to release 4.0, what is the status of this issue?

**Comment by jowr** [comment]
I don't know. I can see that @lgpage works on something, but I did not compare the branches. Logan, please let us know if we can help with anything here.

**Comment by lgpage** [comment]
@jowr @ibell I apologize for my absence lately, my plate has been rather full.
I am working on this at the moment.
I have sorted out the Unified approach to parameter handling and I'm busy working on the `numpy` compatibility for the plot functions.

**Comment by jowr** [comment]
Great! Happy coding. :-)

**Comment by lgpage** [comment]
@jowr please check branch `fix_66`.
A only found a few functions that needed changing to allow for `numpy` compatibility.
Please let me know if I missed any.

**Comment by jowr** [comment]
Should be fine after 6996d7662cdbda94eca4e2c5a48decf7c707fb0e
