### ISSUE TITLE
R407c and TTSE enters an infinite loop

### ISSUE THREAD

**Issue by squoilin** [ibell/coolprop#69]
From Modelica, when calling R407c|enable_TTSE=1, Coolprop keeps building the tables in an infinite loop.

From C++, the following does not give any answer:
TwoPhaseMedium_setState_ph_(8e5, 4E5, 2, pointer, "R407c", "CoolProp", "R407c|enable_TTSE=1");

From C++, the following also ends up in an infinite loop:
TwoPhaseMedium_setState_ph_(8e5, 4E5, 2, pointer, "R245fa", "CoolProp", "R245fa|enable_TTSE=1");

Looks like these are several problems, but I don't have time to isolate them right now.

**Comment by ibell** [comment]
I think, if I am not mistaken, that you can't use TTSE with pseudo-pure.
 Ill have a look this evening.

**Comment by ibell** [comment]
Does this work now?  If so, please close this ticket.

**Comment by jowr** [comment]
Works for me in Python, haven't checked C++ though.

```
import CoolProp.CoolProp as CP
CP.enable_TTSE_LUT('R407c')
CP.Props('D','H',800,'P',400,'R407c')

0.05 to build both two phase tables
0.93 to build single phase table with p,h
1.92 to build single phase table for T,rho
write time: 0.13

6.557865616029696

CP.enable_TTSE_LUT('R245fa')
CP.Props('D','H',800,'P',400,'R245fa')

0.05 to build both two phase tables
0.58 to build single phase table with p,h
10.47 to build single phase table for T,rho
write time: 0.03

10.331465817517245
```

**Comment by ibell** [comment]
I think it works, I'm closing it, @squoilin you can open it back up if the problem still exists for you.
