### ISSUE TITLE
DerivTerms in python crashes without warning

### ISSUE THREAD

**Issue by Rod-Persky** [ibell/coolprop#71]
Hi,

There seems to be an issue using CoolProp.CoolProp.DerivTerms, looking at the C code it seems that it is expecting a Fluid not a name - I'm not sure what magic goes on in cython.

``` python
print(CoolProp.__version__)
        rho = Props('D', 'T', 240, 'P', 55000, self.fluid.CPName)
        print("DerivTerms({}, {}, {}, {}) = ".format('dpdrho', 240, rho, self.fluid.CPName), end="")
        print(DerivTerms('dpdrho', 240, rho, self.fluid.CPName))
        print("Done")
```

``` idle
>>> ================================ RESTART ================================
>>> 
4.0.0beta
DerivTerms(dpdrho, 240, 2.885906015809144, R134a) = 
>>> ================================ RESTART ================================
```

This is on Python 3.3.2 (v3.3.2:d047928ae3f6, May 16 2013, 00:03:43) [MSC v.1600 32 bit (Intel)] on win32

**Comment by jowr** [comment]
Hi, 
this code works fine for me:

```
import CoolProp
from CoolProp.CoolProp import Props,DerivTerms
CPName = "n-Pentane"
print(CoolProp.__version__)
rho = Props('D', 'T', 240, 'P', 55000, CPName)
print(DerivTerms('dpdrho', 240, rho, CPName))
print("Done")
```

gives 

```
4.0.0beta
1953.26598847
Done
```

**Comment by ibell** [comment]
It is also overloaded in CoolPropDLL.h :
https://github.com/ibell/coolprop/blob/master/CoolProp/CoolPropDLL.h#L52 to
take in a string

**Comment by ibell** [comment]
Works fine in C++ too:

![clipboard01](https://f.cloud.github.com/assets/1859947/1531082/8b1a9bf4-4c5c-11e3-86a5-26e9ec2c279f.png)

**Comment by ibell** [comment]
Ah, maybe its a python 3.x issue

**Comment by ibell** [comment]
Yup, its a 3.x issue, have to figure out why it crashes ( I can duplicate this behavior)

**Comment by ibell** [comment]
Fixed (?) in rev 373a75fb5d646dcac9f81af69306554257aa27aa  - lunch time

**Comment by Rod-Persky** [comment]
Works, Awesome! I should have an interesting python and c++ example in making a RGP file for ANSYS CFX

**Comment by ibell** [comment]
Whats an RGP?  Is it like a user-defined-function?

**Comment by Rod-Persky** [comment]
It's a computed table of fluid properties, where RGP = 'Real Gas Properties'. There is no program around (that I know of) which can compute these tables, so this is probably pretty helpful for people trying to generate them. 

Information about the file is in mod_cfx 12.7 ish.

```
https://support.ansys.com/portal/site/AnsysCustomerPortal/template.MAXIMIZE/menuitem.2884af70ee553994a6f26c10639c97a0/?javax.portlet.tpst=79fa7a6e32edb10c85fbb010639c97a0_ws_MX&javax.portlet.prp_79fa7a6e32edb10c85fbb010639c97a0=wcproxyurl%3Dhttp%25253A%25252F%25252Fcancmsapp6%25253A8080%25252Fcpstaticassets%25252Fprod_docu%25252F14.5%25252Fhtml%25252Fcfx_mod%25252FcfxRealRealOrga.html%26viewID%3Dproxy_view_secondary&javax.portlet.begCacheTok=com.vignette.cachetoken&javax.portlet.endCacheTok=com.vignette.cachetoken
```

Part of it looks like:

![image](https://f.cloud.github.com/assets/770327/1531378/8c15b5f0-4c63-11e3-85ca-ed0ec487148a.png)

**Comment by ibell** [comment]
I also worked with some researchers at UGent to build a UDF function in
Fluent that called CoolProp. I can send it to you if you are interested.

**Comment by Rod-Persky** [comment]
We've had some trouble simulating radial turbomachinery in Fluent, CFX seems to be somewhat easier. We're working over at Queensland University of Technology.

Would the UDF function work for CFX?

**Comment by ibell** [comment]
No idea :)  In fact I don't know too much about how all the low level code
works for CFD, but implementing CoolProp ought to not be too hard.  Is CFX
FORTRAN or C/C++ based?
