### ISSUE TITLE
Expose DerivTerms

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#77]
I sometimes get requests from students and colleagues that need derivatives in their calculations. Unfortunately, only a few wrappers include the DerivTerms function. Could we add it to, for example, Matlab?

**Comment by ibell** [comment]
Sure.  MATLAB is a real pain to interface with other things, but go ahead
and add another entry in the Props.c file

**Comment by ibell** [comment]
I just had a brainstorm.  Let's re-implement DerivTerms in the CoolPropStateClass, and add all the derivatives you want to expose as keys in CoolProp so you can do something like:

Props('dpdtau__constdelta','T',300,'D',1,'R134a')

Then the keyed_output function of CoolPropStateClassSI will be modified to take in the derivative keys as well, which will mean that the derivatives are directly accessible using the same wrapper.  A much more elegant solution I think, and shouldn't be too painful to implement I hope.

**Comment by jowr** [comment]
Good idea! I currently do the Lithium Bromide thingy, but this one could be next...

Jorrit

## 

Jorrit Wronski
DTU Mechanical Engineering

Technical University of Denmark
Department of Mechanical Engineering
Nils Koppels Allé
Building 403 Room 111
2800 Kgs. Lyngby

phone: +45 45 25 41 83
email: jowr@mek.dtu.dk
http://www.mek.dtu.dk/english/Sections/TEShttp://www.tes.mek.dtu.dk/English

**Comment by ibell** [comment]
I slightly mis-spoke.  I think it should be in CoolPropStateClassSI, we
might want to consider doing the unit conversions to kSI in
CoolPropStateClass as well, but I would be fine if we just said that
DerivTerms ALWAYS returns SI units.  Up to you.

**Comment by jowr** [comment]
Almost done. Just one issue with the second Virial coefficient in the state class... You might want to have a look at https://github.com/ibell/coolprop/blob/derivToProps/CoolProp/CPState.cpp#L1908

Besides that one, the script in https://github.com/ibell/coolprop/blob/derivToProps/dev/Tickets/77.py gives the same numbers for old and new derivTerms...

**Comment by jowr** [comment]
Note to myself: I might want to use the critical density and not the reducing quantity.

**Comment by ibell** [comment]
@jowr I think you (almost) always want to use the reducing density

What's the issue with the second virial coefficient?  It didn't jump out at me looking at that line

**Comment by jowr** [comment]
The problem is that the new function gives other results than the old one and I have no clue why. Well, I will have a second try tomorrow and keep you updated.

**Comment by ibell** [comment]
How different are the results?

**Comment by jowr** [comment]
An example in Python gives results that differ:

```
fluid = "n-Pentane"
T = numpy.array([ 30,100,150,210])+273.15
D = numpy.array([710, 20, 20,210])

for key in keys:
    liquid    = CP.DerivTerms(key,T[0],D[0],fluid)*1000
    twophase  = CP.DerivTerms(key,T[1],D[1],fluid)*1000
    gaseous   = CP.DerivTerms(key,T[2],D[2],fluid)*1000
    supercrit = CP.DerivTerms(key,T[3],D[3],fluid)*1000
    print '{:<25}: {:>10.5f}; {:>10.5f}; {:>10.5f}; {:>10.5f}'.format(key,liquid,twophase,gaseous,supercrit)
```

Gives this in branch derivToProps:

```
Testing the derivatives and store results for b034e64353390c857c9550a0dad7136ded8bbd12
VB                       :    6.36743;   -9.46880;   -6.87321;   -3.12923
dBdT                     :    0.12943;    0.05959;    0.03857;    0.02511
VC                       :    0.00905;    0.00934;    0.00932;    0.00918
dCdT                     :    0.00001;    0.00000;   -0.00000;   -0.00000
```

... and this in master branch:

```
Testing the derivatives and store results for c5056c734ae6ac418e69a10586efc21dfae543b0
B                        :  -15.65283;   -9.46880;   -7.06913;   -5.20105
dBdT                     :    0.12943;    0.05959;    0.03857;    0.02511
C                        :    0.00905;    0.00934;    0.00932;    0.00918
dCdT                     :    0.00001;    0.00000;   -0.00000;   -0.00000
```

The others values from DerivTerms work fine...

**Comment by jowr** [comment]
Hm, I guess this issue needs some rest. I cannot figure it out now. Inputs are the same, but the function return a different rersult in new version. For debugging, I print the inputs `tau` and `rhoc` before the output gets printed :

```
../../CoolProp/CPState.cpp B(): 1.5494,232
../../CoolProp/CPState.cpp B(): 1.25874,232
../../CoolProp/CPState.cpp B(): 1.11001,232
../../CoolProp/CPState.cpp B(): 0.972162,232
VB                       :    6.36743;   -9.46880;   -6.87321;   -3.12923
dBdT                     :    0.12943;    0.05959;    0.03857;    0.02511
dphir_dDelta             : 1477.24431; -2161.30296; -1594.58410; -725.98171
```

and old version:

```
../../CoolProp/CoolProp.cpp B(): 1.5494,232
../../CoolProp/CoolProp.cpp B(): 1.25874,232
../../CoolProp/CoolProp.cpp B(): 1.11001,232
../../CoolProp/CoolProp.cpp B(): 0.972162,232
B                        :  -15.65283;   -9.46880;   -7.06913;   -5.20105
dBdT                     :    0.12943;    0.05959;    0.03857;    0.02511
dphir_dDelta             : 1477.24431; -2161.30296; -1594.58410; -725.98171
```

The function is also the same in new version:

```
return 1.0/pFluid->reduce.rho*dphir_dDelta(tau,1e-12);
```

and old version: 

```
return 1.0/rhoc*pFluid->dphir_dDelta(tau,1e-12);
```

**Comment by jowr** [comment]
Ah, it was my fault. I used the cached derivatives, but my input did not correspond with the state: 1e-12 != delta_state...

```
../../CoolProp/CPState.cpp B(): 1.5494,232
../../CoolProp/CPState.cppStateClass dphir_dDelta(1.5494,1e-12) = 1.47724
../../CoolProp/CPState.cppFluidClass dphir_dDelta(1.5494,1e-12) = -3.63146
../../CoolProp/CPState.cpp B(): 1.25874,232
../../CoolProp/CPState.cppStateClass dphir_dDelta(1.25874,1e-12) = -2.19676
../../CoolProp/CPState.cppFluidClass dphir_dDelta(1.25874,1e-12) = -2.19676
../../CoolProp/CPState.cpp B(): 1.11001,232
../../CoolProp/CPState.cppStateClass dphir_dDelta(1.11001,1e-12) = -1.59458
../../CoolProp/CPState.cppFluidClass dphir_dDelta(1.11001,1e-12) = -1.64004
../../CoolProp/CPState.cpp B(): 0.972162,232
../../CoolProp/CPState.cppStateClass dphir_dDelta(0.972162,1e-12) = -0.725982
../../CoolProp/CPState.cppFluidClass dphir_dDelta(0.972162,1e-12) = -1.20664
```

I'll fix it, but this basically means that caching is not possible for all functions that rely on the limes->0 contruction of the residual helmholtz energy...

**Comment by jowr** [comment]
Fixed derivative calculation and exposed unit conversion through CoolPropDLL. The Python wrapper now supports all kinds of unit conversions.
