### ISSUE TITLE
Bug Saturation line near critical point (Calculation in function of P)

### ISSUE THREAD

**Issue by EdwinSoft** [ibell/coolprop#78]
I am using Visual Studio 2013 (C++), Windows 8.1 and the last version of Coolpro 4.0Pre. I was trying to make graphs of the saturation lines as a function of  pressure and I used the next code:
# include "CoolProp.h"
# include <iostream>
# include <fstream>

using namespace std;
int main()
{
    if (!add_REFPROP_fluid("REFPROP-Water")) {
        printf("\nError REFPROP\n");
        getchar();
        return(-1);
    }
    char\* fluid1 = "Water";
    char\* fluid2 = "REFPROP-Water";
    const char listSep = ';';
    ofstream file;
    double Pcr = Props(fluid1, "pcrit");
    double p;
    file.open("examplePD.csv");
    file << "Pressure [kPa]" << listSep << "Dl[kg/m^3](Water)" << listSep << "Dl[kg/m^3](REFPROP-Water)" << listSep << "Dg[kg/m^3](Water)" << listSep << "Dg[kg/m^3](REFPROP-Water)" << endl;
    p = Pcr;
    do{
        file << p << listSep << Props('D', 'P', p, 'Q', 0.0, fluid1) << listSep << Props('D', 'P', p, 'Q', 0.0, fluid2) << listSep << Props('D', 'P', p, 'Q', 1.0, fluid1) << listSep << Props('D', 'P', p, 'Q', 1.0, fluid2) << endl;
        p -= 1;
    } while (p >= Pcr-30.0);
    file.close();
    return 0;
}

When I draw the data, I get the following:

![ej1](https://f.cloud.github.com/assets/5746631/1608091/fc40b2de-54ca-11e3-9f26-3d43e33891ab.png)

I debug the program and noticed that the problem was in the tolerance value of the function Brent().

in FluidClass.cpp, Line 3017, I changed 
double tau = Brent(&SatFunc,tau_min,tau_max,1e-10,1e-4,50,&errstr);
by
double tau = Brent(&SatFunc,tau_min,tau_max,1e-10,1e-8,50,&errstr);
and I got good graphics.

![ej2](https://f.cloud.github.com/assets/5746631/1608092/0dcc8e60-54cb-11e3-919e-48faa3e3c4d6.png)

**Comment by ibell** [comment]
Ah ok, I made the change, thanks for noticing that.  1e-4 is a pretty loose
tolerance, and we should be able to get to 1e-8 without problems.

Ian
