### ISSUE TITLE
Thermal Conductivity issue R134a (and potentially R404a)

### ISSUE THREAD

**Issue by bachc** [ibell/coolprop#79]
There seems to be some significant differences in the property calculations between r4.0.0 beta and r2.3. These result in about 12% difference in the Shah 2 phase evap HT coefficient (attached images). According to Ian this seems to be a result of the thermal conductivity calculations for R134a. I couldn't match my old evaporator calculations for R404a and think it might be related to the same issue for R404a.

Please check and fix. Thanks!

![shah_2_3](https://f.cloud.github.com/assets/2520741/1626962/c105ae9c-56e9-11e3-9946-c086c46234b6.png)
![shah_400beta](https://f.cloud.github.com/assets/2520741/1626963/c398f8e4-56e9-11e3-8a2d-5689b55c924a.png)

**Comment by bachc** [comment]
I think the R404a might be unrelated, accidentally added a bug in my evaporator code.

**Comment by ibell** [comment]
I have identified the problem with R134a (critical region term), and
will fix it (and other fluids that use the same code) this afternoon
or tomorrow.

**Comment by ibell** [comment]
Fixed.
