### ISSUE TITLE
Would be nice to get CoolProp working with Java

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#8]

**Comment by jowr** [comment]
I'll have a look.

**Comment by ibell** [comment]
I started playing with SWIG on windows, but I'm stuck with the
compilation.  I'll take a crack on linux and see if I can make progress at
least in linux.

Ian

**Comment by jowr** [comment]
This does the job on Linux:

#!/bin/bash
#
#cd ../../CoolProp
NAME=CoolProp
SRCD="../../${NAME}"
PACK=net.sf.coolprop
JDIR=/usr/lib/jvm/java-6-openjdk/include
#
INCL="-I${JDIR} -I${SRCD}"
#
swig -c++ -java -package ${PACK} -outcurrentdir ${SRCD}/${NAME}.i
g++ -fpic -c ${NAME}_wrap.cxx ${INCL} # -I/usr/java/include -I/usr/java/include/solaris
g++ -fpic -c ${SRCD}/${NAME}DLL.cpp ${INCL}
g++ -shared ${NAME}_wrap.o ${NAME}.o -o lib${NAME}DLL.so
javac *.java

Cheers,
Jorrit

## 

Jorrit Wronski
DTU Mechanical Engineering

Technical University of Denmark
Department of Mechanical Engineering
Nils Koppels Allé
Building 403 Room 111
2800 Kgs. Lyngby

phone: +45 45 25 41 83
email: jowr@mek.dtu.dk
http://www.tes.mek.dtu.dk/English

**Comment by ibell** [comment]
wow, that was fast.  no chance you have an example of running it too?  And
can you commit that script into a wrappers/Java folder?

**Comment by ibell** [comment]
On windows, this version works for Java : 25051260c90d9d2d45b5a82304000f2f9b0919da

**Comment by ibell** [comment]
For linux, I am having a lot of problems, I think they might be related to openjdk, so I want to try using sun java.  Btw, your script is missing the compilation of the coolprop source files as well.  See my windows batch files

**Comment by jowr** [comment]
Hi, the reason I did not commit things is that I am currently trying to convert the build process to scons. I think it is not nice having to compile the big binary library everytime you make a wrapper. A shared system library is just as good and saves compile time... 
What do you think?

**Comment by ibell** [comment]
Are you thinking of using the same static library for all wrappers? This
has a great deal of appeal, and I think I am on board.  The only trick is
dealing with all the possible combinations of compiler flags and 32-/64-bit
compilation

**Comment by abcfy2** [comment]
Hi @jowr .
I use your bash script to build. But I get some errors.

I have installed `openjdk-7-jdk`, so I have to modify this line `JDIR=/usr/lib/jvm/java-7-openjdk-amd64/include`. Then I get this error `g++: error: CoolProp.o: No such file or directory`.

Could you give me a hand ?

**Comment by ibell** [comment]
Can you give a full log of the output from that script?  There must be an error above.

**Comment by abcfy2** [comment]
@ibell 
All right, here is my script. Just from @jowr 

``` bash
$ pwd
/home/fengyu/coolprop/wrappers/Java

$ cat build.sh 
#!/bin/bash
#
#cd ../../CoolProp
NAME=CoolProp
SRCD="../../${NAME}"
PACK=net.sf.coolprop
JDIR=/usr/lib/jvm/java-7-openjdk-amd64/include
#
INCL="-I${JDIR} -I${SRCD}"
#
swig -c++ -java -package ${PACK} -outcurrentdir ${SRCD}/${NAME}.i
g++ -fpic -c ${NAME}_wrap.cxx ${INCL} # -I/usr/java/include -I/usr/java/include/solaris
g++ -fpic -c ${SRCD}/${NAME}DLL.cpp ${INCL}
g++ -shared ${NAME}_wrap.o ${NAME}.o -o lib${NAME}DLL.so
#javac *.java

$ ./build.sh
./build.sh 
g++: error: CoolProp.o: No such file or directory
```

And I attempt to clean up the directory and exec the script line by line manually

``` bash
~/coolprop/wrappers/Java$ git status
nothing to commit, working directory clean

~/coolprop/wrappers/Java$ NAME=CoolProp
~/coolprop/wrappers/Java$ SRCD="../../${NAME}"
~/coolprop/wrappers/Java$ PACK=net.sf.coolprop
~/coolprop/wrappers/Java$ JDIR=/usr/lib/jvm/java-7-openjdk-amd64/include
~/coolprop/wrappers/Java$ INCL="-I${JDIR} -I${SRCD}"
~/coolprop/wrappers/Java$ swig -c++ -java -package ${PACK} -outcurrentdir ${SRCD}/${NAME}.i
~/coolprop/wrappers/Java$ git status
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#   CoolProp.java
#   CoolPropConstants.java
#   CoolPropJNI.java
#   CoolProp_wrap.cxx
#   SWIGTYPE_p_a_2__double.java
#   SWIGTYPE_p_double.java
#   SWIGTYPE_p_std__string.java
#   SWIGTYPE_p_std__vectorT_double_t.java
#   SWIGTYPE_p_std__vectorT_std__string_t.java
#   fluid_types.java
#   params.java
#   phases.java
#   unit_constants.java
#   unit_systems.java
nothing added to commit but untracked files present (use "git add" to track)

~/coolprop/wrappers/Java$ g++ -fpic -c ${NAME}_wrap.cxx ${INCL} 
~/coolprop/wrappers/Java$ g++ -fpic -c ${SRCD}/${NAME}DLL.cpp ${INCL}
~/coolprop/wrappers/Java$ g++ -shared ${NAME}_wrap.o ${NAME}.o -o lib${NAME}DLL.so
g++: error: CoolProp.o: No such file or directory
~/coolprop/wrappers/Java$ git status
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#   CoolProp.java
#   CoolPropConstants.java
#   CoolPropJNI.java
#   CoolProp_wrap.cxx
#   SWIGTYPE_p_a_2__double.java
#   SWIGTYPE_p_double.java
#   SWIGTYPE_p_std__string.java
#   SWIGTYPE_p_std__vectorT_double_t.java
#   SWIGTYPE_p_std__vectorT_std__string_t.java
#   fluid_types.java
#   params.java
#   phases.java
#   unit_constants.java
#   unit_systems.java
nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by ibell** [comment]
I think the equivalent of this line is missing:

cl /c /MP3 /I../../CoolProp /I"C:\Program Files\Java\jdk1.7.0_40\include"
/I"C:\Program Files\Java\jdk1.7.0_40\include\win32" /EHsc
../../CoolProp/*.cpp

The sources for CoolProp are not getting compiled.  Try a

g++ -fpic  ${INCL} -c ../../CoolProp/*.cpp

That help?
