### ISSUE TITLE
Error in the member function "check_saturated_quality"

### ISSUE THREAD

**Issue by EdwinSoft** [ibell/coolprop#80]
I was checking the code in the CPstate.cpp file and found the following:

void CoolPropStateClassSI::check_saturated_quality(double Q){
    double mach_eps = 10*DBL_EPSILON;
    if (fabs(Q-1) < mach_eps){
        SaturatedL = true; SaturatedV = false;
    }
    else if (fabs(Q) < mach_eps){
        SaturatedL = false; SaturatedV = true;
    }
    else{
        SaturatedL = false; SaturatedV = false;
    }
}

I think it should be:

void CoolPropStateClassSI::check_saturated_quality(double Q){
    double mach_eps = 10*DBL_EPSILON;
    if (fabs(Q-1) < mach_eps){
        SaturatedL = false; SaturatedV = true;
    }
    else if (fabs(Q) < mach_eps){
        SaturatedL = true; SaturatedV = false;
    }
    else{
        SaturatedL = false; SaturatedV = false;
    }
}

or am I wrong?

**Comment by ibell** [comment]
No, you are right.  I don't know why the code was like that, but there is
no question that you are correct.  Do you know how to make a pull request?
Do you use git?  You can even make the changes by going to
https://github.com/ibell/coolprop/blob/master/CoolProp/CPState.cpp and
clicking the edit button.  I would be happy to have you make the changes
yourself.  I've added you as a contributor.

**Comment by EdwinSoft** [comment]
Ok Ibell, thanks.
Yes I am using Git, I will try to make the changes, I like programming but
I've never worked with a repository ;)

2013/11/29 Ian Bell notifications@github.com

> No, you are right. I don't know why the code was like that, but there is
> no question that you are correct. Do you know how to make a pull request?
> Do you use git? You can even make the changes by going to
> https://github.com/ibell/coolprop/blob/master/CoolProp/CPState.cpp and
> clicking the edit button. I would be happy to have you make the changes
> yourself. I've added you as a contributor.
> 
> On Fri, Nov 29, 2013 at 11:40 AM, EdwinSoft notifications@github.comwrote:
> 
> > I was checking the code in the CPstate.cpp file and found the following:
> > 
> > void CoolPropStateClassSI::check_saturated_quality(double Q){
> > double mach_eps = 10*DBL_EPSILON;
> > if (fabs(Q-1) < mach_eps){
> > SaturatedL = true; SaturatedV = false;
> > }
> > else if (fabs(Q) < mach_eps){
> > SaturatedL = false; SaturatedV = true;
> > }
> > else{
> > SaturatedL = false; SaturatedV = false;
> > }
> > }
> > 
> > I think it should be:
> > 
> > void CoolPropStateClassSI::check_saturated_quality(double Q){
> > double mach_eps = 10*DBL_EPSILON;
> > if (fabs(Q-1) < mach_eps){
> > SaturatedL = false; SaturatedV = true;
> > }
> > else if (fabs(Q) < mach_eps){
> > SaturatedL = true; SaturatedV = false;
> > }
> > else{
> > SaturatedL = false; SaturatedV = false;
> > }
> > }
> > 
> > or am I wrong?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ibell/coolprop/issues/80>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ibell/coolprop/issues/80#issuecomment-29544055
> .

## 

-Edwin-

**Comment by ibell** [comment]
Perhaps the easiest for now would be just to make the change in the web
interface then.  Its very simple.
