### ISSUE TITLE
scilab

### ISSUE THREAD

**Issue by fxhillion** [ibell/coolprop#83]
hi
is there a way to use coolprop with scilab ?
rgds

**Comment by ibell** [comment]
Working on it, linux/OSX should be possible, windows ~impossible, but I am
running into all kinds of problems with Scilab.  Rest assured you are not
the first person to ask about that.

**Comment by fxhillion** [comment]
many thanks and good luck with it ! i am looking forward to using it !

**Comment by ibell** [comment]
For now its gonna have to be octave on windows.  The scilab devs and I have
been working together, but overall scilab seems pretty buggy to me, which
doesn't give me a lot of confidence that we will sort it out quickly, for
even linux/OSX.  And it requires SWIG as well, which has its own issues.
