### ISSUE TITLE
coolprop.org and redirect to documentation

### ISSUE THREAD

**Issue by Rod-Persky** [ibell/coolprop#92]
+enhancement of sorts, would it be sweet to grab a domain such as coolprop.org and redirect it to the documentation? I'd be cool to pitch in the requisite amount to but the domain for a few years.

**Comment by ibell** [comment]
I'd be happy to chip in as well.  I like the idea a lot!!

**Comment by jowr** [comment]
I am in as well. @Rod-Persky, do you have experience with domain hosting? If not, I can also do it... Thanks for picking this important issue up again.

**Comment by Rod-Persky** [comment]
I've done it so many times it is routine. I've sent @ibell the username and password for the domain service. It's there to have stuff setup on it, I've had experience with name.com and it's pretty sweet - I can send the details over to you too.

Anyway, the domain is paid up to 2018 (5 years). I did notice however that someone has got coolprop .com so hopefully by that time it can be absorbed or swapped to.

**Comment by jowr** [comment]
Great.
