### ISSUE TITLE
Entropy in EES

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#95]
The equation `s_9 = CoolProp('S','P',p_9,'T',T_9,fluid$)` gives an error in EES `CoolProp error: Your output key [s] is not valid. (names are case sensitive)`. Obviously, the `S` gets converted to `s`, which cannot be used as input.

**Comment by ibell** [comment]
This is an issue with case handling in EES.  I have put together a new
version of the coolprop wrapper that converts all input to upper case
which mostly resolves this issue, but now some fluids will not work.
Argh.  The core problem is that EES has changed back and forth between
being and not being case sensitive, which is a problem from our side.

**Comment by jowr** [comment]
Let's leave it all uppercase. I can go through the fluids and add uppercase aliases.

**Comment by jowr** [comment]
... or should we make the fluid list case-insensitive?

**Comment by ibell** [comment]
I think its cleaner to add uppercase aliases, but there are quite a few without them, so if you wanted to just make the fluid name not case sensitive, that would be ok with me too.  What we probably want to do is to add uppercase alias to the alias list for the fluid when it gets loaded into the FluidList in post_load function.

The code to find fluids without uppercase aliases

```
import CoolProp
from CoolProp.CoolProp import Props

for fluid in CoolProp.__fluids__:
    try:
        Props(fluid.upper(),'Tcrit')
    except:
        print fluid
```

which yields

```
Water
Helium
Oxygen
Hydrogen
ParaHydrogen
OrthoHydrogen
Argon
CarbonDioxide
Nitrogen
n-Propane
Ammonia
R1234ze(E)
Ethylene
SulfurHexafluoride
Ethanol
DimethylEther
DimethylCarbonate
n-Dodecane
Propylene
Cyclopentane
Benzene
n-Undecane
CycloPropane
Neon
Propyne
Fluorine
Methanol
R1234ze(Z)
R1233zd(E)
CarbonMonoxide
CarbonylSulfide
n-Decane
HydrogenSulfide
Isopentane
Neopentane
Isohexane
Krypton
n-Nonane
Toluene
Xenon
Acetone
NitrousOxide
SulfurDioxide
R141b
R142b
Methane
Ethane
n-Butane
IsoButane
n-Pentane
n-Hexane
n-Heptane
n-Octane
CycloHexane
1-Butene
IsoButene
cis-2-Butene
trans-2-Butene
MethylPalmitate
MethylStearate
MethylOleate
MethylLinoleate
MethylLinolenate
o-Xylene
m-Xylene
p-Xylene
EthylBenzene
Deuterium
ParaDeuterium
OrthoDeuterium
Air
```

**Comment by jowr** [comment]
OK, I added the aliases. Can you make a new EES wrapper?

**Comment by ibell** [comment]
Jorrit,

I think we still have some line ending issues.  None of the commits in the
last push were minimal diffs :
https://github.com/ibell/coolprop/compare/457c0cc8a215...e68a53043062 and
now I can't pull.

Thanks for adding the uppercase aliases! What a pain to do!

Ian

**Comment by ibell** [comment]
New installer for CoolProp_EES attached.  If you could let me know if it
works for you that would be great!

Ian

**Comment by jowr** [comment]
Did you attach it to the email? I am not sure I know where the file is...

**Comment by ibell** [comment]
Oops, I replied to the github message, but the attachment doesnt get posted
to the issue.  Ok, personal email this time

Ian

**Comment by jowr** [comment]
Haven't tried all possible inputs, but my problems are solved with the
new wrapper.
Let's hope that the line-ending mess stops as soon as evry file has been
checked out and checked in after the configuration change. Let us keep
an eye on that issue.

**Comment by jowr** [comment]
@ibell , can you upload your new code? I guess it is fixed.
