### ISSUE TITLE
CoolProp Support in Mathematica

### ISSUE THREAD

**Issue by gratitude38** [ibell/coolprop#96]
Hi, Ian! 

It is great that you have made CoolProp an open source. As the number of Mathematica users is increasing, it would be nice if Mathematica could call some CoolProp functions. I greatly appreciate your kind help if a special DLL for Mathematica is compiled. 

With gratitude

**Comment by ibell** [comment]
Added support in revision ba4c9f1710ff1a8781b74626b667923148824a34 in a preliminary form.  Follow instructions in wrappers/Mathematica/Readme.rst
